ADEN-10771 add medianet prebid
Wikia/ad-engine pull request #1021
Opened 2021-05-24 08:46 UTC by jakubbanas

2021-05-25 11:44 UTC, dmnsobczak commented on src/ad-bidders/prebid/adapters-registry.ts
> +import { Medianet } from './adapters/medianet';
Please group it into imports from `./adapters` above

2021-05-25 11:44 UTC, dmnsobczak commented on src/ad-bidders/prebid/adapters-registry.ts
> +		Medianet,
Alphabetical order

2021-05-25 11:44 UTC, dmnsobczak commented on src/platforms-shared/bidders-state-setup.ts
> +		context.set('bidders.prebid.medianet.enabled', instantConfig.get('icPrebidMedianet'));
Alphabetical order

2021-05-25 11:45 UTC, dmnsobczak commented on src/ad-bidders/prebid/prebid-models.ts
> +	cid?: string;
Alphabetical order

2021-05-25 12:07 UTC, dmnsobczak requested changes
See comments

2021-05-25 12:10 UTC, dmnsobczak commented on src/ad-bidders/prebid/adapters-registry.ts
> +import { Medianet } from './adapters/medianet';
Oh, now I know why you did it this way. Add Medianet class here:
https://github.com/Wikia/ad-engine/blob/c5a28e26f14b6f7ce8f53b335098458a89bc9129/src/ad-bidders/prebid/adapters/index.ts#L18

2021-05-25 13:56 UTC, jakubbanas commented on src/ad-bidders/prebid/adapters-registry.ts
> +import { Medianet } from './adapters/medianet';
Auto import 🤦‍♂️

2021-05-26 06:47 UTC, dmnsobczak approved these changes

2021-05-27 08:40 UTC, merged