setting stroer variable
Wikia/ad-engine pull request #1025
Opened 2021-05-26 10:53 UTC by Mariusz8Walczak

2021-05-26 11:43 UTC, preludek requested changes

2021-05-26 11:43 UTC, preludek commented on src/ad-services/stroer/index.ts
> +		return utils.scriptLoader.loadScript(libraryUrl, 'text/javascript', true).then(() => {
You don't need to pass `'text/javascript'` and `true` here. Those are default values in scriptLoader.loadScript method.

2021-05-26 11:43 UTC, preludek commented on src/ad-services/stroer/index.ts
> +export const stroer = new Stroer();
This class is not used anywhere. You need to call it in on platforms in callExternals, fe:
https://github.com/Wikia/ad-engine/blob/dev/platforms/ucp-desktop/modes/ucp-desktop-ads.mode.ts#L69

2021-05-26 14:22 UTC, Loczi94 submitted a review, later dismissed
Label major/minor/patch is missing.

What is more, unit tests are missing. We have unit tests for all services in `ad-engine/spec/ad-services.`

2021-05-28 09:25 UTC, Mariusz8Walczak commented on src/ad-services/stroer/index.ts
> +		return utils.scriptLoader.loadScript(libraryUrl, 'text/javascript', true).then(() => {
thanks

2021-05-28 09:33 UTC, Mariusz8Walczak commented on src/ad-services/stroer/index.ts
> +export const stroer = new Stroer();
thanks, done

2021-05-28 10:32 UTC, Mariusz8Walczak commented
There are no test, becouse when ic flag is on, script will be loaded, now is false, I think makeing test that are depended on something external for very basic code, that was used many times is mistake.

2021-05-28 13:24 UTC, Loczi94 commented
In tests we don't read icVar from Instant Config service. We set it to a specific value in ad-engine context. I know it is a dummy test but better have one dummy test than none.

2021-06-01 12:31 UTC, dmnsobczak commented on platforms/shared/setup/base-context.setup.ts
> +		context.set('services.stroer.enabled', this.instantConfig.get('icStroer'));
Can we move it to L144 to keep alphabetical order?

2021-06-01 12:33 UTC, dmnsobczak commented on platforms/ucp-mobile/modes/ucp-mobile-ads.mode.ts
> +		stroer.call();
Missing this set for `platforms/ucp/modes/ucp-ads-mode.ts`

2021-06-01 12:36 UTC, dmnsobczak commented on src/ad-services/stroer/index.ts
> +const logGroup = 'Stroer';
Let's keep (sadly, not always followed :<) conversion to use lowercase + dash for log groups :)

2021-06-01 12:39 UTC, dmnsobczak requested changes
Missing UCP (Oasis) implementation.

2021-06-01 12:47 UTC, Mariusz8Walczak commented on src/ad-services/stroer/index.ts
> +const logGroup = 'Stroer';
ok

2021-06-01 12:50 UTC, Mariusz8Walczak commented on platforms/ucp-mobile/modes/ucp-mobile-ads.mode.ts
> +		stroer.call();
Ok, I will add

2021-06-01 12:50 UTC, Mariusz8Walczak commented on src/ad-services/stroer/index.ts
> +const logGroup = 'Stroer';
added lowercase

2021-06-01 12:59 UTC, Mariusz8Walczak commented on platforms/shared/setup/base-context.setup.ts
> +		context.set('services.stroer.enabled', this.instantConfig.get('icStroer'));
L143 is done

2021-06-01 13:08 UTC, dmnsobczak approved these changes

2021-06-01 13:27 UTC, preludek approved these changes

2021-06-01 13:31 UTC, dmnsobczak commented on src/ad-services/index.ts
> +export * from './stroer';
`ST` should be after `SI` :D

2021-06-07 11:21 UTC, merged