ADEN-11007 | feat: move TOC under BFAA on start and complete state
Wikia/ad-engine pull request #1026
Opened 2021-05-27 14:08 UTC by Tomasz-at-Fandom

2021-05-28 09:18 UTC, Loczi94 requested changes

2021-05-28 09:18 UTC, Loczi94 commented on src/ad-products/video/porvata4/porvata-player.ts
> +		}
What about creating a separate handler and adding it to stickyBig and stickySmall states here: https://github.com/Wikia/ad-engine/blob/dev/platforms/ucp-mobile/templates/bfaa-new-template.ts?

2021-06-01 13:04 UTC, dmnsobczak commented on src/ad-products/video/porvata4/porvata-player.ts
> +				name: 'Porvata',
In RealVu pull request I added a feature to skip second argument:
https://github.com/Wikia/ad-engine/pull/1006/files#diff-50e4c1249aa3095f147eea2fd8ee626809020070724d90d931b08ce57724467cR39
You can copy those changes and remove object passed as second parameter since you're ignoring `props` on UCP side anyway 🤔

2021-06-01 13:04 UTC, dmnsobczak approved these changes

2021-06-07 13:21 UTC, merged