Aden 10999 transition state
Wikia/ad-engine pull request #1038
Opened 2021-06-11 10:47 UTC by Mariusz8Walczak

2021-06-11 11:20 UTC, preludek requested changes

2021-06-11 11:20 UTC, preludek commented on platforms/shared/templates/handlers/slot/slot-decision-sticky-small-to-transition-handler.ts
> +import {
Since this is pretty much the same code as SlotDecisionTimeoutHandler, why don't we just use SlotDecisionTimeoutHandler? :)

2021-06-11 11:20 UTC, preludek commented on platforms/ucp-mobile/templates/bfaa-new-template.ts
> +import { SlotTransitionNewTemplateHandler } from '../../shared/templates/handlers/slot/slot-transition-new-template-handler';
Both of those imports should be moved top to imports from @platforms/shared and exported in ad-engine/platforms/shared/index.ts

2021-06-11 11:20 UTC, preludek commented on platforms/shared/templates/handlers/slot/slot-transition-handler.ts
> +					const tlbPlaceholder = document.querySelector('.ad-slot-placeholder.top-leaderboard');
Why this change here? This is breaking for UAP 2.0 and potentially may cause regression.

2021-06-11 11:37 UTC, Mariusz8Walczak commented on platforms/shared/templates/handlers/slot/slot-decision-sticky-small-to-transition-handler.ts
> +import {
because I didn't know about its existance when I was doing it, I discovered it after PR was made. Sonia told me, that oh Damian have similar thing to your

2021-06-11 11:38 UTC, Mariusz8Walczak commented on platforms/shared/templates/handlers/slot/slot-transition-handler.ts
> +					const tlbPlaceholder = document.querySelector('.ad-slot-placeholder.top-leaderboard');
yep, I must remove that chamge, becaouse I didn't touch that file in that task, something went wrong

2021-06-11 11:43 UTC, Mariusz8Walczak commented on platforms/shared/templates/handlers/slot/slot-decision-sticky-small-to-transition-handler.ts
> +import {
done

2021-06-11 11:46 UTC, Mariusz8Walczak commented on platforms/shared/templates/handlers/slot/slot-transition-handler.ts
> +					const tlbPlaceholder = document.querySelector('.ad-slot-placeholder.top-leaderboard');
done

2021-06-11 11:50 UTC, Mariusz8Walczak commented on platforms/ucp-mobile/templates/bfaa-new-template.ts
> +import { SlotTransitionNewTemplateHandler } from '../../shared/templates/handlers/slot/slot-transition-new-template-handler';
done

2021-06-11 15:47 UTC, preludek commented on platforms/shared/templates/handlers/slot/slot-transition-new-template-handler.ts
> +			.setProperty('marginTop', `-${this.reader.getSlotHeightResolved() * 2}px`);
I'm not sure if it's suppose to be margin-top or just top 🙈  we need to keep that one in mind in case some positioning issues with UAP.

2021-06-11 15:48 UTC, preludek approved these changes

2021-06-13 16:32 UTC, Mariusz8Walczak commented on platforms/shared/templates/handlers/slot/slot-transition-new-template-handler.ts
> +			.setProperty('marginTop', `-${this.reader.getSlotHeightResolved() * 2}px`);
yep, Top didn't work it was my main problem

2021-06-15 09:17 UTC, dmnsobczak commented
Please name Pull Requests properly for better readability in commits tree :)

2021-06-16 10:58 UTC, preludek requested changes

2021-06-16 10:58 UTC, preludek commented on platforms/shared/templates/handlers/slot/slot-decision-timeout-handler-wihtout-scroll.ts
> +export class SlotDecisionTimeoutHandlerWihtoutScroll implements TemplateStateHandler {
There's a typo in `SlotDecisionTimeoutHandlerWihtoutScroll` and all it's uses in other files.

2021-06-16 10:58 UTC, preludek commented on platforms/shared/templates/handlers/slot/slot-decision-timeout-handler-wihtout-scroll.ts
> +					transition('transition');
Shouldn't this be returned (it is in other handlers)?

2021-06-16 10:58 UTC, preludek commented on platforms/ucp-mobile/templates/bfaa-new-template.ts
> +				SlotDecisionTimeoutHandler,
Is this one necessary if you are you using `SlotDecisionTimeoutHandlerWihtoutScroll`?

2021-06-17 06:13 UTC, Mariusz8Walczak commented on platforms/shared/templates/handlers/slot/slot-decision-timeout-handler-wihtout-scroll.ts
> +					transition('transition');
it made in the same way as in SlotDecisionEmbeddedSmallToStickySmallHandler, every slot handler is setting up transition like that.

2021-06-17 07:24 UTC, preludek approved these changes

2021-06-17 13:41 UTC, merged