ADEN-11063 Fix transition from embedded big to embedded resolved
Wikia/ad-engine pull request #1040
Opened 2021-06-13 08:07 UTC by preludek

2021-06-14 07:51 UTC, Tomasz-at-Fandom approved these changes

2021-06-15 13:22 UTC, Tomasz-at-Fandom requested changes

2021-06-15 13:22 UTC, Tomasz-at-Fandom commented on platforms/shared/templates/handlers/slot/slot-decision-embedded-big-to-embedded-resolved-handler.ts
> +			.subscribe();
Please put this `subscription` in to a separate private method. Maybe `videoTransition()` ?

2021-06-15 13:22 UTC, Tomasz-at-Fandom commented on platforms/shared/templates/handlers/slot/slot-decision-embedded-big-to-embedded-resolved-handler.ts
>  		this.timeout
Please put this subscription in to a separate private method. Maybe staticTransition() ?

2021-06-15 13:26 UTC, Tomasz-at-Fandom commented on platforms/shared/templates/handlers/slot/slot-decision-embedded-big-to-embedded-resolved-handler.ts
>  		this.timeout
I could not mark the whole block of code, for some reason, this is for the lines 27-34 on the feature branch.

2021-06-15 13:55 UTC, preludek commented on platforms/shared/templates/handlers/slot/slot-decision-embedded-big-to-embedded-resolved-handler.ts
> +			.subscribe();
Good idea. Done.

2021-06-15 13:55 UTC, preludek commented on platforms/shared/templates/handlers/slot/slot-decision-embedded-big-to-embedded-resolved-handler.ts
>  		this.timeout
Good idea. Done.

2021-06-15 14:08 UTC, Tomasz-at-Fandom approved these changes

2021-06-16 11:36 UTC, merged