ADEN-11079 | ucp-mobile: UAP 3.0 fix bug on infobox pages + fix transitions between embedded and sticky states
Wikia/ad-engine pull request #1046
Opened 2021-06-18 10:24 UTC by Loczi94

2021-06-21 08:32 UTC, Mariusz8Walczak commented on platforms/shared/styles/uap/_bfaa-embedded-small.scss
>  				position: absolute;
why we don't use common style rule, for embedded-big and small? they have very much in common

2021-06-21 08:37 UTC, Mariusz8Walczak reviewed
I found that sticky small and sticky big are almoust the same, can we just make some common rules in css for both of them and TS classes. It will bite us, when something will change. We need only one place to make changes, not few ones.

2021-06-21 08:37 UTC, Mariusz8Walczak commented on platforms/shared/styles/uap/_bfaa-sticky-small.scss
> +		position: fixed;
why we don't use common style rule, for embedded-big and small? they have very much in common

2021-06-21 09:22 UTC, preludek requested changes

2021-06-21 09:22 UTC, preludek commented on platforms/shared/styles/index.scss
> +@import 'uap/_bfaa-with-infobox';
underscore 😈

2021-06-21 09:22 UTC, preludek commented on platforms/shared/styles/uap/_bfaa-with-infobox.scss
> +			left: 0px;
left: 0

2021-06-21 09:22 UTC, preludek commented on platforms/shared/styles/uap/_bfaa-sticky-big.scss
> +		top: 55px;
Since this is coming back, maybe we should move it to some sort of a variable so we know that this is navbar height?

2021-06-21 09:22 UTC, preludek commented on platforms/shared/templates/handlers/slot/slot-decision-embedded-small-to-sticky-small-handler.ts
> +					transition('stickySmall');
I'm still not sure either this should be returned or not (or does it even matter 🙈 ).

2021-06-21 09:22 UTC, preludek commented on platforms/shared/styles/uap/_bfaa-embedded-small.scss
>  				position: absolute;
Also wondering if this can be somehow reused 🤔

2021-06-21 09:58 UTC, Loczi94 commented on platforms/shared/templates/handlers/slot/slot-decision-embedded-small-to-sticky-small-handler.ts
> +					transition('stickySmall');
Wait, what should be returned (or not) and why? 😄

2021-06-21 13:00 UTC, Loczi94 commented on platforms/shared/styles/uap/_bfaa-sticky-small.scss
> +		position: fixed;
I replaced mixins `bfaa-embedded-big`, `bfaa-embedded-small` and `bfaa-embedded-resolved` by one mixin - `bfaa-embedded`.

2021-06-21 14:06 UTC, Loczi94 commented
@Mariusz8Walczak @preludek I replaced mixins `bfaa-embedded-big`, `bfaa-embedded-small` and `bfaa-embedded-resolved` by one mixin - `bfaa-embedded` because all three above were the same. However, I'd rather leave separate styles for `bfaa-sticky-big` and `bfaa-sticky-small`. I know, they have common parts but imo it's more clear if we have separate mixins and separate CSS classes for these two states instead of having some common styles in one mixin and then other styles for example in separate classes. What do you think?

2021-06-21 14:10 UTC, preludek approved these changes

2021-06-23 13:39 UTC, Tomasz-at-Fandom approved these changes

2021-06-25 14:07 UTC, merged