ADEN-11083 Fixing BLB position
Wikia/ad-engine pull request #1050
Opened 2021-06-23 08:03 UTC by dmnsobczak

2021-06-23 11:31 UTC, Tomasz-at-Fandom approved these changes

2021-06-25 09:12 UTC, Tomasz-at-Fandom requested changes

2021-06-25 09:12 UTC, Tomasz-at-Fandom commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +				(slots[slotName].insertBeforeSelector || slots[slotName].parentContainerSelector)
This is getting hard to read. 

When the slot contains the `parentContainerSelector` property, shouldn't we also check if the slot definition contains the `insertIntoParentContainerMethod` property?

I'm not completely sure what is the purpose of this conditional statement. I understand the first part that the slot cannot be `incontent_boxad_1`. But the second condition is a bit confusing. The slot must contain either a selector to insert the slot before it (on the same level of nesting) or a selector for an element inside which the slot will be nested? 

So we are basically validating the slot definition to check if it contains information on how to insert the slot. So for the validation to be complete we should also check if the `insertIntoParentContainerMethod` exists in the case of a slot that is to be nested inside `parentContainerSelector`.

If I'm correct, can we extract this second condition into a private method, like `insertionMethodValidation()`?

2021-06-25 09:24 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +				(slots[slotName].insertBeforeSelector || slots[slotName].parentContainerSelector)
> I understand the first part that the slot cannot be incontent_boxad_1. But the second condition is a bit confusing. The slot must contain either a selector to insert the slot before it (on the same level of nesting) or a selector for an element inside which the slot will be nested?
That's right. 

> we should also check if the insertIntoParentContainerMethod exists in the case of a slot that is to be nested inside parentContainerSelector
No, this option have a default values defined in `slotInjector`.

> can we extract this second condition into a private method
Ideally would be to extract this to `SlotInjector` class, but since we still have old style slot injecting mechanism used on legacy platforms it's better not to add anything there before we do some cleanup first.

2021-06-25 09:50 UTC, Tomasz-at-Fandom approved these changes

2021-06-25 09:50 UTC, Tomasz-at-Fandom commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +				(slots[slotName].insertBeforeSelector || slots[slotName].parentContainerSelector)
OK, thanks for explaining.

2021-06-28 09:13 UTC, merged