ADEN-11045 | feat: UAP embedded placeholder size always big
Wikia/ad-engine pull request #1075
Opened 2021-07-22 16:11 UTC by Tomasz-at-Fandom

2021-07-23 08:35 UTC, dmnsobczak commented on platforms/ucp-mobile/styles.scss
> +			min-height: 211px;
What is this value? UAP can have different ratios and different sizes. It probably will work for most of use cases, but it's not ideal and can cause layout shift for some campaigns. Maybe let's introduce some additional padding and position UAP in the center?

2021-07-23 08:36 UTC, dmnsobczak commented on platforms/shared/templates/helpers/uap-dom-manager.ts
> +	addClassToAdSlot(className: string): void {
This is a breaking change and it conflict with the fix I prepared here:
https://github.com/Wikia/ad-engine/pull/1071/files#diff-e78632dbc387b1dfd9e869ee83eedecb275dd1dbde54932d78d8582c3910de0eR4
Let's talk and figure out merge conflicts :)

2021-07-23 08:37 UTC, dmnsobczak requested changes
Changes will conflict with changes/fixes in different ticket. This one will probably go second so let's discuss how to solve them.

2021-07-26 13:39 UTC, Tomasz-at-Fandom commented on platforms/shared/templates/helpers/uap-dom-manager.ts
> +	addClassToAdSlot(className: string): void {
We can have both of these functions if they are needed, but we should review their uses together.

2021-07-27 13:07 UTC, dmnsobczak commented on platforms/ucp-mobile/styles.scss
> +			min-height: 211px;
@sseyda What's the biggest (most square) UAP aspect ratio we're using?

2021-07-27 13:08 UTC, dmnsobczak approved these changes

2021-07-27 14:31 UTC, sseyda commented on platforms/ucp-mobile/styles.scss
> +			min-height: 211px;
@dmnsobczak as per slack, UAPs are using following sizes: 1600x400 for Desktop, 640x360 for mobile for impacts and 1600x160 and 640x213 for resolved state.

2021-07-28 05:51 UTC, dmnsobczak commented on platforms/ucp-mobile/styles.scss
> +			min-height: 211px;
Thank you! @Tomasz-at-Fandom consider using `min-height: 213px;` here then to remove that micro content shift :)

2021-07-28 07:16 UTC, Tomasz-at-Fandom commented on platforms/ucp-mobile/styles.scss
> +			min-height: 211px;
Thanks guys! I bumped it up to 213px 👍

2021-07-28 11:35 UTC, merged