Force TLB to be sticky for configuration 'icForceStickyTlb'
Wikia/ad-engine pull request #1108
Opened 2021-09-20 11:11 UTC by szymon-nawrocki

I've added support for displaying top_leaderboard as sticky to maximize viewability. 
For more information see ticket ADEN-11234.

When configuration in icbm variable 'icForceStickyTlb' is met, top_leaderboard gets defaultTemplate='stickyTlb' and appears as sticky

2021-09-20 11:44 UTC, preludek requested changes
There are changes in package-lock.json that shouldn't be here.

2021-09-20 11:44 UTC, preludek commented on platforms/shared/templates/handlers/sticky-tlb/sticky-tlb-blocking-handler.ts
> +		if (context.get('templates.stickyTlb.forced')) {
I would move that to a separate function f.e. isStickyForced or something like that. It should not be a part of isLineAndGeo imo.

2021-09-20 12:52 UTC, szymon-nawrocki commented on platforms/shared/templates/handlers/sticky-tlb/sticky-tlb-blocking-handler.ts
> +		if (context.get('templates.stickyTlb.forced')) {
@preludek thanks for your input

### package-lock.json
Changes were caused by installing node dependencies with use of 'npm install' command instead of 'npm ci'. 
I installed dependencies once again with 'npm ci' command, but 'git status' did not show any changes, so i manually deleted the line of code which was added before.

### sticky-tlb-blocking-handler.ts 
I moved the functionality to separate function stickyTlbForced() as you suggested.

2021-09-21 06:10 UTC, szymon-nawrocki commented on platforms/shared/templates/handlers/sticky-tlb/sticky-tlb-blocking-handler.ts
> +		if (this.stickyTlbForced()) {
Okay, I've done the changes

2021-09-21 08:08 UTC, preludek approved these changes

2021-09-22 07:37 UTC, preludek approved these changes

2021-09-22 08:11 UTC, merged