ADEN 11129 - Stop loading ads on collapse/blocked event
Wikia/ad-engine pull request #1115
Opened 2021-10-01 11:20 UTC by szymon-nawrocki

**Ticket:** https://fandom.atlassian.net/browse/ADEN-11129
**CSS changes on unified-platform side:** https://github.com/Wikia/unified-platform/pull/7411

**What I tried to achieve:**
- stop loading ads for events: _blocked_, _collapse_, _forced_collapse_
- remove labels for stopped ads
- change label creation method from _::after_ pseudo-elements to _divs_

2021-10-01 11:25 UTC, szymon-nawrocki commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +					if (action['event'] === 'slotHidden') {
I observed, that the action event for _incontent_player_ is being send 2 times, so removeLabel() is also called x2

2021-10-04 07:55 UTC, preludek requested changes

2021-10-04 07:55 UTC, preludek commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +				statusesToStopLoadingSlot.map((status) => {
This mapping is done 4 times in this file. Can we move it to a utils function?

2021-10-04 07:55 UTC, preludek commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +const statusesToStopLoadingSlot: string[] = [
This could be a more specific type not an array of strings.

2021-10-05 15:45 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +const statusesToStopLoadingSlot: string[] = [
What do you think of making it an array of statics from AdSlot? 🤔
```ts
const statusesToStopLoadingSlot: string[] = [
  AdSlot.SLOT_RENDERED_EVENT,
  AdSlot.STATUS_BLOCKED,
  AdSlot.STATUS_COLLAPSE,
  AdSlot.STATUS_FORCED_COLLAPSE,
]
```

2021-10-05 15:46 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +					if (action['event'] === 'slotHidden') {
@dmnsobczak is it known? I don't recall and the only thing that comes to my mind is some kind of a leftover after Veles construction 🤔

2021-10-06 05:29 UTC, szymon-nawrocki commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +	} else if (withHide === 'parent') {
No there are not, but we only want additional action on one of two specific use cases, with `if-else` loop the loop will be entered every time, which we don't want.

Plus the function was originally created in _ucp-desktop-dynamic-slots.setup.ts_ file and it will be also used there.

2021-10-06 06:02 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +					if (action['event'] === 'slotHidden') {
I have no idea :( Maybe first hide event is after slot load and second after playback finished? Or are they fired at the same time?

2021-10-06 08:52 UTC, szymon-nawrocki commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +					if (action['event'] === 'slotHidden') {
@dmnsobczak They are fired at the same time

2021-10-06 11:05 UTC, preludek approved these changes

2021-10-08 13:56 UTC, merged