ADEN-11320 Nativo ad in Fan Feed on FandomMobile
Wikia/ad-engine pull request #1163
Opened 2021-11-02 16:59 UTC by nandy-andy

2021-11-05 13:05 UTC, preludek requested changes

2021-11-05 13:05 UTC, preludek commented on platforms/ucp-mobile/styles.scss
> +#ntv_feed_ad {
We should style everything by classes and not id's. Having both used here and there is making maintenance and potential changes way harder.

2021-11-05 13:05 UTC, preludek commented on src/ad-engine/services/slot-creator.ts
> +		logger(groupName, 'SlotCreator::getAnchorElement() called', slotConfig, result);
There is group name used so `getAnchorElement() called` seems sufficient.

2021-11-05 14:06 UTC, nandy-andy commented on platforms/ucp-mobile/styles.scss
> +#ntv_feed_ad {
I agree. I'd like to address it in the follow-up work as I'm thinking of removing `.gpt-ad` class from Nativo slot that are adding the style I'm removing with this CSS rule. Once `.gpt-ad` is not added to Nativo slots we can remove lines 202-204 from this file 👌

2021-11-05 14:08 UTC, nandy-andy commented on src/ad-services/nativo/nativo.service.ts
> +			utils.logger(logGroup, 'Displaying an dummy test ads');
Trolling is a art 😈

2021-11-06 15:36 UTC, Tomasz-at-Fandom commented on src/ad-services/nativo/index.ts
> +		} else {
If we would reverse the statement, move logger before the HTML block and make an early return then the else would be obsolete  and the HTML block would have one less indentation :)

2021-11-06 15:44 UTC, Tomasz-at-Fandom commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
Could we refactor contents of the following callback? 
There are two`if` statements there that cause deep indentations. We could reverse them and make early returns instead of nesting.

2021-11-06 15:44 UTC, Tomasz-at-Fandom commented on src/ad-services/nativo/index.ts
> +		} else {
If we would reverse the statement, move logger before the HTML block and make an early return then the else would be obsolete and the HTML block would have one less indentation :)

2021-11-06 15:46 UTC, Tomasz-at-Fandom commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
>  		});
Could we refactor contents of this callback? 
There are two`if` statements here that cause deep indentations. We could reverse them and make early returns instead of nesting.

2021-11-06 15:49 UTC, Tomasz-at-Fandom commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +			return;
It's strange that this is getting compiled, we should add `void` as a possible return value.

2021-11-08 10:12 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +			return;
Yep, it's weird but it doesn't break the code as we filter out from the array incorrect elements: https://github.com/Wikia/ad-engine/pull/1163/files#diff-0a44597c77526a4a5c919898980fff7ba9ae62c3fd10c4e11b658d9372ce9bfbL79

2021-11-08 10:49 UTC, Tomasz-at-Fandom approved these changes

2021-11-10 09:49 UTC, dmnsobczak approved these changes

2021-11-15 12:55 UTC, kwfandom approved these changes

2021-11-15 13:02 UTC, preludek approved these changes

2021-11-15 13:03 UTC, merged