ADEN-11341 Cleanup and upgrade Blockthrough integration
Wikia/ad-engine pull request #1169
Opened 2021-11-05 10:41 UTC by dmnsobczak

2021-11-09 20:35 UTC, preludek requested changes

2021-11-09 20:35 UTC, preludek commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +		eventService.once(events.AD_STACK_START, () => {
`eventService` is deprecated, we should go with `communicationService`

2021-11-09 20:35 UTC, preludek commented on platforms/ucp-desktop/templates/configs/outstream-config.ts
> +		inViewportOffsetTop: document.querySelector('.fandom-sticky-header')?.clientHeight || 0,
Team nullish coalescing operator!

2021-11-09 20:35 UTC, preludek commented on platforms/ucp-mobile/templates/configs/outstream-config.ts
> +		inViewportOffsetTop: document.querySelector('.wds-global-navigation')?.clientHeight || 0,
ditto

2021-11-10 08:58 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +		eventService.once(events.AD_STACK_START, () => {
Replaced!

2021-11-10 09:01 UTC, dmnsobczak commented on platforms/ucp-desktop/templates/configs/outstream-config.ts
> +		inViewportOffsetTop: document.querySelector('.fandom-sticky-header')?.clientHeight || 0,
Done!

2021-11-10 09:01 UTC, dmnsobczak commented on platforms/ucp-mobile/templates/configs/outstream-config.ts
> +		inViewportOffsetTop: document.querySelector('.wds-global-navigation')?.clientHeight || 0,
Done!

2021-11-10 13:46 UTC, merged