Aden 11412 - Add Fan Lab message when collapse appears on a page
Wikia/ad-engine pull request #1204
Opened 2021-12-10 14:48 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/ADEN-11412

2021-12-16 11:59 UTC, dmnsobczak requested changes

2021-12-16 11:59 UTC, dmnsobczak commented on .prettierignore
> +platforms/f2/fallback-config.json
Why only 3 `fallback-config.json` are ignored? There are more of them. Can we change it to general regex? I think it's going to be something like that:
`platforms/**/fallback-config.json`

2021-12-16 11:59 UTC, dmnsobczak commented on platforms/shared/index.ts
> +export * from './utils/collapsed-messages/message-box-service';
Those imports are not in alphabetical order :D

2021-12-16 11:59 UTC, dmnsobczak commented on platforms/shared/utils/collapsed-messages/fanlab-box.ts
> +		return `${basicUrl}?utm_source=${utm_source}&utm_medium=${utm_medium}&utm_campaign=${utm_campaign}&utm_content=${utm_content}`;
Instead of this long parameterized URL you can join the simple array - I think it is easier to read:
https://github.com/Wikia/ad-engine/blob/d5e3f096c926e2abc660601364c69f941790b4d3/src/ad-engine/video/vast-url-builder.ts#L110
You can also always add a new util: `arrayToUrlParser()` or something, but that's optional :)

2021-12-16 11:59 UTC, dmnsobczak commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +	getCurrentTypeIndex = (): number => {
I wonder why are you creating a method-variable instead of normal method? Is there any difference in behaviour or speed?

2021-12-16 11:59 UTC, dmnsobczak commented on platforms/shared/utils/collapsed-messages/newsletter-box.ts
> +		super();
💎

2021-12-16 11:59 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +		const messageBoxService = new MessageBoxService();
Note to the future Damian: this will conflict with those changes: https://github.com/Wikia/ad-engine/pull/1200

2021-12-16 11:59 UTC, dmnsobczak commented
One request, some questions and few improvement ideas :)

2021-12-16 12:47 UTC, szymon-nawrocki commented on .prettierignore
> +platforms/f2/fallback-config.json
Great point! I've added only 3 that I had problems with, and I forgot that there is more of them. Thanks

2021-12-16 12:51 UTC, szymon-nawrocki commented on platforms/shared/index.ts
> +export * from './utils/collapsed-messages/message-box-service';
Typescript didn't do his job :D

2021-12-16 13:28 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/fanlab-box.ts
> +		return `${basicUrl}?utm_source=${utm_source}&utm_medium=${utm_medium}&utm_campaign=${utm_campaign}&utm_content=${utm_content}`;
Yeah, you're right, this way it's much better to read 🙇‍♂️

2021-12-16 13:33 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-box.ts
> +		super();
🙇‍♂️

2021-12-16 14:48 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +	getCurrentTypeIndex = (): number => {
No specific reason, I am using arrow functions just out of preference :)

2021-12-17 07:32 UTC, dmnsobczak approved these changes

2021-12-20 07:27 UTC, dmnsobczak commented on .prettierignore
> +platforms/*/fallback-config.json
Alphabetical order xD

2021-12-20 07:27 UTC, dmnsobczak approved these changes

2021-12-20 11:24 UTC, merged