ADEN-11351 Replacing EventEmitter with Post-Quecast
Wikia/ad-engine pull request #1214
Opened 2021-12-28 13:58 UTC by dmnsobczak

2021-12-30 14:23 UTC, preludek requested changes
Did you consider writing some unit tests for new methods in `communication-service`?

2021-12-30 14:23 UTC, preludek commented on src/communication/communication-service.ts
> +			.pipe(ofType(this.getGlobalAction(event)), once ? take(1) : skip(0))
We can do this conditional with `&&` operator and won't need skip

2021-12-30 14:23 UTC, preludek commented on src/communication/communication-service.ts
> +				once ? take(1) : skip(0),
ditto

2021-12-30 14:23 UTC, preludek commented on src/communication/communication-service.ts
> +				filter(
prettier pls

2021-12-30 14:23 UTC, preludek commented on src/ad-products/templates/outstream/porvata-template.ts
> -		eventService.once(events.PAGE_CHANGE_EVENT, () => {
Shouldn't we set a listener here to destroy the player?

2021-12-31 06:51 UTC, dmnsobczak commented on package.json
> -		"eventemitter3": "^3.0.1",
<3

2021-12-31 06:56 UTC, dmnsobczak commented on src/communication/event-types.ts
> +	} as EventOptions,
Yes, but when we mark it as `Dictionary<EventOptions>` or `{ [key: string]: EventOptions }` then IDE won't treat it as a constant and won't give any suggestions if you will type `eventsRepository.` :/ 
I reverted this commit, but we can work on those types in the future.

2021-12-31 06:59 UTC, dmnsobczak commented on src/communication/event-types.ts
> +// tslint:disable-next-line:import-blacklist
Actually I don't know. Maybe it's because this module is imported from npm dependency and that's why it can't be added to the `.tsconfig`? 🤔 @Bielik20 ca you provide some details?

2021-12-31 07:06 UTC, dmnsobczak commented on src/communication/event-types.ts
> +export const eventsRepository = {
Agree, but I consider this PR as a first step. I wanted to make it as simple as possible, because removing EventEmitter and switching fully to Post-Quecast is, as you can see, already a big change. Once we test ad merge it we can improve this mechanism in smaller steps in the future. For now I think `eventRepository` fits it's limit and it definitely will be splitted with the future events or some more sophisticated events control system.

2021-12-31 07:06 UTC, dmnsobczak commented on src/communication/communication-service.ts
> +				filter(
xD

2021-12-31 07:08 UTC, dmnsobczak commented on src/ad-products/templates/outstream/porvata-template.ts
> -		eventService.once(events.PAGE_CHANGE_EVENT, () => {
Destroying a player was used on mobile-wiki legacy where between pageviews there was a single AdEngine instance which had to be reconfigured for a different slots. Now all our apps are not a Single Page Apps and nothing is emitting a Page_Change_Event, so I removed all SPA-related logic, including this line :)

2021-12-31 07:10 UTC, Bielik20 commented on src/communication/event-types.ts
> +// tslint:disable-next-line:import-blacklist
I used it for 2 things:

1. Enforce separation between AdEngine submodules. For example everyone can import from "core" module, but it cannot import from other modules. This is to prevent circular dependencies between modules and set clear boundaries. 
2. (this example) We do not want to use `post-quecast` directly in the code. We have our own wrapper (I don't remember the name... CommunicationService?) and we want to use that instead. So to prevent users from accidentally importing `post-quecast` itself, this rule was introduced.

2021-12-31 07:12 UTC, dmnsobczak commented on src/communication/communication-service.ts
> +			.pipe(ofType(this.getGlobalAction(event)), once ? take(1) : skip(0))
Great tip! Changed!

2021-12-31 07:12 UTC, dmnsobczak commented on src/communication/communication-service.ts
> +				once ? take(1) : skip(0),
Done!

2021-12-31 07:12 UTC, dmnsobczak commented on src/communication/event-types.ts
> +// tslint:disable-next-line:import-blacklist
Got it! Thank you 🙇

2021-12-31 09:47 UTC, preludek approved these changes

2022-01-04 09:07 UTC, mfarul commented on src/communication/communication-service.ts
> +	listenSlotEvent(
listenOnSlotEven

2022-01-04 10:13 UTC, bckatarzyna approved these changes

2022-01-04 10:13 UTC, bckatarzyna commented on src/communication/communication-service.ts
> +	listen(event: EventOptions, callback: (payload?: any) => void, once: boolean = true): void {
Wouldn't `listenOn` be better? Or just `on`?

2022-01-04 10:28 UTC, nandy-andy commented on package.json
> -		"eventemitter3": "^3.0.1",
❤️

2022-01-04 12:20 UTC, nandy-andy commented on platforms/f2/setup/dynamic-slots/f2-dynamic-slots.setup.ts
> +			communicationService.listen(eventsRepository.AD_ENGINE_STACK_START, () => {
What did motivate you to rename the event from `AD_STACK_START` to `AD_ENGINE_STACK_START`?

2022-01-04 12:25 UTC, nandy-andy commented on platforms/shared/setup/ad-engine-runner.setup.ts
> +				utils.logger(logGroup, `Created ad slot ${slot.getSlotName()}`);
I'd change the log message to `'Added ad slot...'` since we don't listen to `AD_SLOT_CREATE` anymore.

2022-01-04 12:31 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/message-box.ts
> +		communicationService.communicate(eventsRepository.AD_ENGINE_MESSAGEBOX_EVENT, {
There is no word like messagebox, so I'd go with: `r/AD_ENGINE_MESSAGEBOX_EVENT/AD_ENGINE_MESSAGE_BOX_EVENT`

2022-01-04 12:35 UTC, nandy-andy commented on platforms/sports/templates/handlers/logo-replacement/logo-replacement-futhead-handler.ts
> -				this.adSlot.emitEvent(events.LOGO_REPLACED);
Don't we want to replace it with some event from the `eventRepository`?

2022-01-04 12:36 UTC, nandy-andy commented on platforms/sports/templates/handlers/logo-replacement/logo-replacement-muthead-handler.ts
> -			this.adSlot.emitEvent(events.LOGO_REPLACED);
Ditto.

2022-01-04 12:50 UTC, nandy-andy commented on platforms/ucp-desktop/setup/context/slots/ucp-desktop-slots-context.setup.ts
> +		communicationService.listen(
This is the same code as in f2 setup: https://github.com/Wikia/ad-engine/pull/1214/files#diff-ccba3e1af310afba5c74877c647d6d03e0b930d8721f2ae3010e041677c739c1R185 What do you think of moving it to shared?

2022-01-04 12:52 UTC, nandy-andy commented on platforms/ucp-mobile/setup/context/slots/ucp-mobile-slots-context.setup.ts
> +		communicationService.listen(
This is the same logic we use in f2 and ucp-desktop. I think it's a good candidate to move it to shared :)

2022-01-04 13:03 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
>  		const slotName = 'interstitial';
We don't need this variable here ;)

2022-01-04 13:07 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +				const disableFloorAdhesionWithStatus = (status: string) => {
What do you think of moving the definition of `disableFloorAdhesionWithStatus()` to the line 119? It should make the lines 120-148 a bit more readable.

2022-01-04 13:18 UTC, nandy-andy commented on spec/ad-engine/models/ad-slot.spec.ts
>  		it('should call eventService.communicator.dispatch with string event', () => {
Yep, consider replacing this and following unit tests with something general for the `communicationService` integration.

2022-01-04 13:24 UTC, nandy-andy commented on spec/ad-engine/ad-slot-fake.ts
> +	emit(event) {
Shouldn't we have a similar method in the real AdSlot, so it's not confusing for anyone reading the unit tests?

2022-01-04 13:39 UTC, nandy-andy commented on src/ad-engine/models/ad-slot.ts
> +		this.viewed = new Promise<void>((resolve) => {
What do you think of defining the promises elsewhere and also adding `catch()` to them with some logging in the browser's console?

2022-01-04 13:41 UTC, nandy-andy commented on src/ad-engine/models/ad-slot.ts
> +		this.emit(AdSlot.TEMPLATES_LOADED, templateNames);
I assume we were copying `templateNames` in order to avoid unexpected mutations. Are you sure it's safe to just pass it as an argument?

2022-01-04 13:42 UTC, nandy-andy commented on spec/ad-engine/ad-slot-fake.ts
> +	emit(event) {
Nevermind, I've just found it: https://github.com/Wikia/ad-engine/pull/1214/files#diff-18f1c6cfa4982c404779ce1c6c6021cf2da725f5f31b9d165393f4ef5d8816f8R596 :D

2022-01-04 13:45 UTC, nandy-andy commented on src/ad-engine/models/ad-slot.ts
> +	emit(event: string | symbol, data: any = {}): void {
Are you sure we want to just pass the `data` object? We used to copy it with `JSON.parse(JSON.stringify())` in the previous `emitPostQueueCast()` implementation 🤔

2022-01-04 14:06 UTC, nandy-andy commented on src/ad-engine/services/template-service.ts
> +				ofType(communicationService.getGlobalAction(eventsRepository.GAM_LOAD_TEMPLATE)),
Nice idea of informing that the template comes from GAM 👌 I'd suggest just changing its place, so it sounds better: `LOAD_GAM_TEMPLATE` or `LOADED_GAM_TEMPLATE`. What do you think?

2022-01-04 14:09 UTC, nandy-andy commented on src/ad-engine/tracking/intervention-tracker.ts
> +				ofType(communicationService.getGlobalAction(eventsRepository.GAM_AD_INTERVENTION)),
The GAM part here seems misleading and unnecessary. It's not GAM that blocks the ad - it's the browser.

2022-01-04 14:27 UTC, nandy-andy commented on src/communication/communication-service.ts
> +	listen(event: EventOptions, callback: (payload?: any) => void, once: boolean = true): void {
I had similar thoughts ;) My thoughts were leaning towards leaving just `on` as when reading the code we read "on something do something" or going with `listenTo` as it's more grammatically correct, I guess.

2022-01-04 14:32 UTC, nandy-andy commented on src/communication/event-types.ts
> +export const eventsRepository: Dictionary<EventOptions> = {
Hooray! One place for all the events definitions ❤️

2022-01-04 14:33 UTC, nandy-andy commented on src/communication/communication-service.ts
> +	communicate(event: EventOptions, payload?: object): void {
Shouldn't we make `dispatch()` private if we want to use `communicate()` now?

2022-01-05 07:58 UTC, dmnsobczak commented on platforms/f2/setup/dynamic-slots/f2-dynamic-slots.setup.ts
> +			communicationService.listen(eventsRepository.AD_ENGINE_STACK_START, () => {
I wanted all internal AdEngine events to start with `AD_ENGINE_...`, because their name also starts like that: `[AdEngine] Something...`. It looks cleaner and this event is only used by us, so we can rename it however we like :D

2022-01-05 08:01 UTC, dmnsobczak commented on platforms/shared/setup/ad-engine-runner.setup.ts
> +				utils.logger(logGroup, `Created ad slot ${slot.getSlotName()}`);
I wanted to limit the amount of non-event related code changes to minimum to limit the testing scope, especially I don't want to change log messages, because somebody might be used to them like that. Creating an ad slot is a synonym of adding if to the slotService or to ad stack.

2022-01-05 08:02 UTC, dmnsobczak commented on platforms/sports/templates/handlers/logo-replacement/logo-replacement-futhead-handler.ts
> -				this.adSlot.emitEvent(events.LOGO_REPLACED);
No, this event was not used anywhere - there's no need to emit events that are not listened anywhere 🤔

2022-01-05 08:02 UTC, dmnsobczak commented on platforms/sports/templates/handlers/logo-replacement/logo-replacement-muthead-handler.ts
> -			this.adSlot.emitEvent(events.LOGO_REPLACED);
Replied above.

2022-01-05 08:06 UTC, dmnsobczak commented on src/ad-engine/services/template-service.ts
> +				ofType(communicationService.getGlobalAction(eventsRepository.GAM_LOAD_TEMPLATE)),
It's not a event about loading a template. It's a event with a data from GAM - it is dispatched by GAM Post-Quecast creative wrapper and it starts with `[GAM] Something...` - that's why `GAM` is on the first place. I want to keep the first word in the event identifier a uppercase event category: `[GAM]` === `GAM_`, `[AdEngine]` === `AD_ENGINE_` etc :)

2022-01-05 08:07 UTC, dmnsobczak commented on src/ad-engine/tracking/intervention-tracker.ts
> +				ofType(communicationService.getGlobalAction(eventsRepository.GAM_AD_INTERVENTION)),
Yes, but the event comes from GAM Post-Quecast instance - that's what `GAM_` states. I would like to keep it that way.

2022-01-05 08:07 UTC, dmnsobczak commented on src/communication/event-types.ts
> +export const eventsRepository: Dictionary<EventOptions> = {
<3

2022-01-05 08:08 UTC, dmnsobczak commented on src/communication/event-types.ts
> +export const eventsRepository: Dictionary<EventOptions> = {
But this file will be splitted in the future when it will grow up :D

2022-01-05 08:10 UTC, dmnsobczak commented on platforms/shared/utils/collapsed-messages/message-box.ts
> +		communicationService.communicate(eventsRepository.AD_ENGINE_MESSAGEBOX_EVENT, {
Done! :grammar: 🙇

2022-01-05 08:30 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/context/slots/ucp-desktop-slots-context.setup.ts
> +		communicationService.listen(
Good idea. Moved to `slotsContext`!

2022-01-05 08:31 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/context/slots/ucp-mobile-slots-context.setup.ts
> +		communicationService.listen(
Done!

2022-01-05 08:38 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
>  		const slotName = 'interstitial';
Removed!

2022-01-05 08:40 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +				const disableFloorAdhesionWithStatus = (status: string) => {
But then this method (or actually "decorator") will be created always, not only when FloorAdhesion gets `success` and there is a real chance to use this code prio logic. We don't need to allocate a memory for that. Small improvement, but still :D I'll keep it in the local scope.

2022-01-05 08:44 UTC, dmnsobczak commented on spec/ad-engine/models/ad-slot.spec.ts
>  		it('should call eventService.communicator.dispatch with string event', () => {
Renamed!
Also: `communicationService` tests are spread across multiple modules since events are really important mechanism. I know that coverage is never enough, but I think it's high enough for now 🤔

2022-01-05 08:44 UTC, dmnsobczak commented on spec/ad-engine/models/ad-slot.spec.ts
>  		it('should call eventService.communicator.dispatch with Symbol event', () => {
Done!

2022-01-05 08:51 UTC, dmnsobczak commented on src/ad-engine/models/ad-slot.ts
> +		this.viewed = new Promise<void>((resolve) => {
Those promises are like a semaphores and they are ultra fragile - I spent a lot of time fixing them after changing event system to make all ads load and track correctly. I would rather create a separate ticket for that. Tomek has a solid ideas and motivation to split AdSlot Mega Class into smaller chunks - let's postpone this idea until then :)
Also nothing is emitting any exception there and an exception would lead to a massive AdEngine crash - this can't be just logged and forget, this part needs to be designed with an idea to omit any exceptions 🤔

2022-01-05 08:53 UTC, dmnsobczak commented on src/ad-engine/models/ad-slot.ts
> +		this.emit(AdSlot.TEMPLATES_LOADED, templateNames);
Good idea. I don't think anybody will edit this event payload which, like you observed, will be a context reference, but a simple `{ ...var }` usage is a solid protection :D

2022-01-05 08:55 UTC, dmnsobczak commented on src/ad-engine/models/ad-slot.ts
> +		this.emit(AdSlot.TEMPLATES_LOADED, templateNames);
Changing mind: fixed in the `emit()` method.

2022-01-05 08:55 UTC, dmnsobczak commented on src/ad-engine/models/ad-slot.ts
> +	emit(event: string | symbol, data: any = {}): void {
Hmm, good thinking 🤔 I will restore a serialization-deserialization!

2022-01-05 09:01 UTC, dmnsobczak commented on src/ad-engine/models/ad-slot.ts
> +	emit(event: string | symbol, data: any = {}): void {
One place where I can't use it is a renderEnded GPT event - there are some important data sent there. I added optional, default parameter.

2022-01-05 09:05 UTC, dmnsobczak commented on src/communication/communication-service.ts
> +	communicate(event: EventOptions, payload?: object): void {
`communicate()` is just a wrapper for a 95% of events, but some of them are more complex, have complicated types and use some edge-case RxJS stream parameters. For those I left `dispatch()` for manual use. We probably will get rid of them in the future: for example types in `tracking-opt-in-wrapper` will be removed after moving Post-Quecast events to TrackingOptIn repository in different ticket :)

2022-01-05 09:15 UTC, dmnsobczak commented on src/communication/communication-service.ts
> +	communicate(event: EventOptions, payload?: object): void {
I changed a method name to `.on()`

2022-01-05 09:16 UTC, dmnsobczak commented on src/communication/communication-service.ts
> +	listen(event: EventOptions, callback: (payload?: any) => void, once: boolean = true): void {
Less letters is better - changed to `.on()` :)

2022-01-05 09:16 UTC, dmnsobczak commented on src/communication/communication-service.ts
> +	listenSlotEvent(
Changed to `.onSlotEvent()`!

2022-01-05 09:17 UTC, dmnsobczak commented on src/communication/event-types.ts
> +	// Google Ad Manager events //
I changed the comment to: `// Events emitted from Google Ad Manager //`, because that's their origin :)

2022-01-05 09:45 UTC, nandy-andy commented on LICENSE
> +      form, that is based emit (or derived from) the Work and for which the
I don't think you need to change the LICENSE :p

2022-01-05 09:45 UTC, nandy-andy commented on README.md
> +* `npm run dev:platforms` - to serve ad-engine platforms code (UCP, Futhead, Muthead) emit port 9000
Nope, `on` was fine here ;)

2022-01-05 09:49 UTC, nandy-andy commented on platforms/shared/setup/ad-engine-runner.setup.ts
> +				utils.logger(logGroup, `Created ad slot ${slot.getSlotName()}`);
But it's not inconsistent and I'm afraid only you treat creating and ad slot and adding an ad slot as synonyms 🙈 I'd say adding is a synonym for injecting ;) So, we need to figure it out first but in the spirit of consistency the log message should be consistent with the event. Otherwise, it's misleading.

2022-01-05 09:50 UTC, nandy-andy commented on src/ad-engine/models/ad-slot.ts
> +		this.viewed = new Promise<void>((resolve) => {
If such massive crash happens with a log message we'd now the place when it happens, won't we? :) Please, create a follow-up ticket and let's groom it this or next week.

2022-01-05 09:52 UTC, nandy-andy commented on src/communication/event-types.ts
> +	// Events emitted from Google Ad Manager //
That's not true. The events are emitted from the iframe created by GPT ;p GAM does not emit anything on our pages ;)

2022-01-05 09:57 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +				const disableFloorAdhesionWithStatus = (status: string) => {
Code readability > premature optimalisation ;)

2022-01-05 10:48 UTC, dmnsobczak commented on README.md
> +* `npm run dev:platforms` - to serve ad-engine platforms code (UCP, Futhead, Muthead) emit port 9000
Arrrghhhhm fixed :<

2022-01-05 10:48 UTC, dmnsobczak commented on LICENSE
> +      form, that is based emit (or derived from) the Work and for which the
Damn, fixed too.

2022-01-05 10:49 UTC, dmnsobczak commented on platforms/shared/setup/ad-engine-runner.setup.ts
> +				utils.logger(logGroup, `Created ad slot ${slot.getSlotName()}`);
Ooook, changed :D

2022-01-05 10:50 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +				const disableFloorAdhesionWithStatus = (status: string) => {
Ok, done :D

2022-01-05 10:54 UTC, dmnsobczak commented on src/communication/event-types.ts
> +	// Events emitted from Google Ad Manager //
How about `Events emitted by Google Ad Manager creatives`? :D It's just a comment :>

2022-01-07 07:10 UTC, nandy-andy approved these changes

2022-01-10 09:50 UTC, nandy-andy approved these changes

2022-01-11 15:37 UTC, merged