ADEN-11413 Add newsletter signup form when collapse appears on page
Wikia/ad-engine pull request #1215
Opened 2021-12-28 15:56 UTC by szymon-nawrocki

### Ticket:
https://fandom.atlassian.net/browse/ADEN-11413

2021-12-29 14:51 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +				this.sendTrackingEvent(adSlot, status_clicked);
I wonder if sending _adengadinfo_ event is necessary here, because these clicks can be probably tracked in _Sailthru_  🤔

2021-12-30 09:45 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +const ACCT_ID = 'c9322e218da57e71a4965ae18fecbefa';
I am also wondering if I can use this _ACCT_ID_, because I took it straight from Newsletter Form implementation on f2, so maybe it can distort their data or something.
@preludek Do you think that I should consult it with someone from f2 first?

2021-12-30 10:07 UTC, preludek requested changes

2021-12-30 10:07 UTC, preludek commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		message.innerHTML = '';
is this necessary?

2021-12-30 10:07 UTC, preludek commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		messageArea.innerHTML = text;
Can we use innerText instead?

2021-12-30 10:08 UTC, preludek commented on src/ad-services/sailthru/index.ts
> +const ACCT_ID = 'c9322e218da57e71a4965ae18fecbefa';
We should ask somebody if we can use that. Also, ACCT_ID may sometimes differ for different platforms.

2021-12-30 12:50 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +				this.sendTrackingEvent(adSlot, status_clicked);
You're right, I don't think we have any access there.
And since we are tracking other message boxes with these events I will leave it as it is

2021-12-30 14:07 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +const ACCT_ID = 'c9322e218da57e71a4965ae18fecbefa';
@mklucsarits
I see that you were implementing Newsletter sign-up in f2 platform (https://github.com/Wikia/f2/pull/2413)

I've got the task of copying this Newsletter sign-up and serve it into collapsed ad slots, which I did.
So far everything seems to be working:
- Sailthru script is correctly added to the site,
- we're getting 201 responses on sign ups with valid email address
But I am not really sure about this _ACCT_ID_ variable.

Could you tell me if I can use the same `ACCT_ID` that is being used in f2 platform?

2021-12-30 15:06 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +	return utils.scriptLoader.loadScript(path, 'text/javascript', true, 'first');
You're right, we don't really need "first" parameter here

2021-12-30 15:15 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		message.innerHTML = '';
not really

2022-01-03 08:21 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +const ACCT_ID = 'c9322e218da57e71a4965ae18fecbefa';
It turns out that when AdEngine is loaded Sailthru is already there, so there is no need to initialize it a second time

2022-01-03 08:33 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +	call(): Promise<void> {
When AdEngine is loaded Sailthru is already there, so there is no need for ICBM flag.

2022-01-03 08:34 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +const ACCT_ID = 'c9322e218da57e71a4965ae18fecbefa';
icVar won't be implemented

2022-01-04 18:10 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +	call(): Promise<void> {
Turns out that Sailthru is being initiated on the backend, and only one of its method will be used in the AdEngine: `Sailthru.integration()`
So I think that flag is not super necessary in this case.

2022-01-04 18:11 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +const ACCT_ID = 'c9322e218da57e71a4965ae18fecbefa';
It was decided that icVar won't be implemented

2022-01-05 08:39 UTC, preludek requested changes

2022-01-05 08:39 UTC, preludek commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		window.Sailthru.integration('userSignUp', {
This should be moved to Sailthru integration. Let's keep all calls to `window.Sailthru` in one place.

2022-01-05 09:33 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +	private types: MessageBoxType[] = ['REGISTER', 'FANLAB', 'NEWSLETTER_FORM', 'NEWSLETTER_LINK'];
Do we need both versions of `MessageBoxType`?

2022-01-05 09:34 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +			source: 'homepage_hero_unit',
That's not true. Let's make the source here `adengine_in_content_ad`

2022-01-05 15:27 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +	private types: MessageBoxType[] = ['REGISTER', 'FANLAB', 'NEWSLETTER_FORM', 'NEWSLETTER_LINK'];
I think that you mistook "type" with "types" :)
The second one is an array of types that I am using to iterate over message boxes

2022-01-07 08:49 UTC, preludek requested changes

2022-01-07 08:49 UTC, preludek commented on platforms/shared/utils/collapsed-messages/message-box.ts
> +	create = () => {
While reviewing this PR I see that you are using arrow functions in classes which is undesirable. For example, arrow functions will be created every time while calling a new MessageBox and will not be shared in a prototype. 

This is already merged, should we make a separate ticket for refactoring and just ignore that here? @nandy-andy @szymon-nawrocki

2022-01-07 09:55 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/message-box.ts
> +	create = () => {
What holds us from changing it within this PR? 🤔

2022-01-07 10:00 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/message-box.ts
> +	create = () => {
Sorry, I didn't realize that using arrow functions inside classes is undesirable. Thanks for pointing this up to me!

@preludek
I think that I can change it in this PR, so I will do that in the next commit

2022-01-07 11:23 UTC, preludek commented on src/ad-services/sailthru/index.ts
> +		const { email, onSuccess, onError } = payload;
You can destructure it directly in line 14.

2022-01-07 11:23 UTC, preludek commented on src/ad-services/sailthru/index.ts
> +export type SailthruSource = 'adengine_in_content_ad';
I wouldn't export that type, and use it in line 14.

2022-01-07 11:23 UTC, preludek commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		const source: SailthruSource = 'adengine_in_content_ad';
I wouldn't specify that type here. If it's typed correctly in Sailthru class, it will throw an error anyway. Same with the line above. You specified what createPayload returns and what should be passed into `sailthru.userSignup`.

2022-01-07 11:59 UTC, preludek approved these changes

2022-01-07 12:31 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		if (!EMAIL_REGEX.test(emailValue)) {
I've added additional validation to avoid submitting form with empty email address

2022-01-10 16:28 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		sailthru.init();
Turns out Sailthru has to be initialized in AdEngine in order to work correctly, so I've added logic for that.
I've added call for `init()` here, because this service will be used only when Newsletter Form will appear in place of every third collapsed ad slot, so very rarely.
@preludek how does it look to you?

2022-01-11 14:31 UTC, nandy-andy commented on @types/sailthru/index.d.ts
> +	lists: { 'Fandom Account Registration - MASTERLIST': number };
I wonder if we shouldn't go with just `object` or `any` here... but the second isn't really welcome 🙈 It just feels weird to see a string as a property ;p

2022-01-11 15:00 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		const onError = (): void => {
I think we should be consistent and resign from this arrow functions (`onSuccess`, `onError`) as well as we did after the previous conversation: https://github.com/Wikia/ad-engine/pull/1215#discussion_r780108758

2022-01-12 10:22 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +	private types: MessageBoxType[] = ['REGISTER', 'FANLAB', 'NEWSLETTER_FORM', 'NEWSLETTER_LINK'];
Should we have `NEWSLETTER_FORM` in types when Sailthru is not enabled? 🤔

2022-01-12 10:25 UTC, nandy-andy commented on src/ad-services/sailthru/index.ts
> +type SailthruSource = 'adengine_in_content_ad';
I think this type is unnecessary. Let's just use `string` in the defintion of `userSignup()`.

2022-01-12 10:26 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +	private types: MessageBoxType[] = ['REGISTER', 'FANLAB', 'NEWSLETTER_FORM', 'NEWSLETTER_LINK'];
Yeah, I think we shouldn't allow a collapse message with the form to appear on pages where Sailthru isn't enabled nor loaded.

2022-01-12 10:28 UTC, nandy-andy commented on src/ad-services/sailthru/index.ts
> +const packageUrl = 'https://ak.sail-horizon.com/spm/spm.v1.min.js';
It's not necessary since we still treat it as an experiment but a nice-to-have is to move `packageUrl` and `ACCT_ID` to our `instant-config` service, so in the future we could change them without releasing code changes.

2022-01-12 13:31 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		const onError = (): void => {
I've used arrow functions here, because with "normal" functions there is a problem with `this`

2022-01-12 15:04 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		const onError = (): void => {
We can figure something out. Use biding to bind to the right context or pass whatever we need as an argument. I'll think about it once I get to my laptop :-)

2022-01-12 17:11 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		sailthru.init();
What happens if Sailthru has been already initialised by silver-surfer and we re-initialise it here? 🤔

2022-01-12 17:20 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +		this.types = sailthru.isEnabled()
Shouldn't we also check if Sailthru loaded?

2022-01-12 17:22 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		}
It seems this logic is the same in [the base class](https://github.com/Wikia/ad-engine/pull/1215/files#diff-f79ceb05f281f21ad82180a59c54153209f87af26b2a3189e6bf007e215f2c08R29-R31), so we could extract it to a helper method that we'd just reuse here.

2022-01-12 17:48 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		const wrapper = this.createBoxWrapper();
If I'm correct this method differs from the base class `create()` method with two things: (1) Sailthru initialisation and (2) adding different things to the wrapper and then to the placeholder. Consider simplifying the base class method to a simple one that receives things to add to the placeholder, adds them and sends the tracking pixel. Then in the `NewsletterFormBox`'s version you'll just additionally init Sailthru and add different elements 🤔

2022-01-12 18:10 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		sailthru.init();
It's also a promise that's returned from `init()`, so I think we should do everything that's below in the `then()` callback 🤔

2022-01-12 18:16 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +		this.types = sailthru.isEnabled()
I think we don't need to since if it's enabled we'll call `NewsletterFormBox::create()` that will call `Sailthru::init()` that checks if it's loaded and if not it's loading the script.

2022-01-12 18:18 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/message-box-service.ts
> +	init(): void {
Do we need this method? I can't find its usage anywhere else and I think setting `this.types` fits perfectly in the `constructor()` 🤔

2022-01-13 12:44 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		form.innerHTML = `
I created it this way because it was easier for me, but I did not know that it can cause potential security issues

2022-01-13 13:10 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		sailthru.init();
Sailthru will be initialized from scratch, only if it is not already loaded:
https://github.com/Wikia/ad-engine/blob/93541d646bf79f6f204b5667bd254aed1da7fdd4/src/ad-services/sailthru/index.ts#L29

2022-01-13 13:13 UTC, szymon-nawrocki commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		sailthru.init();
I've made a change to the NewsletterForm, and I removed completely `create()` method, instead of this method, I created `getElementsToAppend()` where we can specify what elements should be added to _Message Box wrapper_.

I was thinking where will be the best place to put `sailthru.init()` method, so I put it to the constructor, @nandy-andy do you think it is a good place for it?

2022-01-13 13:29 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		return elements;
I think in this case, where there is no additional logic you can simplify the method to:
```js
getElementsToAppend(): HTMLElement[] {
  return [this.createForm(), this.createFormMessage()]
}
```

2022-01-13 13:31 UTC, nandy-andy commented on platforms/shared/utils/collapsed-messages/newsletter-form-box.ts
> +		const submitBtn: HTMLButtonElement = document.querySelector('.newsletter-submit');
You can create a small method `disableSubmitButton()`, move there this line and the next line and reuse the new method by replacing lines 76, 77 above :)

2022-01-13 14:52 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +					utils.logger(logGroup, 'ready');
Here return `Promise.resolve()`

2022-01-13 14:53 UTC, szymon-nawrocki commented on src/ad-services/sailthru/index.ts
> +					throw new Error('Error occurred while loading Sailthru.');
And here `Promise.reject()` instead of error?

@nandy-andy  what do you think?

2022-01-13 14:56 UTC, nandy-andy commented on src/ad-services/sailthru/index.ts
> +		}
@szymon-nawrocki and here one more `Promise.resolved()` if Sailthru is enabled and loaded 🤔

2022-01-13 17:08 UTC, nandy-andy approved these changes

2022-01-17 07:52 UTC, dmnsobczak approved these changes

2022-01-17 07:53 UTC, merged