ADEN-11477 Replacing clip() with dynamic resize
Wikia/ad-engine pull request #1217
Opened 2021-12-30 12:05 UTC by dmnsobczak

2022-01-03 08:37 UTC, preludek requested changes

2022-01-03 08:37 UTC, preludek commented on platforms/shared/templates/helpers/uap-dom-manager.ts
> +			.setProperty('clipPath', `inset(0 0 ${this.reader.getSlotHeightClipping()}px)`);
Did you check inset on `caniuse`, cause it looks worse than clip 🙈 

https://caniuse.com/mdn-css_properties_inset

2022-01-03 08:37 UTC, preludek commented on platforms/ucp-mobile/templates/bfaa-3-template.ts
> -}
That had to be so satisfying :D

2022-01-03 08:37 UTC, preludek commented on platforms/shared/templates/helpers/uap-dom-reader.ts
> +	getSlotHeightClipping(): number {
Nit-pick: This is not following the name convention and the description in line 71. What do you think of changing `Progress` in line 71 to `Clipping`?

2022-01-03 08:37 UTC, preludek commented on platforms/shared/templates/handlers/bfaa-new/bfaa-new-bootstrap-handler.ts
> -}
💎

2022-01-04 06:28 UTC, dmnsobczak commented on platforms/ucp-mobile/templates/bfaa-3-template.ts
> -}
Yeees, it was <3

2022-01-04 06:29 UTC, dmnsobczak commented on platforms/shared/templates/handlers/bfaa-new/bfaa-new-bootstrap-handler.ts
> -}
🙇

2022-01-04 06:35 UTC, dmnsobczak commented on platforms/shared/templates/helpers/uap-dom-manager.ts
> +			.setProperty('clipPath', `inset(0 0 ${this.reader.getSlotHeightClipping()}px)`);
Based on our Supported Browsers page, we're good to go. Fandom requires updated browsers and IE is no longer supported:
https://community.fandom.com/wiki/Help:Supported_browsers
Additionally: `inset` CSS property is widely used in Unified Platforms CSS files, mostly for `box-shadow` property. That's why I decided that we don't need to worry about that :D

2022-01-04 06:38 UTC, dmnsobczak commented on platforms/shared/templates/helpers/uap-dom-reader.ts
> +	getSlotHeightClipping(): number {
Git is making a mess in the history: I removed `calculateProgress()` completely, because this method was unused and I added completely different `getSlotHeightClipping()` which follows `getSlotHeightImpact()` or `getSlotHeightResolved()` convention 🤔

2022-01-04 07:33 UTC, preludek approved these changes

2022-01-04 14:38 UTC, merged