ADEN-11492 | Identify sequential UAP ad
Wikia/ad-engine pull request #1231
Opened 2022-01-19 15:49 UTC by Tomasz-at-Fandom

2022-01-19 16:06 UTC, Tomasz-at-Fandom commented on platforms/shared/sequential-messaging/data-structures/sequential-messaging-cookie.ts
> +}
I know this looks the same as `IcSequentialMessaging` but it will change in the next step so no point in merging them now.

2022-01-19 18:15 UTC, mfarul requested changes

2022-01-19 18:15 UTC, mfarul commented on platforms/shared/sequential-messaging/domain/sequence-handler.ts
> +export class SequenceHandler {
Not sure what we handle here? is this supposed to store the sequence number per user ? 
If so the handleMethod should just detect if slot is filled with sequence Ad and call an internal method  storeSequenceNumberForUser. As now this is our product: 
1) detect if we are getting sequenced Ad (line item config)
2) store this info per user (in cookie)
3) use this info for targeting Ad (this will be implemented further)

If this is the exact flow we should see it in method names and all being called from main handle method.

2022-01-20 09:01 UTC, Tomasz-at-Fandom commented on platforms/shared/sequential-messaging/domain/data-structures/sequential-messaging-cookie.ts
> +export interface SequentialMessagingCookie {
Well this goes in to the cookie and IcSequentialMessaging come from ICBM (or maybe GAM in the future). I expect trouble if I'll represent two different "external" data stores with one data structure. E.g. in the next step I expect we will probably store additionally information about the ad slot that this came in, that we will not be defining in the configuration.

2022-01-20 09:06 UTC, Tomasz-at-Fandom commented on platforms/shared/sequential-messaging/domain/data-structures/ic-sequential-messaging.ts
> +export interface IcSequentialMessaging {
Well the jury is still out on this one, I expect that this will change as we progress through the development of this feature, so for now I just labeled it with the icbm var name that this data comes from.

2022-01-20 09:30 UTC, preludek commented on platforms/ucp-desktop/ucp-desktop-platform.ts
> +			SequentialMessagingSetup,
Is this the right place for it? I feel like those SequentialMessaging is more like an ad-product 🤔

2022-01-20 09:30 UTC, preludek commented on platforms/shared/sequential-messaging/domain/sequence-handler.ts
> +		if (typeof icSequentialMessaging !== 'object') {
I have some doubts about that line. If we plug in `null` this will go through and break on line 34.

2022-01-20 09:30 UTC, preludek commented on platforms/shared/sequential-messaging/domain/factories/detector-factory.ts
> +	constructor(private icSequentialMessaging: IcSequentialMessaging) {}
Because we are naming icVars this way the naming starting with ic feels really odd.

2022-01-20 09:52 UTC, Tomasz-at-Fandom commented on platforms/shared/sequential-messaging/domain/factories/detector-factory.ts
> +@Injectable()
Oh good catch, this is a leftover from previous implementation where I was injecting ICBM here. That's why I created a separate Factory class in the fist place but yea this could go back to the Sequence Detector all together.

2022-01-20 10:25 UTC, Tomasz-at-Fandom commented on platforms/shared/sequential-messaging/domain/interfaces/cookie-jar-interface.ts
> +export interface CookieJarInterface {
Well I guess it's possible to use something else then cookies so I'll change the name of the interface and will make an adapter to hide the cookie `name` required by `js-cookie` package. I should also rename the `SequentialMessagingCookie` to something like `UserSequentialMessageState`

2022-01-20 10:28 UTC, Tomasz-at-Fandom commented on platforms/shared/sequential-messaging/domain/sequence-handler.ts
> +		private instantConfig: InstantConfigServiceInterface,
That can get tricky down the line if every feature would establish its own interface that the ICBM class would have to abide by to meet its requirements. It would be easier to discuss this on a call.

2022-01-20 16:24 UTC, Tomasz-at-Fandom commented on platforms/ucp-desktop/ucp-desktop-platform.ts
> +			SequentialMessagingSetup,
It's the best place I could find for a one point per platform plug in.

2022-01-20 16:25 UTC, Tomasz-at-Fandom commented on platforms/shared/sequential-messaging/domain/factories/detector-factory.ts
> +	constructor(private icSequentialMessaging: IcSequentialMessaging) {}
This was refactored now, please see the new implementation.

2022-01-21 08:47 UTC, preludek approved these changes

2022-01-21 08:47 UTC, preludek commented on platforms/shared/sequential-messaging/domain/data-structures/user-sequential-message-state.ts
> +	[sequentialAdIs: number]: { length: number };
typo :D

2022-01-21 08:54 UTC, Tomasz-at-Fandom commented on platforms/shared/sequential-messaging/domain/data-structures/user-sequential-message-state.ts
> +	[sequentialAdIs: number]: { length: number };
Good catch, like sniper 🧐

2022-01-25 11:37 UTC, merged