ADEN-11578 Change Nativo from a service to a proper ad provider
Wikia/ad-engine pull request #1268
Opened 2022-02-11 16:09 UTC by nandy-andy

2022-02-11 16:11 UTC, nandy-andy commented on platforms/shared/modes/start-ad-engine.ts
> +		if (context.get('services.nativo.enabled') && context.get('wiki.opts.enableNativeAds')) {
We could have GPT loader and Nativo loader that would keep additional logic and load the assets when some conditions are met.

2022-02-11 16:16 UTC, nandy-andy commented on src/ad-engine/ad-engine.ts
> +			if (provider.fillIn(adSlot)) {
Right now only Nativo returns `true` other providers (GPT and Prebidium) are more complicated and I'm not sure but probably we'll need to resign from this idea. We could replace it with having all the providers to respond with something and we pick at this point what gets rendered ;)

2022-02-17 14:59 UTC, Tomasz-at-Fandom commented
I could not make up my mind where to start this review in code, so I'm starting with this general comment.
Two things that worry me about the direction of these changes are:
1. We remove tests of the old implementation without replacing them with tests for the new one.
2. The old implementation encapsulated Nativo better than this one, which is spread wider across the codebase.
I'll follow this up with comments to specific points in code, so please keep in mind when reading them that what I'm trying to do is to find a way to better encapsulate this provider and his features and make the code easier to test at a granular level.

2022-02-17 15:06 UTC, Tomasz-at-Fandom commented on platforms/shared/modes/start-ad-engine.ts
> +		if (context.get('services.nativo.enabled') && context.get('wiki.opts.enableNativeAds')) {
So how about moving all this newly added code to a separate class within the Nativo Module to reduce Nativos spread across the existing codebase?

2022-02-17 16:04 UTC, Tomasz-at-Fandom commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-slots-definition-repository.ts
> +	}
This is something that could live in the Nativo Module

2022-02-17 16:08 UTC, Tomasz-at-Fandom commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-slots-definition-repository.ts
>  	}
Actually all of this could live in the Nativo Module, let's not bloat this "repository" with  every provider we want to add.

2022-02-17 16:10 UTC, Tomasz-at-Fandom commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
>  	}
Like in the desktop version, perhaps we could move this to a Nativo Module.

2022-02-17 16:16 UTC, Tomasz-at-Fandom commented on src/ad-engine/providers/nativo-provider.ts
> +		window.ntv.cmd = window.ntv.cmd || [];
If we inject this through constructors parameters instead of fetching from window we could easily test this class and not even bother with instantiating it in case `window.ntv` is not even set

2022-02-28 12:05 UTC, dmnsobczak commented on @types/window/index.d.ts
> +	ntv?: NativoSdk;
It's more like an API than SDK 🤔

2022-02-28 12:22 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +	private createProvider(providerName: string) {
This seems over-splitted, but it's fine :D

2022-02-28 12:23 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		const providersChain = context.get(`slots.${adSlot.getSlotName()}.providers`);
This context key is used twice - we could pass providers like an argument 🤔

2022-02-28 12:24 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		const providersChain = context.get(`slots.${adSlot.getSlotName()}.providers`);
Also: `... || []`?

2022-02-28 12:29 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +
Unneeded line break :>

2022-02-28 12:31 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +			if (provider.fillIn(adSlot)) {
I was surprised by the `chain` logic while we do not have any use case where actual chain is used. My proposal is to resign from `chain` for now and re-add it in the future if needed.

2022-02-28 14:02 UTC, dmnsobczak commented on platforms/shared/modes/start-ad-engine.ts
> +		const nativo = new Nativo(context);
This makes `Nativo` class as important as `AdEngine` class. Maybe let's move it to `setupProviders()` inside AdEngine class? It would be executed on `AdEngine::init` and logically it will be in the better place. Also `Nativo` class constructor could be executed only once 🤔

2022-02-28 14:06 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +	constructor(protected domListener: DomListener, protected nativo: Nativo) {
`, protected nativo: Nativo` is redundant

2022-02-28 14:07 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-nativo-slots-definition-repository.ts
> +	constructor(protected nativo: Nativo, protected domListener: DomListener) {
`protected nativo: Nativo, ` can be removed

2022-02-28 14:08 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +		this.nativo = new Nativo(context);
Actually: can we make `Nativo` class instance Injectable? 🤔

2022-02-28 14:09 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +		const slotName = Nativo.INCONTENT_AD_SLOT_NAME;
Assigning a static variable to a variable - why don't we use a static variable directly? :D

2022-02-28 14:10 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +				const scrollThreshold = context.get('events.pushOnScroll.nativoThreshold') || 200;
This variable was already defaulted as `200` multiple times, ` || 200;` is reduntant

2022-02-28 14:12 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +		const slotName = Nativo.FEED_AD_SLOT_NAME;
`slotName` is used only once :trollface:

2022-02-28 14:16 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-nativo-slots-definition-repository.ts
> +				const scrollThreshold = context.get('events.pushOnScroll.nativoThreshold') || 200;
Some lines here as well as definition of `onAdEngineUapLoaded()` method are duplicated - some refactor of a refactor? Code can be always stored as ucp-shared util inside `platforms/shared/` directory.

2022-02-28 14:19 UTC, dmnsobczak commented on src/ad-engine/providers/nativo/nativo-provider.ts
> +	getQueue(): Array<Dictionary> {
`cmd?: any[];` - can you choose the same type? It can be just `Dictionary[]` 🤔

2022-02-28 14:22 UTC, dmnsobczak commented on src/ad-engine/providers/nativo/nativo.ts
> +		logger(logGroup, 'Is Nativo enabled?', isEnabled);
This log with unchanged message will be console.logged multiple times 🤔

2022-02-28 14:23 UTC, dmnsobczak commented on src/ad-engine/providers/nativo/nativo.ts
> +		const NATIVO_LIBRARY_URL = '//s.ntv.io/serve/load.js';
Usually we make variables like that a variable outside the class, not a local variable.

2022-02-28 14:26 UTC, dmnsobczak commented on src/ad-engine/providers/nativo/nativo.ts
> +		}
```suggestion
		if (action.isLoaded || action.adProduct === 'ruap') {
			logger(logGroup, "UAP or UAP:Roadblock on page - don't display Nativo");
			return;
		}
			
		this.context.push('state.adStack', { id: slotName });
```

2022-02-28 16:33 UTC, nandy-andy commented on @types/window/index.d.ts
> +	ntv?: NativoSdk;
What's the difference? ;)

2022-02-28 16:40 UTC, nandy-andy commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +	constructor(protected domListener: DomListener, protected nativo: Nativo) {
You mean redundant because of the line below? 🤔

2022-02-28 16:42 UTC, nandy-andy commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +		const slotName = Nativo.INCONTENT_AD_SLOT_NAME;
Damian once told me he likes the pattern of having `slotName` defined at the beginning of the definition repository methods ;)

2022-02-28 16:43 UTC, nandy-andy commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +				const scrollThreshold = context.get('events.pushOnScroll.nativoThreshold') || 200;
But just-in-case... ;)

2022-02-28 16:47 UTC, nandy-andy commented on src/ad-engine/ad-engine.ts
> +	private createProvider(providerName: string) {
It's used now in two places instead of one. However, if we want to get rid off of the chain we can make it as it used to be 👌 ;)

2022-02-28 16:48 UTC, nandy-andy commented on src/ad-engine/providers/nativo/nativo.ts
> +		logger(logGroup, 'Is Nativo enabled?', isEnabled);
Yep.

2022-03-01 06:13 UTC, dmnsobczak commented on @types/window/index.d.ts
> +	ntv?: NativoSdk;
I always understand SDK like a set of tools that helps to create an application, but are not present in the finished build, while the API allows two apps to communicate: AdEngine and Nativo library in this example 🤔

2022-03-01 06:18 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +	constructor(protected domListener: DomListener, protected nativo: Nativo) {
Yes, `protected nativo` creates an class object and usually it should be assigned to a DI injected value. Line below can also create a class field with `private` access level and while nothing is inheriting from this class, then `protected` is actually a `private` 🤔

2022-03-01 06:23 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +		this.nativo = new Nativo(context);
Dependency Injection is available only in `platforms/` so `Nativo` class should be moved here, but that's not strictly required. I was thinking about binding it to container via `DiProcess` interface. You can use InstantConfig as an example :D 
https://github.com/Wikia/ad-engine/blob/3b90faf7958f9f09885e17f7c88c1ff8d92ff4bb/platforms/shared/utils/instant-config-setup.ts#L23

2022-03-01 06:24 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-nativo-slots-definition-repository.ts
> +		const slotName = Nativo.INCONTENT_AD_SLOT_NAME;
Yes, but then he admitted that reviewing person was right and he abandoned that idea :trollface:

2022-03-01 10:08 UTC, nandy-andy commented on @types/window/index.d.ts
> +	ntv?: NativoSdk;
Sure, we can go this way :) My understanding was that whatever comes from Nativo's lib is a set of tools - there is a queue, an API to request something from the ad server and an API with events. But I have no strong feelings about SDK vs. API. There are two votes for changing it to API, so let's do it :)

2022-03-02 12:32 UTC, preludek requested changes

2022-03-02 12:32 UTC, preludek commented on src/ad-engine/providers/nativo/lazy-loader.ts
> +		const scrollPosition =
nitpick - you are declaring a type for 2 out of 3 consts :D since those are all primitive types and typescript is inferring them, I'd just skip them for all 3.

2022-03-02 12:32 UTC, preludek commented on platforms/shared/dynamic-slots/nativo-slots-definition-repository.ts
> +import { SlotSetupDefinition } from './../utils/insert-slots';
nitpick - `'../utils/insert-slots'`

2022-03-02 12:32 UTC, preludek commented on spec/ad-engine/providers/nativo/nativo.spec.ts
> +			const contextMock = new Context();
I think this will leak between units. We need to clear that after this spec.

2022-03-02 12:32 UTC, preludek commented on spec/ad-engine/providers/nativo/nativo.spec.ts
> +			context = new Context();
ditto

2022-03-02 12:32 UTC, preludek commented on src/ad-engine/ad-engine.ts
> +			case 'gpt':
since `gpt` is default this line seems redundant 🤔

2022-03-02 12:32 UTC, preludek commented on src/ad-engine/providers/nativo/nativo.ts
> +	sendNativoLoadStatus(status: string, event?: any): void {
This method can be private

2022-03-02 12:32 UTC, preludek commented on src/ad-engine/providers/nativo/nativo.ts
> +	sendNativoLoadStatus(status: string, event?: any): void {
And we never pass the second argument so it seems we can 🔪  it

2022-03-02 12:32 UTC, preludek commented on src/ad-engine/providers/nativo/nativo.ts
> +	private handleNtvNativeEvent(e, slotName: string, adStatus: string) {
e has any type here, we can be more specific

2022-03-02 12:32 UTC, preludek commented on spec/ad-engine/providers/nativo/nativo-provider.spec.ts
> +	beforeEach(() => {
I think this will also leak if we didn't reset it in afterEach.

2022-03-02 14:39 UTC, nandy-andy commented on spec/ad-engine/providers/nativo/nativo.spec.ts
> +			context = new Context();
we only spy here and then we reset the spy, so I think it's safe 🤔

2022-03-02 15:11 UTC, nandy-andy commented on spec/ad-engine/providers/nativo/nativo.spec.ts
> +			context = new Context();
@Tomasz-at-Fandom I think that reseting the spy's history in `afterEach()` prevents the case you described from happening 🤔 Let me know if my understanding is incorrect 😊

2022-03-03 08:32 UTC, szymon-nawrocki commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +			}),
Can't we set the config in `getNativoFeedAdConfig` function to be consistent with another slots?

2022-03-03 08:41 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +			}),
Not really or more: not right now. Not in this scope change. We need to pass this configuration in order to create slot in DOM for FandomMobile.

2022-03-03 09:36 UTC, szymon-nawrocki approved these changes

2022-03-03 09:40 UTC, Tomasz-at-Fandom commented on spec/ad-engine/providers/nativo/nativo.spec.ts
> +			context = new Context();
Oh I did not notice the after each, sorry!

2022-03-03 09:43 UTC, dmnsobczak approved these changes

2022-03-03 14:14 UTC, nandy-andy commented on src/ad-engine/providers/nativo/nativo.ts
> +			this.replaceAndShowSponsoredFanAd();
Follow-up: https://fandom.atlassian.net/browse/ADEN-11626

2022-03-03 19:39 UTC, preludek approved these changes

2022-03-03 19:39 UTC, preludek commented on spec/ad-engine/providers/nativo/nativo.spec.ts
> +				adProduct: 'nothing important',
🙈

2022-03-04 07:02 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +				slotName: Nativo.FEED_AD_SLOT_NAME,
I would rather move it to the Slot Definition Repository file - placing it here looks weird 🤔 Alternatively it can be stored in the context or something.

2022-03-04 07:05 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		const nativo = new Nativo(context);
Can we move it to `createProvider()` method below `case 'nativo':` line or after the switch? Initializing Nativo has nothing to do with setting up providers 🤔

2022-03-04 07:05 UTC, dmnsobczak approved these changes

2022-03-04 07:54 UTC, nandy-andy commented on spec/ad-engine/providers/nativo/nativo.spec.ts
> +				adProduct: 'nothing important',
It's a test. What's the matter?

2022-03-04 07:56 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +				slotName: Nativo.FEED_AD_SLOT_NAME,
There is a ticket for dealing with it: https://fandom.atlassian.net/browse/ADEN-11626 a bit out of scope for this PR but good catch 👍

2022-03-04 07:59 UTC, nandy-andy commented on src/ad-engine/ad-engine.ts
> +		const nativo = new Nativo(context);
Right. In the future it's something that the ProvidersManager/AdLayoutBuilder/LIS will take care of 👌

2022-03-04 08:18 UTC, nandy-andy commented on src/ad-engine/ad-engine.ts
> +		const nativo = new Nativo(context);
Darn, I can't move it because moving it `createProvider()` means we'll load the Nativo API every time we create a provider for a slot. Maybe making `isEnabled()` public static will be a solution - no need to create an instance of Nativo class 🤔

2022-03-04 08:21 UTC, nandy-andy commented on src/ad-engine/ad-engine.ts
> +		const nativo = new Nativo(context);
Ugh, it's complicated. We'll change it while working on AdLayoutBuilder hopefully 🤞

2022-03-04 10:40 UTC, merged