ADEN-11612 ads in quizes
Wikia/ad-engine pull request #1305
Opened 2022-03-16 09:21 UTC by preludek

2022-03-17 07:19 UTC, dmnsobczak commented on platforms/shared/dynamic-slots/quiz-slots-definition-repository.ts
> +export class QuizSlotsDefinitionRepository {
Please add it to `index.ts` to export outside of the module

2022-03-17 07:19 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +import { QuizSlotsDefinitionRepository } from '../../../shared/dynamic-slots/quiz-slots-definition-repository';
Import from `@platforms/shared`

2022-03-17 07:20 UTC, dmnsobczak commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +import { QuizSlotsDefinitionRepository } from '../../../shared/dynamic-slots/quiz-slots-definition-repository';
ditto

2022-03-17 07:21 UTC, dmnsobczak commented on src/ad-engine/providers/gpt-provider.ts
> +	window.googletag.pubads().updateCorrelator();
Consult with @sseyda if updating correlator between for example ICB1 and ICB2 impression is fine 🤔

2022-03-17 07:23 UTC, dmnsobczak requested changes
Just one `import` issue ;)

2022-03-17 08:40 UTC, preludek commented on platforms/shared/dynamic-slots/quiz-slots-definition-repository.ts
> +export class QuizSlotsDefinitionRepository {
done

2022-03-17 08:40 UTC, preludek commented on platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +import { QuizSlotsDefinitionRepository } from '../../../shared/dynamic-slots/quiz-slots-definition-repository';
done

2022-03-17 08:40 UTC, preludek commented on src/ad-engine/providers/gpt-provider.ts
> +	window.googletag.pubads().updateCorrelator();
I'll just remove it, it feels like an overkill and potential problem maker 🤷‍♂️

2022-03-17 08:40 UTC, preludek commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +import { QuizSlotsDefinitionRepository } from '../../../shared/dynamic-slots/quiz-slots-definition-repository';
done

2022-03-17 09:47 UTC, dmnsobczak approved these changes

2022-03-21 08:17 UTC, szymon-nawrocki commented on platforms/ucp-desktop/setup/context/slots/ucp-desktop-slots-context.setup.ts
> +				slotNameSuffix: '',
I think variables `slotNameSuffix` can be removed, because they are currently initialized at AdSlot level https://github.com/Wikia/ad-engine/blob/8653a591037509635259ab321a88b76d948f1693/src/ad-engine/models/ad-slot.ts#L151

2022-03-21 08:50 UTC, szymon-nawrocki commented on platforms/ucp-desktop/setup/context/slots/ucp-desktop-slots-context.setup.ts
> +				slotNameSuffix: '',
Since @preludek is on vacation, I removed it and committed a changes

2022-03-21 08:50 UTC, szymon-nawrocki approved these changes

2022-03-23 14:05 UTC, merged