ADEN-11657 Log in Kibana Audigent segments
Wikia/ad-engine pull request #1309
Opened 2022-03-22 13:12 UTC by nandy-andy

2022-03-23 09:01 UTC, dmnsobczak requested changes

2022-03-23 09:01 UTC, dmnsobczak commented on src/ad-services/audigent/index.ts
> +		if (Math.random() * 100 <= sampling && typeof segments !== 'string') {
If sampling is disabled then `sampling` will be 0 and `Math.random()` can return 0: 
`(inclusive of 0, but not 1)`
So the feature cannot be disabled :(

2022-03-23 09:14 UTC, nandy-andy commented on spec/ad-services/audigent/audigent.spec.ts
> +describe.only('Audigent', () => {
Goddamnit! Thanks! 😊

2022-03-23 09:29 UTC, dmnsobczak approved these changes

2022-03-29 08:20 UTC, jakubbanas approved these changes

2022-03-30 12:58 UTC, merged