DPAD-119 :: Add communication for ad block detected
Wikia/ad-engine pull request #1313
Opened 2022-03-23 17:12 UTC by vforge

Will be used to collapse/remove slots added in https://github.com/Wikia/silver-surfer/pull/904

2022-03-23 17:28 UTC, szymon-nawrocki commented on platforms/shared/services/wad-runner.ts
> +const adClickedAction = globalAction('[AdEngine] Ad block detected');
I would change a variable name to `adblockDetectedAction`

2022-03-23 17:29 UTC, szymon-nawrocki commented on platforms/shared/services/wad-runner.ts
> +			communicationService.dispatch(adClickedAction());
This should work perfectly for the quizes 👍

2022-03-23 17:30 UTC, vforge commented on src/communication/event-types.ts
> +	AD_ENGINE_AD_BLOCK_DETECTED: {
👍

2022-03-23 17:31 UTC, vforge commented on src/communication/event-types.ts
> +	AD_ENGINE_AD_BLOCK_DETECTED: {
Removed in https://github.com/Wikia/ad-engine/pull/1313/commits/5e004193d2aea748d2d272055c54c32694e0631f

2022-03-23 17:32 UTC, szymon-nawrocki approved these changes

2022-03-24 05:44 UTC, dmnsobczak commented on platforms/shared/services/wad-runner.ts
> +			communicationService.dispatch(adblockDetectedAction());
We are already emitting Post-Quecast event with AdBlock detection status:
https://github.com/Wikia/ad-engine/blob/dev/src/ad-engine/services/bab-detection.ts#L107
Event type:
https://github.com/Wikia/ad-engine/blob/dev/src/communication/event-types.ts#L77
Instead of `AdBlock` we are using `BAB` which is an acronym for `BlockAdBlock` - the library we are using for AdBlock detection :)

2022-03-24 05:45 UTC, dmnsobczak requested changes
Let me know if existing event is available for you. If yes, then this change is redundant I guess 🤔

2022-04-12 07:20 UTC, closed without merging