ADEN-11676 Disable ad slots for engagement test
Wikia/ad-engine pull request #1340
Opened 2022-04-06 11:08 UTC by jakubbanas

2022-04-11 14:54 UTC, nandy-andy commented on platforms/shared/setup/base-context.setup.ts
> +		context.set('icDisabledSlots', this.instantConfig.get('icDisabledSlots'));
Do we still need the variable?

2022-04-11 14:56 UTC, nandy-andy commented on platforms/f2/setup/dynamic-slots/f2-dynamic-slots.setup.ts
> -		if (!topLeaderboardDefinition) {
Isn't removing this piece of code breaking something on f2? 🤔

2022-04-11 14:59 UTC, nandy-andy commented on platforms/shared/setup/noads-experiment.setup.ts
> +				this.cookieAdapter.setItem('_ae_intrsttl_imp', '1');
Once a user gets to this group and we set the cookie she'll become lucky since next pageviews for her will be without the Celtra interstitial too, won't they? ;) However, I don't have any good idea of "fixing" it :/

2022-04-11 15:04 UTC, nandy-andy commented on platforms/shared/setup/noads-experiment.setup.ts
> +	return config?.unitName;
What do you think of removing `?`, so it'll break loudly and we'll catch cases when there will be a bug in the config.

2022-04-11 15:05 UTC, nandy-andy commented on platforms/shared/setup/noads-experiment.setup.ts
> +		this.disableUnit(unitName);
If we make sure `getUnitNameToDisable()` always returns a string with the unit we could go with a one-liner here:
```js
this.disableUnit(getUnitNameToDisable(configs, userBeacon));
```

2022-04-12 06:40 UTC, jakubbanas commented on platforms/f2/setup/dynamic-slots/f2-dynamic-slots.setup.ts
> -		if (!topLeaderboardDefinition) {
Right, it was supposed to stay here! 🙈

2022-04-12 06:41 UTC, jakubbanas commented on platforms/shared/setup/base-context.setup.ts
> +		context.set('icDisabledSlots', this.instantConfig.get('icDisabledSlots'));
Right, it's the next thing I forgot to remove from the POC branch.

2022-04-12 08:22 UTC, jakubbanas commented on platforms/shared/setup/noads-experiment.setup.ts
> +				this.cookieAdapter.setItem('_ae_intrsttl_imp', '1');
I believe it would not be a problem. The idea behind this "beacon targeting" is that the experiment lives as long as the beacon itself. Beacon stays the same between page views, so the only way to jump off the experiment is to clear cookies, which will also remove the  Celtra blocker.

2022-04-12 08:33 UTC, jakubbanas commented on platforms/shared/setup/noads-experiment.setup.ts
> +	return config?.unitName;
The `find` method returns `undefined` when it finds nothing, which means the beacon doesn't match any experiment. This is not a bug in the config, it might happen that the beacon should not participate in any experiment.
I'll add a test for that case.

2022-04-12 09:32 UTC, jakubbanas commented on platforms/shared/setup/noads-experiment.setup.ts
> +	const config = configs.find((conf) => userBeacon.match(conf.beaconRegex));
I added a default value for the beacon, so when it's undefined it's falling back to an empty string.

2022-04-12 10:02 UTC, mfarul commented on platforms/shared/setup/noads-experiment.setup.ts
> +export class NoAdsExperimentSetup implements DiProcess {
I think this could go beyond experiment - if this could be a UnitDisabler with a provided function getUnitNameToDisable we could use it in an experiment environment and in a regular ICBM environment when needed. This is not needed now, just for future reference.

2022-04-12 11:17 UTC, dmnsobczak requested changes
New `slot.disabled` logic will probably break some dynamically enabled slots. Comments added.

2022-04-12 11:17 UTC, dmnsobczak commented on platforms/shared/setup/noads-experiment.setup.ts
> +		btfBlockerService.finishFirstCall();
This is a duplicate of this:
https://github.com/Wikia/ad-engine/blob/dev/platforms/f2/setup/dynamic-slots/f2-dynamic-slots.setup.ts#L34
I think that logic of manually enabling the second call can be refactored, for example somewhere in the `shared/ads-mode`. You can run a code on `AD_ENGINE_STACK_START` event, check in slots context or awaiting ad stack if there is any enabled slot with `firstCall` flag in context and if not, then jumping straight to the second call 🤔

2022-04-12 11:17 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		if (context.get(`slots.${adSlot.getSlotName()}.disabled`)) {
This is risky. Some slots are disabled in the ad context and they are enabled once something happen, for example `mobile_prefooter` on mobile is enabled by UAP filling the TLB slot. If you leave this then `mobile_prefooter` won't be pushed to the ads queue and then second call start it won't be requested. Did you checked it?
Also: this looks like a duplicate, because disabled slots won't be filled there:
https://github.com/Wikia/ad-engine/blob/dev/src/ad-engine/services/btf-blocker-service.ts#L115
What's the idea behind it?

2022-04-12 11:26 UTC, nandy-andy commented on src/ad-engine/ad-engine.ts
> +		if (context.get(`slots.${adSlot.getSlotName()}.disabled`)) {
Blocking slots for different providers: GPT and Nativo ;)

2022-04-12 11:27 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		if (context.get(`slots.${adSlot.getSlotName()}.disabled`)) {
Ack. Then it can't be done like this, because this will introduce regression in oustream, mobile_prefooter, ICB and BLB on F2 :(

2022-04-13 06:25 UTC, dmnsobczak commented on platforms/shared/setup/noads-experiment.setup.ts
> +export class NoAdsExperimentSetup implements DiProcess {
👍

2022-04-13 06:32 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		if (context.get(`slots.${adSlot.getSlotName()}.disabled`)) {
Added extra check for Nativo.

2022-04-13 06:33 UTC, dmnsobczak commented on platforms/shared/setup/noads-experiment.setup.ts
> +		btfBlockerService.finishFirstCall();
I'll keep it as it is since this is an experiment, so this code will be removed in the future and manually enabling second call is only used on News&Stories 🤷‍♂️

2022-04-13 07:16 UTC, nandy-andy commented on src/ad-engine/ad-engine.ts
> +		if (context.get(`slots.${adSlot.getSlotName()}.disabled`)) {
As for experiment we can go with that but it should be removed after the experiments are done and we should redesign it in near future (LIS and performance efforts 🤞)

2022-04-13 07:18 UTC, nandy-andy approved these changes
Only for the experiment 😊

2022-04-13 15:06 UTC, nandy-andy approved these changes

2022-04-13 16:06 UTC, merged