ADEN-11724 Bump dependencies
Wikia/ad-engine pull request #1345
Opened 2022-04-08 11:08 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/ADEN-11724

2022-04-11 10:52 UTC, dmnsobczak requested changes
* Husky requires more work
* `jsdom` should be removed
* Let's test package generation after sass upgrade
* Please add better QA notes for manual testing

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"@typescript-eslint/parser": "5.18.0",
This is just an update and it's safe to bump 👍

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"css-loader": "6.7.1",
`* re-export defaultGetLocalIdent` + update of deps 👍

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"lint-staged": "12.3.7",
Nothing major except: `make console task titles more explicit` 👍

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"mocha-jsdom": "^2.0.0",
https://github.com/rstacruz/mocha-jsdom#upgrading-to-v200
> If you are coming from mocha-jsdom v1.x, remove jsdom if you're not using it before upgrading. jsdom is now a direct dependency of mocha-jsdom.

We are not using `jsdom`, tests are using `jsdom-global`. It should be removed after upgrade.

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"prettier": "2.6.2",
https://prettier.io/blog/2020/03/21/2.0.0.html
There are some API changes. Did you tried to run Prettier on the whole project to see if it change anything anywhere?

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"sass-loader": "^12.6.0",
This is a big upgrade. Did you checked release logs of every major version?
I see that minified built files changed. QA should include manual inspection of our templates.

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"sass-loader": "^12.6.0",
Release log:
https://github.com/webpack-contrib/sass-loader/releases/tag/v12.0.0

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"sass-loader": "^12.6.0",
> minimum supported webpack version is 5

What about `"webpack-cli": "4.9.2",`?

2022-04-11 10:52 UTC, dmnsobczak commented on package.json
> +		"husky": "7.0.4",
Upgrading Husky is a pretty complicated process including rewriting the hooks:
https://github.com/typicode/husky-4-to-7
I'm pretty sure that Prettier and Linter won't work, can you check it with some commit?

2022-04-11 15:51 UTC, szymon-nawrocki commented on package.json
> +		"mocha-jsdom": "^2.0.0",
Thanks for pointing that out, I removed  `jsdom` from dependencies

2022-04-11 15:56 UTC, szymon-nawrocki commented on package.json
> +		"husky": "7.0.4",
You're right. I will create a follow up ticket for that

2022-04-11 15:58 UTC, szymon-nawrocki commented on package.json
> +		"sass-loader": "^12.6.0",
Yes, indeed that is a big upgrade. I will create a follow up ticket for that

2022-04-11 16:12 UTC, szymon-nawrocki commented on package.json
> +		"prettier": "2.6.2",
Actually Prettier is run on before every commit, and I don't see in "Files changed" tab that anything was changed by Prettier, so I guess we can assume that it is safe to upgrade this dependency?

2022-04-12 11:22 UTC, preludek approved these changes

2022-04-13 09:19 UTC, merged