ADEN-11764 Fix Nativo regression after implementing NoAdsExperimentSetup
Wikia/ad-engine pull request #1368
Opened 2022-04-19 14:19 UTC by nandy-andy

2022-04-20 09:25 UTC, preludek commented
With this implementation, nativo AdSlots are being created twice which causes some undesired side effects like for example sending 2 success events.

2022-04-20 16:41 UTC, preludek requested changes

2022-04-20 16:41 UTC, preludek commented on src/ad-engine/providers/nativo/nativo.ts
> +		const experimentUnit = this.context.get('state.noAdsExperiment.unitName');
I can't find where this is set. It seems like it is missing and it breaks the current implementation.

2022-04-21 07:11 UTC, preludek approved these changes

2022-04-21 08:17 UTC, preludek commented on spec/platforms/shared/setup/noads-experiment.setup.spec.ts
> +		context.remove('state.noAdsExperiment.unitName');
<3

2022-04-21 08:24 UTC, preludek approved these changes

2022-04-21 08:24 UTC, preludek commented on platforms/shared/setup/noads-experiment.setup.ts
> +		context.set('state.noAdsExperiment.unitName', unitName);
As long as beacons don't overlap it's 👍  we just have to remember to adjust it if we want to use that mechanism for more than 1 slot at a time

2022-04-21 08:37 UTC, nandy-andy commented on platforms/shared/setup/noads-experiment.setup.ts
> +		context.set('state.noAdsExperiment.unitName', unitName);
Definitely, if we want to cross-check the ad units we'll need to make it an array ;)

2022-04-22 08:36 UTC, merged