ADEN-11762 Fixing second iteration of Prebid multi auction
Wikia/ad-engine pull request #1379
Opened 2022-04-22 09:23 UTC by dmnsobczak

2022-04-25 10:46 UTC, bckatarzyna approved these changes

2022-04-25 11:00 UTC, mfarul requested changes

2022-04-25 13:53 UTC, dmnsobczak commented on platforms/ucp-desktop/setup/context/slots/ucp-desktop-slots-context.setup.ts
> +				initStage: true,
Not exactly. The list of Prebid.js placements is not equal to the list of slots. For example on mobile `top_leaderboard` gets bids under `mobile_top_leaderboard` id. Same applies to `incontent_boxad_X` and `top_boxad`: they are both using `mobile_in_content` id. This is a technical/organizational debt :/

2022-04-26 13:15 UTC, dmnsobczak commented on spec/ad-bidders/prebid/adapters/wikia.spec.ts
> +					cpm: 20,
Done!

2022-04-26 13:15 UTC, dmnsobczak commented on src/ad-bidders/prebid/index.ts
> +				const mainStageTimeout = context.get('bidders.prebid.mainTimeout') || this.timeout;
Done!

2022-04-27 13:54 UTC, mfarul approved these changes

2022-04-29 12:44 UTC, merged