ADEN-11799 | Integrating prebid native ads from AppNexus
Wikia/ad-engine pull request #1432
Opened 2022-06-03 12:20 UTC by bckatarzyna

2022-06-06 08:57 UTC, nandy-andy commented on src/ad-bidders/prebid/adapters/appnexus.ts
> +								ratio_height: 1,
Are the `1`s and `100`s needed only for the whole adapter to work? Maybe it's worth setting some real minimal sizes like mobile's minimum 300x50? 🤔 On the other hand it's a native ad, so it doesn't really need to match regular display ads sizes. The "magic numbers" just caught my attention 😅

2022-06-06 09:00 UTC, nandy-andy commented on src/ad-bidders/prebid/native/prebid-native-provider.ts
> +	getPrebidNativeTemplate(): string {
If we can't use here any templating system like [mustache](https://github.com/janl/mustache.js/) or just load an HTML file maybe it'll be worth changing the concatenated string to a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) in order to make it more readable.

2022-06-06 09:01 UTC, nandy-andy commented on src/ad-engine/providers/nativo/nativo.ts
> +			if (slotName == Nativo.INCONTENT_AD_SLOT_NAME) {
Let's get rid off the comment above it seems it already got lost 🙈

2022-06-06 09:08 UTC, nandy-andy commented on src/ad-bidders/prebid/native/prebid-native-provider.ts
> +		const ntvAdSLot = document.getElementById(adSlotName);
We don't need capital `L` here.

2022-06-06 09:11 UTC, nandy-andy commented on src/ad-bidders/prebid/native/prebid-native-provider.ts
> +export class PrebidNativeProvider {
I wonder if we should use here "Provider" word as it suggests the Provider interface is used where it is not 😊 Maybe nothing holds us from implementing the interface and making the class doing the provider's job: initialising itself and filling/rendering slots. The rest of the class responsibilities (getting/preparing the template) could be moved to `PrebidAdRenderer` and `PrebidAdTemplate` classes that would be a dependency for `PrebidNativeProvider` and would be used in the `fillIn()` method of the provider. But it's easier to write as a comment than code. We could discuss it in a wider group and maybe work on it as follow-up that we'd add to the "ads providers brainstorming" 😉

2022-06-06 09:12 UTC, nandy-andy commented on src/ad-engine/providers/nativo/nativo.ts
> +				communicationService.emit(eventsRepository.NO_NATIVO_AD, {
Basically we could emit such event for all nativo slots and let the provider decide if it can fill the slot or not 🤔

2022-06-06 09:23 UTC, nandy-andy commented on src/ad-bidders/prebid/native/prebid-native-provider.ts
> +	private renderPrebidNativeAd(adSlotName: string, data: PrebidNativeData): void {
I wonder why we want to keep it `private`. Making it `protected` could help us unit test the most crucial for business part -- checking if it's been called when `data.native` has been received from a bidder (through `window.pbjs.getHighestUnusedBidResponseForAdUnitCode()`). Making it public could help us unit test the input-output scenario in which we mock DOM element and check if after calling `renderPrebidNativeAd()` with proper data we got the HTML we expect.

2022-06-06 09:24 UTC, nandy-andy commented on src/ad-bidders/prebid/native/prebid-native-provider.ts
> +			communicationService.emit(eventsRepository.NO_NATIVE_PREBID_AD, {
Shouldn't we emit this only when `data.native` is undefined/in the `else` part of the condition?

2022-06-06 09:27 UTC, nandy-andy commented on src/ad-bidders/prebid/native/prebid-native-provider.ts
> +			if (assetsMap[assetName]) {
In order to make the code more readable and with less indentation you could extract the if and its body to `replaceAssetPlaceholderWithValueIfExist()` -- java-like name but tells you exactly what happens in the if without scanning the code.

2022-06-06 09:30 UTC, nandy-andy requested changes
Let's replace string concatenation with something more readable and try add some unit tests. In terms of the provider's future/brainstorming maybe we should fill a follow-up.

2022-06-06 10:31 UTC, bckatarzyna commented on src/ad-bidders/prebid/adapters/appnexus.ts
> +								ratio_height: 1,
I set 1:1 ratio to have the ad similar to Nativo one. In case of minimum size - I have no idea what would be the best in terms of our ads and prebid inventory availability. I event don't know what would be better: logo or image. Image seems to be more detailed and attractive but I'm not sure if they are available in small sizes and 1:1 ratios? This is why I created this ticket: https://fandom.atlassian.net/browse/ADEN-11849. Hope all the questions like this will find the explanation over there.

2022-06-07 07:21 UTC, bckatarzyna commented on src/ad-bidders/prebid/native/prebid-native-provider.ts
> +			communicationService.emit(eventsRepository.NO_NATIVE_PREBID_AD, {
Yes... we should 🙈

2022-06-07 10:54 UTC, bckatarzyna commented on src/ad-engine/providers/nativo/nativo.ts
> +				communicationService.emit(eventsRepository.NO_NATIVO_AD, {
But using `.on(event)` don't we take care only of the first of the events?

2022-06-07 11:04 UTC, bckatarzyna commented on src/ad-bidders/prebid/native/prebid-native-provider.ts
> +export class PrebidNativeProvider {
Follow up ticket created https://fandom.atlassian.net/browse/ADEN-11913

2022-06-07 11:27 UTC, nandy-andy commented on src/ad-engine/providers/nativo/nativo.ts
> +				communicationService.emit(eventsRepository.NO_NATIVO_AD, {
By default we do but there is a flag ;) Anyway, I think this could be a future discussion included in https://fandom.atlassian.net/browse/ADEN-11913 👌

2022-06-07 11:42 UTC, nandy-andy commented on src/ad-engine/providers/nativo/nativo.ts
> +			this.handleNtvNativeEvent(e, slotName, AdSlot.STATUS_COLLAPSE);
OK, before we release it globally we'll need to add one more functionality to the Nativo module: handling collapses from PrebidNativeProvider. It may be a `watchPrebidNativeEvnets()` in which we just listen to `NO_NATIVE_PREBID_AD` and if it's emitted we execute `replaceWithAffiliateUnit()`. So, when Nativo does not return anything, PrebidNative does not fill the slot we have still chances to render the affiliate unit 🤔

2022-06-07 11:46 UTC, nandy-andy approved these changes
If we don't plan to release it globally, we can move on and share with AppNexus special links to check if it works fine on their side 👍 We should take care of the follow-ups before we release it globally, though.

2022-06-09 11:56 UTC, merged