ADEN-11823 - Page Level Targeting Part I
Wikia/ad-engine pull request #1448
Opened 2022-06-24 09:56 UTC by Tomasz-at-Fandom

2022-06-27 08:21 UTC, dmnsobczak requested changes
`.DS_Store` and `spec/.DS_Store` shouldn't be committed - please remove them and add it to the `.gitignore` file :)
Apart from that: all good 👍

2022-06-27 11:29 UTC, Tomasz-at-Fandom commented
Good catch, thanks!  Totally missed that 😨

2022-06-28 05:46 UTC, dmnsobczak approved these changes

2022-06-30 11:14 UTC, dmnsobczak approved these changes

2022-07-11 06:48 UTC, merged