ADEN-12055 Adding Audigent assets preloading
Wikia/ad-engine pull request #1483
Opened 2022-07-29 08:07 UTC by dmnsobczak

2022-07-29 08:45 UTC, bckatarzyna approved these changes

2022-07-29 09:09 UTC, bckatarzyna commented on platforms/shared/utils/instant-config-setup.ts
> +			if (newIntegrationEnabled) {
```suggestion
			if (gamDirectTestEnabled || newIntegrationEnabled) {
```

2022-07-29 09:24 UTC, bckatarzyna commented on src/ad-services/audigent/index.ts
> +		if (gamDirectTestEnabled) {
```suggestion
		if (!this.isLoaded && gamDirectTestEnabled) {
```

2022-07-29 09:24 UTC, bckatarzyna commented on src/ad-services/audigent/index.ts
> +				utils.logger(logGroup, 'audience tag script loaded');
```suggestion
				utils.logger(logGroup, 'audience tag script loaded');
				this.isLoaded = true;
```

2022-07-29 09:27 UTC, bckatarzyna approved these changes

2022-07-29 11:12 UTC, mfarul requested changes

2022-07-29 11:12 UTC, mfarul commented on platforms/shared/utils/instant-config-setup.ts
> +		if (instantConfig.get('icAudigent')) {
Not a very good place to load audigent - how about extracting this from instant-config-setup ?

2022-08-01 07:52 UTC, dmnsobczak commented on platforms/shared/utils/instant-config-setup.ts
> +		if (instantConfig.get('icAudigent')) {
I think that calling Audigent preload from here is fine, because it's `Preload libraries based on ICBM configuration`. I moved the most of the code though into Audigent class - you right, easier to maintain and refactor from there :)

2022-08-01 10:58 UTC, merged