ADEN-12023 Implementing sticking TopBoxad experiment
Wikia/ad-engine pull request #1496
Opened 2022-08-09 11:03 UTC by dmnsobczak

2022-08-09 13:10 UTC, preludek requested changes

2022-08-09 13:10 UTC, preludek commented on platforms/shared/dynamic-slots/sticked-boxad-helper.ts
> +	pusherSlotName: string;
Why is this necessary?

2022-08-09 13:10 UTC, preludek commented on platforms/shared/dynamic-slots/sticked-boxad-helper.ts
> +	slotName: string;
That's like always top_boxad right? :D

2022-08-09 13:10 UTC, preludek commented on platforms/ucp-desktop/templates/ucp-desktop-templates.setup.ts
> +			railSelector: '.main-page-tag-rcs #top_boxad, #rail-boxad-wrapper',
Maybe it's time (or maybe not :P) to think about setting this and similar selectors as constants somewhere in platforms?

2022-08-09 13:10 UTC, preludek commented on platforms/shared/dynamic-slots/sticked-boxad-helper.ts
> +					pageElement.classList.add('companion-viewed');
This may break AdEngine if something goes wrong in line 75.

2022-08-10 05:29 UTC, dmnsobczak commented on platforms/shared/dynamic-slots/sticked-boxad-helper.ts
> +	pusherSlotName: string;
I don't like hardcoded slot names in the class located in `shared` directory. Also I want this class to be expanded on mobile while implementing sticky incontents there - configuration will handle different logic there 🤔

2022-08-10 05:30 UTC, dmnsobczak commented on platforms/shared/dynamic-slots/sticked-boxad-helper.ts
> +	slotName: string;
Yes, but same reason - instead of hardcoding `top_boxad` 2 or 3 times I prefer to store it in the variable and use when needed :D

2022-08-10 05:33 UTC, dmnsobczak commented on platforms/ucp-desktop/templates/ucp-desktop-templates.setup.ts
> +			railSelector: '.main-page-tag-rcs #top_boxad, #rail-boxad-wrapper',
Layout constants are used in the Templates 2.0 (for example in UAP) and I think that it is a bit overkill to create a template handler for this sticking functionality. It will also require some changes allowing two templates to work at the same time in case of UAP. So maybe in the future :D

2022-08-10 05:34 UTC, dmnsobczak commented on platforms/shared/dynamic-slots/sticked-boxad-helper.ts
> +					pageElement.classList.add('companion-viewed');
Additional check added! 🙇

2022-08-10 05:36 UTC, dmnsobczak commented on platforms/shared/dynamic-slots/sticked-boxad-helper.ts
> +	initialize(params: StickedBoxadHelperConfiguration): void {
Splitted!

2022-08-10 10:23 UTC, preludek approved these changes

2022-08-22 08:58 UTC, merged