ADEN-11921 Reconfigure Eyeota integration for GDPR etc
Wikia/ad-engine pull request #1506
Opened 2022-08-26 06:26 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/ADEN-11921

2022-08-26 09:23 UTC, preludek approved these changes

2022-08-26 09:23 UTC, preludek commented on spec/ad-services/eyeota/eyeota.spec.ts
> +		context.set('services.eyeota.enabled', undefined);
I'd use `context.remove` here. Or bonus points for adding a `clear` method or something like that, that removes all at once.

2022-08-26 09:23 UTC, preludek commented on src/communication/event-types.ts
> +	EYEOTA_STARTED: {
semantics but maybe `ready`? ;)

2022-08-26 09:24 UTC, preludek requested changes
wrong button xd

2022-08-29 05:38 UTC, szymon-nawrocki commented on src/communication/event-types.ts
> +	EYEOTA_STARTED: {
I used `start` to be consistent with the events defined here:
https://github.com/Wikia/ad-engine/blob/289d98e9fd4e60fdcf4c1336ee7d4738be80228c/src/ad-engine/services/load-times-service.ts#L6

Plus it is clearly stated in the ticket to add "integration_**start**" event :)

2022-08-29 08:00 UTC, preludek approved these changes

2022-08-29 08:25 UTC, merged