ADEN-12097 Refactored BaseServiceSetup into Decorator
Wikia/ad-engine pull request #1509
Opened 2022-08-29 12:16 UTC by domjanik

[Ticket](https://fandom.atlassian.net/browse/ADEN-12097)

2022-08-30 05:19 UTC, szymon-nawrocki commented on platforms/shared/setup/ad-engine.setup.ts
> +let adEngineInstance: AdEngine;
Why this variable is not encapsulated inside a class?

2022-08-30 05:32 UTC, szymon-nawrocki approved these changes

2022-08-30 07:12 UTC, domjanik commented on platforms/shared/setup/ad-engine.setup.ts
> +let adEngineInstance: AdEngine;
Good point, thanks for noticing it!

2022-08-30 08:21 UTC, dmnsobczak requested changes
Everything is fine, but please reset `package-lock.json`, because it was completely overwritten. You should use `npm ci` while setting up local AdEngine instance and only update the lock with required packages - though I don't see anything added in this PR 🤔

2022-08-30 08:26 UTC, dmnsobczak approved these changes

2022-10-13 04:46 UTC, dmnsobczak approved these changes

2022-10-19 12:15 UTC, merged