ADEN-11788 Added new path for ICBM fallbacks
Wikia/ad-engine pull request #1531
Opened 2022-09-08 06:48 UTC by domjanik

[ADEN-11788](https://fandom.atlassian.net/browse/ADEN-11788)

2022-09-08 07:57 UTC, bckatarzyna approved these changes

2022-09-14 07:15 UTC, szymon-nawrocki approved these changes
👌

2022-09-19 16:19 UTC, mfarul requested changes

2022-09-19 16:19 UTC, mfarul commented on platforms/sports/ad-context.ts
> +				'https://script.wikia.nocookie.net/fandom-ae-assets/icbm/prod/icbm_state_muthead_json',
_json should be .json

2022-09-20 10:14 UTC, mfarul approved these changes

2022-09-20 12:12 UTC, merged