ADEN-12194 Refactor targeting strategies
Wikia/ad-engine pull request #1532
Opened 2022-09-12 07:28 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/ADEN-12194

2022-09-12 10:18 UTC, mfarul requested changes

2022-09-12 10:18 UTC, mfarul commented on @types/fandom/index.d.ts
> +		legacyVertical: string;
let's move this to fields into a one called taxonomy, that will contain string[] table of a full taxonomy path,f.e. ['life']['lifestyle']['tv']['zombies']['the walking dead']. Then we could just use s0v=taxonomy[0], s0=taxonomy[1] if they are available.
Thus we will be open for all sites that will have richer / poorer taxonomy.

2022-09-12 10:18 UTC, mfarul commented on platforms/shared/context/targeting/targeting-strategies/interfaces/taxonomy-tags.ts
> +export interface PrefixableTaxonomyTags {
Why call them prefixable? This is a site effect of some strategies not the type per se. They are rather strategy resolved depended tags, instead of the 3 ones down that are always get from the same place.

2022-09-12 10:18 UTC, mfarul commented on platforms/shared/context/targeting/targeting-strategies/strategies/common-strategy.ts
> +	protected addPagePrefixToValues(tags: TaxonomyTags): PrefixableTaxonomyTags {
why this is a part of common? I would extract this into separate class that will add prefixes and combinations

2022-09-12 10:18 UTC, mfarul commented on platforms/shared/context/targeting/targeting-strategies/strategies/combined-strategy-site-tags-based.ts
> +export class CombinedStrategySiteTagsBased
is it possible to build this based on SiteContextStrategy class? Or even better - could we use delegation strategy to build combined strategy from any other one?

2022-09-12 11:34 UTC, szymon-nawrocki commented on platforms/shared/context/targeting/targeting-strategies/strategies/common-strategy.ts
> +			s0: fandomContext.site.legacyVertical || fandomContext.site.vertical,
* `legacyVertical` is needed to set targeting `s0` value
* `wikiVertical` is needed to set `s0v` value

2022-09-12 11:35 UTC, szymon-nawrocki commented on platforms/shared/context/targeting/targeting-strategies/strategies/common-strategy.ts
> +			s0v: fandomContext.site.wikiVertical || wiki.targeting.wikiVertical,
I've added the information about it in the release notes, but good point that it should be also added here 👍

2022-09-12 11:36 UTC, szymon-nawrocki commented on platforms/shared/context/targeting/targeting-strategies/strategies/common-strategy.ts
> +			s0v: fandomContext.site.wikiVertical || wiki.targeting.wikiVertical,
done ✅

2022-09-12 11:43 UTC, szymon-nawrocki commented on platforms/shared/context/targeting/targeting-strategies/interfaces/taxonomy-tags.ts
> +export interface PrefixableTaxonomyTags {
I've divided the interface into two, to make it more visible, to which tags we are adding `p_` prefix.
But on the other hand it is visible in place where we are adding prefixes here:
https://github.com/Wikia/ad-engine/blob/933ad5c8ea057e9b01fe25657b7ba608fb6e51b9/platforms/shared/context/targeting/targeting-strategies/strategies/common-strategy.ts#L11

So now I see that indeed it is not needed here, and probably makes things less readable.

2022-09-13 05:23 UTC, szymon-nawrocki commented on platforms/shared/context/targeting/targeting-strategies/strategies/common-strategy.ts
> +			s0: fandomContext.site.legacyVertical || fandomContext.site.vertical,
I moved it to `taxonomy` variable ✅

2022-09-13 05:24 UTC, szymon-nawrocki commented on @types/fandom/index.d.ts
> +		legacyVertical: string;
Done in:
https://github.com/Wikia/unified-platform/pull/11246

2022-09-14 07:21 UTC, szymon-nawrocki commented on platforms/shared/context/targeting/targeting-strategies/strategies/combined-strategy-site-tags-based.ts
> +export class CombinedStrategySiteTagsBased
Probably it is possible and it should be done in this way to make the code more clean.
However I decided not doing this in this PR. but revisit it after the Sprint work will be done

2022-09-14 08:04 UTC, mfarul commented on platforms/shared/context/targeting/targeting-strategies/utils/tag-combinator.ts
> +					combinedTags[key] = siteTags[key].concat(pageTags[key]);
does this make any sense? e.g. if we are going through prefixable tags and sending them with p_ why we are combining the values?

2022-10-14 06:57 UTC, domjanik approved these changes

2022-10-14 07:00 UTC, domjanik requested changes

2022-10-14 07:00 UTC, domjanik commented on src/platforms/shared/context/targeting/targeting-strategies/strategies/common-tags.ts
> +			esrb: this.fandomContext.site.esrbRating || '',
I think that esrbRating should be moved to the optionalKeyVals as well - currently it has been moved to that section and it was done after last changes to ESRB Rating

2022-10-14 08:55 UTC, szymon-nawrocki commented on src/platforms/shared/context/targeting/targeting-strategies/strategies/common-tags.ts
> +			esrb: this.fandomContext.site.esrbRating || '',
Great suggestion! Now instead of empty string it will be 1 key val less and shorter URL

2022-10-14 08:55 UTC, szymon-nawrocki commented on src/platforms/shared/context/targeting/targeting-strategies/strategies/common-tags.ts
> +			esrb: this.fandomContext.site.esrbRating || '',
Done ✅

2022-10-14 08:56 UTC, domjanik approved these changes

2022-10-14 09:37 UTC, mfarul requested changes

2022-10-14 09:37 UTC, mfarul commented on src/platforms/shared/context/targeting/targeting-strategies/decorators/summary-decorator.ts
> +	constructor(private commonTags: CommonTags, private strategyToSum: TargetingStrategyInterface) {}
This could sum any of the TargetingStrategyInterface and not only a one with CommonTags?
If this is possible it should be:
`constructor(private tagsToSum: TargetingStrategyInterface[]) {}`

2022-10-14 09:37 UTC, mfarul commented on src/platforms/shared/context/targeting/targeting-strategies/decorators/combine-tags-decorator.ts
> +export class CombineTagsDecorator implements TargetingStrategyInterface {
looking at this now, you were right, it is not the Decorator rather Composer, let's rename this one into TagsByKeyComposer and the package to structures

2022-10-14 09:37 UTC, mfarul commented on src/platforms/shared/context/targeting/targeting-strategies/decorators/summary-decorator.ts
> +export class SummaryDecorator implements TargetingStrategyInterface {
let's call it TagsPlainSumBuilder

2022-10-14 10:30 UTC, szymon-nawrocki commented on src/platforms/shared/context/targeting/targeting-strategies/decorators/summary-decorator.ts
> +	constructor(private commonTags: CommonTags, private strategyToSum: TargetingStrategyInterface) {}
You're right, so it will enable easy adding of new set of tags in the future

2022-10-14 10:30 UTC, szymon-nawrocki commented on src/platforms/shared/context/targeting/targeting-strategies/decorators/summary-decorator.ts
> +	constructor(private commonTags: CommonTags, private strategyToSum: TargetingStrategyInterface) {}
Done ✅

2022-10-14 10:34 UTC, szymon-nawrocki commented on src/platforms/shared/context/targeting/targeting-strategies/decorators/combine-tags-decorator.ts
> +export class CombineTagsDecorator implements TargetingStrategyInterface {
Great suggestion! Done ✅

2022-10-14 11:04 UTC, szymon-nawrocki commented on src/platforms/shared/context/targeting/targeting-strategies/decorators/summary-decorator.ts
> +export class SummaryDecorator implements TargetingStrategyInterface {
Done ✅

2022-10-18 09:18 UTC, mfarul commented on spec/platforms/shared/context/targeting/targeting-strategies/strategies/combined-strategy.spec.ts
> +		const combinedStrategy = new TagsPlainSumBuilder([
move the creation code to one method or just use Factory from create-selected-strategy.st

2022-10-18 09:19 UTC, mfarul commented on spec/platforms/shared/context/targeting/targeting-strategies/strategies/combined-strategy.spec.ts
> +		s0: 'life',
move this to constant and use here and in #52

2022-10-18 09:22 UTC, mfarul commented on spec/platforms/shared/context/targeting/targeting-strategies/providers/common-tags.spec.ts
> +	it('commonTags are returned correctly', function () {
here the taxonomy[] -> s0, s0v is hidden it could be an explicit new test

2022-10-18 09:24 UTC, mfarul commented on src/platforms/shared/context/targeting/targeting-strategies/providers/common-tags.ts
> +			s0v: this.fandomContext.site.taxonomy?.[1] || wiki.targeting.wikiVertical,
[1] will not throw if we have 1 element array?

2022-10-18 12:56 UTC, szymon-nawrocki commented on spec/platforms/shared/context/targeting/targeting-strategies/strategies/combined-strategy.spec.ts
> +		s0: 'life',
done ✅

2022-10-18 13:28 UTC, szymon-nawrocki commented on src/platforms/shared/context/targeting/targeting-strategies/providers/common-tags.ts
> +			s0v: this.fandomContext.site.taxonomy?.[1] || wiki.targeting.wikiVertical,
no, it will return `undefined`

2022-10-18 13:30 UTC, szymon-nawrocki commented on spec/platforms/shared/context/targeting/targeting-strategies/providers/common-tags.spec.ts
> +	it('commonTags are returned correctly', function () {
I extracted taxonomy values into `const` and now testing this functionality is included in the main test

2022-10-18 14:09 UTC, szymon-nawrocki commented on spec/platforms/shared/context/targeting/targeting-strategies/providers/common-tags.spec.ts
> +	it('commonTags are returned correctly', function () {
But I added the tests for the case: `'s0 and s0v get assigned empty string when taxonomy value is empty array'`

2022-10-20 10:07 UTC, mfarul approved these changes

2022-10-27 06:59 UTC, domjanik approved these changes

2022-10-27 09:51 UTC, merged