ADEN-12179 Refactored UserIdentity, Added UserIdentity to Sports platform
Wikia/ad-engine pull request #1533
Opened 2022-09-13 09:32 UTC by domjanik

[Ticket](https://fandom.atlassian.net/browse/ADEN-12179)

2022-09-13 10:06 UTC, mfarul requested changes

2022-09-13 10:06 UTC, mfarul commented on src/ad-engine/utils/storage.ts
> +class Storage {
what Storage ? Take a look also on StorageProvider and UniversalStorage class ;)

2022-09-13 10:06 UTC, mfarul commented on src/ad-engine/utils/uuid.ts
> +class Uuid {
do we need this encapsulation ? can we just use uuid() function?

2022-09-13 10:06 UTC, mfarul commented on src/ad-services/user-identity/adms-strategy/adms-client.ts
> +	return window.location.hostname.includes('fandom.com')
will it work on futhead.com  or muthead.com ?

2022-09-13 10:06 UTC, mfarul commented on src/ad-services/user-identity/adms-strategy/adms-client.ts
> +		return fetch(this.ADMS + `profiles?cb=${Date.now()}`, {
what are the cookies required for this call on futhead.com? beacon's ?

2022-09-13 10:06 UTC, mfarul commented on src/ad-services/user-identity/adms-strategy/adms-service.ts
> +class AdmsService {
for future: this could a generic functionality that will combine local and backend storages

2022-09-13 10:06 UTC, mfarul commented on src/ad-services/user-identity/adms-strategy/index.ts
> +class AdmsStrategy implements StorageStrategyInterface {
AdmsIdentityStorage?

2022-09-13 10:06 UTC, mfarul commented on src/ad-services/user-identity/index.ts
> +			await this.setupPPID(ppid.strategy);
where do we set ppid.strategy?

2022-09-13 10:49 UTC, domjanik commented on src/ad-engine/utils/uuid.ts
> +class Uuid {
It's necessary for sake of our tests - There are pretty serious problems with unit tests when you use that library and "cleanest" solution is to use additional layer, that can be mocked in tests

2022-09-13 10:50 UTC, domjanik commented on src/ad-services/user-identity/adms-strategy/adms-client.ts
> +		return fetch(this.ADMS + `profiles?cb=${Date.now()}`, {
We need FandomGlobalID, however if we won't provide it - it'll work anyway, create proper object and save it in LocalStorage but won't sync it with backend.

2022-09-13 10:51 UTC, domjanik commented on src/ad-services/user-identity/index.ts
> +			await this.setupPPID(ppid.strategy);
It has been moved to separate feature flag. I was thinking about changing existing one

2022-09-13 11:52 UTC, domjanik commented on src/ad-services/user-identity/adms-strategy/adms-service.ts
> +class AdmsService {
If we will need it somewhere else I think it won't be a problem to move it to some other place. Right now I think we can leave it there :)

2022-09-13 12:46 UTC, nandy-andy commented on spec/ad-services/user-identity/user-identity.spec.ts
> +		sandbox.restore();
I think it's a good practice of ours to also reset our god-object config here with something like:
```js
context.set('services.ppid.enabled', undefined);
```
or:
```js
context.remove('services.ppid.enabled');
```
It helps not polluting the god object in all tests run.

2022-09-13 12:58 UTC, nandy-andy commented on src/ad-services/user-identity/adms-identity-repository/adms-client.ts
> +	storage = new UniversalStorage();
I wonder if it's worth passing it as an argument in the constructor just in case we'd like to replace `UniversalStorage` with something else 🤔

2022-09-13 13:10 UTC, nandy-andy commented on src/ad-services/user-identity/index.ts
> +		try {
Should we make `setupPPID()` also private? I'm guessing we'd like clients to use only `call()` 🤔

2022-09-13 13:14 UTC, nandy-andy commented on src/ad-services/user-identity/adms-identity-repository/adms-client.ts
> +		return this.storage.getItem('silver-surfer-active-data-v2') as ActiveData;
Consider keeping the item's name in a class field, so then you can reuse it in these two lines: 58 and 62 ;)

2022-09-13 13:18 UTC, nandy-andy commented on src/ad-services/user-identity/adms-identity-repository/index.ts
> +			(id) => id.payload.identityType === 'ppid',
Shall we extract it, so it's easily extensible in the future without modifying the code here? I'm thinking here that in the future we'd like also to retrieve HEMs for example from the ADMS but maybe I'm confusing different topics 😊 But if I am not, then adding more types will force us to modify this piece of code and it'll get ugly after a while 🙈 I'm afraid of something like:
```js
let identity: IdentityAction = userData?.IDENTITY?.find(
			(id) => id.payload.identityType === 'ppid' || id.payload.identityType === 'ppid' || id.payload.identityType === 'nandy-is-over-engineering'
);
```

2022-09-13 13:18 UTC, domjanik commented on src/ad-services/user-identity/index.ts
> +		try {
Unfortunately - I can't make it private if I want to spy on it in tests :(

2022-09-13 13:20 UTC, nandy-andy commented on src/ad-services/user-identity/index.ts
> +		try {
Pity, thanks for checking!

2022-09-13 13:26 UTC, nandy-andy commented on src/ad-services/user-identity/index.ts
> +		try {
Hm, alternatively we could create a `didSetup` public flag to check in the tests and then make `setupPPID()` private 🤔 But maybe it's not worth it... I mean we (the AdEng team) are the only clients of the service ;p

2022-09-13 13:27 UTC, nandy-andy approved these changes

2022-09-14 14:14 UTC, mfarul commented on src/ad-services/user-identity/adms-identity-repository/adms-client.ts
> +				(location.hostname.match(/(?!\.)(pl|us)$/) || ['us'])[0] +
this could be used as index solely

2022-09-14 14:16 UTC, mfarul approved these changes

2022-09-14 14:23 UTC, merged