ADEN-12189 Integrate LiveConnect into f2
Wikia/ad-engine pull request #1545
Opened 2022-09-19 09:21 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/ADEN-12189

2022-09-21 09:01 UTC, domjanik approved these changes

2022-09-21 09:01 UTC, domjanik commented
Looks good to me :)

2022-09-21 10:21 UTC, mfarul requested changes

2022-09-21 10:21 UTC, mfarul commented on src/ad-services/live-connect/index.ts
> +		this.isLoaded = this.isAvailableInLocalStorage(`${partnerName}-unifiedId`);
Here we should check for unifiedId and sha2 presence as the first one will be almost always available but sha2 could be resolved later. 
Then I would also add checking optional once in resolveId.

2022-09-21 10:24 UTC, mfarul approved these changes

2022-09-21 10:25 UTC, mfarul commented on src/ad-services/live-connect/index.ts
> +		this.isLoaded = this.isAvailableInLocalStorage(`${partnerName}-unifiedId`);
On the other hand we use session storage here, so the chance of resolving sha2 during session is almost 0%. Let's leave it as it is.

2022-09-26 06:43 UTC, domjanik approved these changes

2022-09-27 16:53 UTC, mfarul commented on src/ad-services/live-connect/index.ts
>  	resolveId(idName, partnerName) {
shouldn't we skip resolving if we have ID in cache?

2022-09-27 16:53 UTC, mfarul commented on src/ad-services/live-connect/index.ts
> +		if (!this.storageConfig.mandatoryParams.includes(idName)) {
why saving only mandatory? those are only set up to skip or fire resolving

2022-09-29 08:46 UTC, merged