ADEN-12533 Add initial prebid configuration for remaining NnR sites
Wikia/ad-engine pull request #1653
Opened 2022-12-14 17:09 UTC by nandy-andy

2022-12-15 09:52 UTC, dmnsobczak requested changes

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/gamefaqs/gamefaqs-platform.ts
> +			() => communicationService.emit(eventsRepository.AD_ENGINE_CONFIGURED),
`AD_ENGINE_CONFIGURED` should be the last step of platform execution - why it is in the middle?

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/comicvine/comicvine-platform.ts
>  			gptSetup.call,
I think this will run `.call()` twice, because it's execution is included in the `.execute()` method - just `gptSetup` should be enough (see `BaseServiceSetup` class).

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/comicvine/comicvine-platform.ts
> +					.call()
I don't like calling `.call()` manually since `bidders` is an instance of `BaseServiceSetup` class that handles more things like setting if it is initialized or handling options. The `execute()` entry point is an async function that returns `Promise<void>` - maybe you can (with or without simple changes) attach `.then()` to it and simplify it to `bidders.then(() => communicationService.emit(eventsRepository.AD_ENGINE_PARTNERS_READY))`?

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/comicvine/comicvine-platform.ts
> +					.call()
Another idea is to add new option and run it like that:
```
	bidders.setOptions({
		after: () => communicationService.emit(eventsRepository.AD_ENGINE_PARTNERS_READY),
	}),
```

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/gamefaqs/gamefaqs-platform.ts
>  				bidders
ditto

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/gamespot/gamespot-platform.ts
> +				bidders
ditto

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/gamespot/gamespot-platform.ts
>  			() => context.set('custom.dfpId', this.shouldSwitchGamToRV() ? 22309610186 : 5441),
I hope this is temporary xD

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/giantbomb/giantbomb-platform.ts
> +				bidders
ditto

2022-12-15 09:52 UTC, dmnsobczak commented on src/platforms/metacritic/metacritic-platform.ts
> +				bidders
ditto

2022-12-15 10:25 UTC, nandy-andy commented on src/platforms/gamefaqs/gamefaqs-platform.ts
> +			() => communicationService.emit(eventsRepository.AD_ENGINE_CONFIGURED),
it's at the end of setup 🤔

2022-12-15 10:29 UTC, nandy-andy commented on src/platforms/gamespot/gamespot-platform.ts
>  			() => context.set('custom.dfpId', this.shouldSwitchGamToRV() ? 22309610186 : 5441),
Ofc.

2022-12-15 10:31 UTC, nandy-andy commented on src/platforms/comicvine/comicvine-platform.ts
> +					.call()
Worth discussing offline at a tech refinement and filling up a follow-up.

2022-12-15 10:33 UTC, nandy-andy commented on src/platforms/comicvine/comicvine-platform.ts
>  			gptSetup.call,
We've been testing it on other platforms since couple of weeks and nobody notices the described issue. Worth checking offline later 🤔

2022-12-15 10:46 UTC, nandy-andy commented on src/platforms/comicvine/comicvine-platform.ts
>  			gptSetup.call,
But you're right! Reading the code suggest it'll execute twice 🙈 However, when I try to change it I got:
<img width="1031" alt="Screenshot 2022-12-15 at 11 44 29" src="https://user-images.githubusercontent.com/1662451/207839638-ff57bdc8-1b7d-477b-a88b-44b2c3e1ede2.png">

2022-12-15 10:49 UTC, nandy-andy commented on src/platforms/comicvine/comicvine-platform.ts
>  			gptSetup.call,
I've created a follow-up: https://fandom.atlassian.net/browse/ADEN-12536

2022-12-15 10:49 UTC, nandy-andy commented on src/platforms/comicvine/comicvine-platform.ts
> +					.call()
I've created a follow-up: https://fandom.atlassian.net/browse/ADEN-12536

2022-12-15 10:58 UTC, dmnsobczak approved these changes
Discussed on Slack

2022-12-22 05:50 UTC, dmnsobczak approved these changes
LGTM, but please equip all platforms with `dependencies: [bidders.initialized]` like on GameFaqs 👍

2022-12-22 10:45 UTC, szymon-nawrocki commented on src/ad-bidders/index.ts
> +			utils.logger(logGroup, 'resolving call() promise because of no bidder providers');
This log could be more descriptive, and describe what does "resolving call() promise" mean in this case. So a person who reads the logs and doesn't know the code by heart knows what happened in bidders setup

2022-12-22 10:49 UTC, nandy-andy commented on src/ad-bidders/index.ts
> +			utils.logger(logGroup, 'resolving call() promise because of no bidder providers');
Don't you think the group printed next to it helps?

2022-12-22 10:57 UTC, szymon-nawrocki approved these changes

2022-12-23 11:36 UTC, merged