ADEN-AdEngine-2023 New Year's major upgrade pack
Wikia/ad-engine pull request #1662
Opened 2022-12-22 08:42 UTC by dmnsobczak

2022-12-27 08:34 UTC, preludek commented on spec/ad-products/templates/interface/listeners/player-overlay-click-listener.spec.ts
> +import { onVideoOverlayClick } from '@wikia//ad-products/templates/interface/listeners/player-overlay-click-listener';
import { onVideoOverlayClick } from '@wikia/ad-products/templates/interface/listeners/player-overlay-click-listener';
```suggestion
import { onVideoOverlayClick } from '@wikia//ad-products/templates/interface/listeners/player-overlay-click-listener';
```

2022-12-27 08:35 UTC, preludek commented on spec/ad-products/templates/uap/ui/ui-template.spec.ts
> +import { CloseButton } from '@wikia//ad-products/templates/interface/video/close-button';
```suggestion
import { CloseButton } from '@wikia/ad-products/templates/interface/video/close-button';
```

2023-01-02 12:10 UTC, nandy-andy commented on .nycrc
> +  "lines": 55,
Why not the old 50? Here and in the next 3 lines below :D

2023-01-02 12:12 UTC, nandy-andy commented on package.json
> +		"@babel/runtime-corejs2": "7.20.7",
Do we still need it? I thought you mentioned removing babel and above there is a `babel-app.config.js` being removed 🤔

2023-01-02 12:25 UTC, nandy-andy commented on package.json
> +		"test-coverage": "nyc instant-mocha './src/!(platforms)*/**/*.ts' './src/platforms/shared/**/*.ts' './spec/**/*.spec.ts' -r jsdom-global/register --webpack-config webpack.coverage.js"
What are the paths we're passing here? They seem similar except the first one seem like we want to exclude any `*.ts` files inside `src/platforms/` and the other one seem like we want to include any `*.ts` files within `src/platforms/shared` and then include all `spec/**/*.spec.ts` files with unit tests 🤔

2023-01-02 12:29 UTC, nandy-andy commented on spec/spec-utils/html-element.stub.ts
> -// @TODO: remove if not needed
I've used it in one [recently added test](https://github.com/Wikia/ad-engine/pull/1674/files#diff-5340cb2ea465ad9c489f2f4153318cf2faf8253639584140aee8b770e6356db8R7) 😊 But if we don't use it anywhere else, we can 🔪 it, I guess 🤔

2023-01-02 12:31 UTC, nandy-andy commented on src/ad-products/video/jwplayer/streams/jwplayer-stream-stateless.ts
> +			distinctUntilChanged((a, b) => a.playlistItem.mediaid === b.playlistItem.mediaid),
🙀 you removed typing! Why?! ;)

2023-01-02 12:33 UTC, nandy-andy commented on src/core/services/templates-registry/template-registry.ts
> +			// @ts-ignore "this context fix"
Could you elaborate more why we need the `@ts-ignore` here? Is it waiting for changes with the god object (`context`)?

2023-01-02 12:36 UTC, nandy-andy requested changes
Looks good. Let's add follow-up tickets for all the TODOs.

2023-01-02 15:16 UTC, dmnsobczak commented on .nycrc
> +  "lines": 55,
I included all files in code coverage report, not only those imported in existing test files. This resulted in a visible drop in real code coverage :< So I set those limit below current readings and in the future we will use them to enforce unit testing 🧐

2023-01-02 15:20 UTC, dmnsobczak commented on package.json
> +		"test-coverage": "nyc instant-mocha './src/!(platforms)*/**/*.ts' './src/platforms/shared/**/*.ts' './spec/**/*.spec.ts' -r jsdom-global/register --webpack-config webpack.coverage.js"
I want to import everything inside `/src/`, but not platform directories, but I cannot list `excludes` here :/ So I reversed it :D

2023-01-02 15:20 UTC, dmnsobczak commented on package.json
> +		"test-coverage": "nyc instant-mocha './src/!(platforms)*/**/*.ts' './src/platforms/shared/**/*.ts' './spec/**/*.spec.ts' -r jsdom-global/register --webpack-config webpack.coverage.js"
Also: I added it to enforce `instabul-loader` to load all `.ts` files.

2023-01-02 15:21 UTC, dmnsobczak commented on spec/spec-utils/html-element.stub.ts
> -// @TODO: remove if not needed
Is it (your test) on master? 🤔

2023-01-02 15:23 UTC, dmnsobczak commented on src/ad-products/video/jwplayer/streams/jwplayer-stream-stateless.ts
> +			distinctUntilChanged((a, b) => a.playlistItem.mediaid === b.playlistItem.mediaid),
Because `a` and `b` are not actually `JwpState` but `Partial< JwpState>` and fixing this mapping would require more, potentially regressive changes. Also compiler understand what `a` and `b` should look like, so I decided that it's not worth it :D

2023-01-02 15:23 UTC, nandy-andy commented on spec/spec-utils/html-element.stub.ts
> -// @TODO: remove if not needed
Not yet on master/dev but soon I hope ;)

2023-01-02 15:27 UTC, dmnsobczak commented on src/core/services/templates-registry/template-registry.ts
> +			// @ts-ignore "this context fix"
I think there is a bug in TypeScript and it don't properly understand this type creation:
`export type TemplateDependency<T = any> = Parameters<Container['bind']>[0];`
This results in a TS error that I don't know how to solve :< I'll try to get rid of this `@ts-ignore` later 🤞

2023-01-03 07:51 UTC, dmnsobczak commented on spec/spec-utils/html-element.stub.ts
> -// @TODO: remove if not needed
Ok! Unit tests won't pass in that case so I will restore it during this branch merge to master :) In this universe this file is redundant 🤔

2023-01-03 08:09 UTC, dmnsobczak commented on src/core/services/templates-registry/template-registry.ts
> +			// @ts-ignore "this context fix"
I don't know how :< I'll leave it for the future 🤞

2023-01-03 08:20 UTC, nandy-andy approved these changes

2023-01-18 11:47 UTC, lnawrotek approved these changes

2023-01-18 11:51 UTC, merged