ADEN-12519 Get ICBM config per country
Wikia/ad-engine pull request #1671
Opened 2022-12-27 17:02 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/ADEN-12519

2022-12-27 17:06 UTC, szymon-nawrocki commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> +			InstantConfigSetup,
To be able to get country in `instant-config.loader.ts` from `context.get('geo.country')`  I had to:
1. call `() => bootstrapAndGetConsent()` first
2. and `InstantConfigSetup` second

@dmnsobczak is that okay, that we won't be calling these 2 parts in parallel?
Or do you have a better idea of how we can handle it in a better way?

2022-12-28 07:14 UTC, dmnsobczak commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> +			InstantConfigSetup,
It will work, but it will have a negative impact on performance. `InstantConfigSetup` do two things:
* calls ICBM and load flags
* preload libraries: https://github.com/Wikia/ad-engine/blob/7b8428958cefafe020b41d16e83aaf5a36b733d1/src/platforms/shared/utils/instant-config-setup.ts#L33

When modal is rendered and visible we cannot proceed with AdEngine startup without the consent, but we can load big files in this "free time" when browser is not loading anything. By this change we won't have this free time :< In order to keep it we can:
* split and rearrange `InstantConfigSetup`
* emit a `GeoCookieReady` event that blocks `InstantConfigSetup` logic

2022-12-28 07:15 UTC, dmnsobczak commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> +			InstantConfigSetup,
While working on this we should also get rid of duplicated `setGeoData()` call:
https://github.com/Wikia/ad-engine/blob/dev/src/platforms/shared/bootstrap.ts#L7

This can be done now or in a separate ticket 🤔

2022-12-28 11:30 UTC, szymon-nawrocki commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> +			InstantConfigSetup,
> While working on this we should also get rid of duplicated setGeoData() call:

There is already ticket for that:
https://fandom.atlassian.net/browse/ADEN-12577

2022-12-28 12:07 UTC, szymon-nawrocki commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> +			() => utils.geoService.setUpGeoData(),
@dmnsobczak What do you think about this solution?

2022-12-28 12:26 UTC, szymon-nawrocki commented
Another question that came up during getting getting around InstantConfig code.

Maybe it will be worth to add GPT setup to `preloadLibraries()`?
https://github.com/Wikia/ad-engine/blob/53ec44ac0b164fa5ea25da16400d2bb80a03d358/src/platforms/shared/utils/instant-config-setup.ts#L33

CC: @nandy-andy @dmnsobczak

2022-12-28 14:56 UTC, szymon-nawrocki commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> +			() => BaseContextSetup.setUpInitialContext(basicContext),
@dmnsobczak What do you think about this solution?

2022-12-29 11:42 UTC, dmnsobczak requested changes

2022-12-29 11:42 UTC, dmnsobczak commented on src/core/services/index.ts
> +export * from './tracking-opt-in-wrapper';
<3

2022-12-29 11:42 UTC, dmnsobczak commented on src/core/services/bootstrap.ts
> +	static setUpContextAndGeo(basicContext: any, isMobile = false): void {
We used to use `setupXXX` instead of `setUpXXX` :D :grammar_nazi:

2022-12-29 11:42 UTC, dmnsobczak commented on src/core/services/bootstrap.ts
> +	static async getConsent(): Promise<void> {
`setupConsent` sounds better since this method doesn't return anything

2022-12-29 11:42 UTC, dmnsobczak commented on src/platforms/bingebot/bingebot-platform.ts
> +			parallel(InstantConfigSetup, () => Bootstrap.getConsent()),
```suggestion
			parallel(InstantConfigSetup, Bootstrap.setupConsent),
```

2022-12-29 11:42 UTC, dmnsobczak commented on src/platforms/bingebot/bingebot-platform.ts
> +			() => Bootstrap.setUpContextAndGeo(basicContext),
```suggestion
			Bootstrap.setupContextAndGeo(basicContext),
```

2022-12-29 11:42 UTC, dmnsobczak commented on src/core/services/bootstrap.ts
> +	static async getConsent(): Promise<void> {
```suggestion
	static async setupConsent(): Promise<void> {
```

2022-12-29 11:42 UTC, dmnsobczak commented on src/core/services/bootstrap.ts
> +	}
```suggestion
	static setupContextAndGeo(basicContext: any, isMobile = false): void {
		return () => {
			context.extend(basicContext);
			context.set('state.isMobile', isMobile);
			utils.geoService.setUpGeoData();
		};
	}
```

2022-12-29 11:42 UTC, dmnsobczak commented on src/core/utils/geo.ts
> +import { ensureGeoCookie } from '../../platforms/shared';
Core shouldn't import from `platforms/shared`. Please move `ensureGeoCookie` to utils, geo.ts file or Bootstrap class :)

2022-12-29 11:42 UTC, dmnsobczak commented on src/platforms/comicvine/comicvine-platform.ts
> +			() => Bootstrap.setUpContextAndGeo(basicContext),
ditto

2022-12-29 11:42 UTC, dmnsobczak commented on src/platforms/comicvine/comicvine-platform.ts
> +			() => Bootstrap.getConsent(),
ditto

2022-12-29 12:00 UTC, nandy-andy commented on src/ad-services/instant-config/instant-config.loader.ts
> +	getConfigUrl() {
Beautiful method to unit test :)

2022-12-29 14:09 UTC, szymon-nawrocki commented on src/ad-services/instant-config/instant-config.loader.ts
> +	getConfigUrl() {
done ✅

2022-12-29 14:38 UTC, dmnsobczak commented on src/platforms/comicvine/comicvine-platform.ts
> +			() => Bootstrap.setupConsent(),
```suggestion
			Bootstrap.setupConsent,
```

2022-12-29 14:38 UTC, dmnsobczak commented on src/platforms/gamefaqs/gamefaqs-platform.ts
> +			() => Bootstrap.setupConsent(),
```suggestion
			Bootstrap.setupConsent,
```

2022-12-29 14:38 UTC, dmnsobczak commented on src/platforms/gamespot/gamespot-platform.ts
> +			() => Bootstrap.setupConsent(),
```suggestion
			Bootstrap.setupConsent,
```

2022-12-29 14:39 UTC, dmnsobczak commented on src/platforms/giantbomb/giantbomb-platform.ts
> +			() => Bootstrap.setupConsent(),
```suggestion
			Bootstrap.setupConsent,
```

2022-12-29 14:39 UTC, dmnsobczak commented on src/platforms/metacritic/metacritic-platform.ts
> +			() => Bootstrap.setupConsent(),
```suggestion
			Bootstrap.setupConsent,
```

2022-12-29 14:39 UTC, dmnsobczak commented on src/platforms/tvguide/tvguide-platform.ts
> +			() => Bootstrap.setupConsent(),
```suggestion
			Bootstrap.setupConsent,
```

2022-12-29 14:39 UTC, dmnsobczak approved these changes

2023-01-10 10:36 UTC, domjanik submitted a review, later dismissed

2023-05-25 15:51 UTC, closed without merging