ADEN-12232 - Added CrossDomain storage to Identity Service
Wikia/ad-engine pull request #1676
Opened 2022-12-30 08:19 UTC by domjanik

2022-12-30 13:35 UTC, nandy-andy commented on src/ad-services/user-identity/adms-identity-repository/index.ts
> +	storage = new UniversalStorage();
We could pass it in the constructor to make unit testing it easier :)

2022-12-30 13:48 UTC, nandy-andy commented on src/ad-services/user-identity/global-identity-repository/global-identity-provider/index.ts
> +} from '@fandom-frontend/cross-domain-storage/dist';
nit-picking: we could maybe create an alias and get rid of `/dist` 🤔

2022-12-30 13:49 UTC, nandy-andy commented on src/ad-services/user-identity/global-identity-repository/global-identity-provider/index.ts
> +		return window.location.href.includes('.fandom.com');
Consider using `window.location.host` 🤔

2022-12-30 13:56 UTC, nandy-andy commented on src/ad-services/user-identity/global-identity-repository/index.ts
> +	client = new GlobalIdentityProvider();
What do you think of renaming `client` to `identityProvider`? It's more descriptive as `client` can mean many different things 🤔

2022-12-30 13:57 UTC, nandy-andy submitted a review, later dismissed

2023-01-04 06:29 UTC, domjanik commented on src/ad-services/user-identity/global-identity-repository/global-identity-provider/index.ts
> +} from '@fandom-frontend/cross-domain-storage/dist';
I've tried to do that, however I've failed - It seems that there are some problems with fandom-frontend configuration. When I've checked in their repo, all of their projects that are loaded as dependencies seems to be loaded with /dist :/ If you know about package without that in fandom-frontend please, let me know. Otherwise I would leave it as it is for now.

2023-01-04 13:22 UTC, jakubbanas requested changes
Looks good overall, but I believe `package-lock` should not be removed.

2023-01-05 07:25 UTC, domjanik commented
> Looks good overall, but I believe `package-lock` should not be removed.

Fixed

2023-01-05 07:28 UTC, jakubbanas approved these changes

2023-03-08 09:53 UTC, closed without merging