ADEN-12567 Map N&R targeting keys
Wikia/ad-engine pull request #1716
Opened 2023-01-24 11:33 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/ADEN-12567

2023-01-24 12:18 UTC, preludek requested changes
Left some comments. Also the tickets AC calls for unit tests to be added.

2023-01-24 12:18 UTC, preludek commented on src/platforms/news-and-ratings/shared/setup/context/targeting/phoenix-sites-and-gamefaqs-targeting.setup.ts
> +			return JSON.parse(dataSettingsElement)?.target_params;
I'm guessing `?` is here in case JSON.parse fails. If yes, I think this will not work as intended and produce an error. I'd recommend using a try/ catch here and returning value accordingly.

2023-01-24 12:18 UTC, preludek commented on src/platforms/news-and-ratings/tvguide/setup/context/targeting/tvguide-targeting.setup.ts
> +		// TODO: Map key 'network' to 'tv' (ADEN-12567)
😞

2023-01-24 12:18 UTC, preludek commented on src/platforms/news-and-ratings/comicvine/comicvine-platform.ts
> +			PhoenixSitesAndGamefaqsTargetingSetup,
Is this a part of comicvine platform setup? 🤔

2023-01-24 12:18 UTC, preludek commented on src/platforms/news-and-ratings/gamefaqs/gamefaqs-platform.ts
> +			GamefaqsTargetingSetup,
It seems like there's like two GamefaqsTargetingSetups, or at least one and a half 😄

2023-01-24 12:29 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/shared/setup/context/targeting/phoenix-sites-and-gamefaqs-targeting.setup.ts
> +export class PhoenixSitesAndGamefaqsTargetingSetup implements DiProcess {
So rename it to `GamefaqsGamespotGiantbombComicvineTargetingSetup` ? That does not look good

2023-01-24 12:31 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/shared/setup/context/targeting/phoenix-sites-and-gamefaqs-targeting.setup.ts
> +export class PhoenixSitesAndGamefaqsTargetingSetup implements DiProcess {
I'd rather rename it to `PhoenixBasedSitesAndGamefaqsTargetingSetup` or just `PhoenixBasedSitesTargetingSetup` Then we can see from the usage that Gamefaqs is using the same TargetingSetup as Phoenix based sites

2023-01-24 12:45 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/shared/setup/context/targeting/phoenix-sites-and-gamefaqs-targeting.setup.ts
> +			return JSON.parse(dataSettingsElement)?.target_params;
Good catch!

2023-01-24 12:50 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/comicvine/comicvine-platform.ts
> +			PhoenixSitesAndGamefaqsTargetingSetup,
yes, Comicvine is Phoenix based site

2023-01-24 12:53 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/gamefaqs/gamefaqs-platform.ts
> +			GamefaqsTargetingSetup,
I don't understand, this is one `GamefaqsTargetingSetups` that shares some of the targeting parts from:
* phoenix based sites
* all news and ratings sites

2023-01-24 13:12 UTC, preludek commented on src/platforms/news-and-ratings/shared/setup/context/targeting/phoenix-sites-and-gamefaqs-targeting.setup.ts
> +export class PhoenixSitesAndGamefaqsTargetingSetup implements DiProcess {
I'm thinking if this should be in the shared directory anyway. It's not being shared between all the n&r platforms hence I'd argue this code should be in each TargetingSetup respectively. It's not a problem bundle size-wise since we are generating a bundle based on a platform. It would be pretty straightforward which platforms use these different keys, and finally, we wouldn't have to initialize multiple targeting setups. (for example for Gamefaqs we have 3):
```
   NewsAndRatingsTargetingSetup,
   PhoenixSitesAndGamefaqsTargetingSetup,
   GamefaqsTargetingSetup,
```

2023-01-24 13:22 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/shared/setup/context/targeting/phoenix-sites-and-gamefaqs-targeting.setup.ts
> +export class PhoenixSitesAndGamefaqsTargetingSetup implements DiProcess {
`PhoenixBasedSitesTargetingSetup` is shared between 4/6 platforms so for me it shared :)
I don't want to put the exactly the same code to 4 different places  according to the DRY rule.
Plus this class will be removed, and the code will be moved to `NewsAndRatingsTargetingSetup` once Metacritic and TVGuide will implement `adtags` metadata object that contains all targeting params on their sites

2023-01-26 10:14 UTC, preludek approved these changes

2023-01-26 14:54 UTC, preludek approved these changes

2023-01-26 15:45 UTC, merged