ADEN-12721 Decode adtags on N&R platforms
Wikia/ad-engine pull request #1731
Opened 2023-01-31 15:58 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/ADEN-12721

2023-01-31 17:13 UTC, nandy-andy commented on src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts
> +				const value = decodeURIComponent(parts[1]).replace(/\+/g, ' ');
We don't need a regular expression to replace `'+'` with `' '`, do we? Consider using just `.replace('+', ' ')` 🤔

2023-02-01 09:51 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts
> +				const value = decodeURIComponent(parts[1]).replace(/\+/g, ' ');
The value can contain multiple plus signs. The `replace` method will replace only first match

2023-02-01 09:52 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts
> +				const value = decodeURIComponent(parts[1]).replace(/\+/g, ' ');
> A string pattern will only be replaced once. To perform a global search and replace, use a regular expression with the g flag, or use [replaceAll()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) instead.

Taken from: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

2023-02-01 10:59 UTC, nandy-andy approved these changes

2023-02-01 11:05 UTC, mfarul requested changes

2023-02-01 11:05 UTC, mfarul commented on src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts
> +				const key = parts[0];
the whole forEach could be replaced with this:
`for (const [key, value] of new URLSearchParams(adTags)) { 
    adTagsObj[key] = value;
}`
or some map function

2023-02-01 11:37 UTC, szymon-nawrocki commented on src/platforms/news-and-ratings/shared/setup/context/targeting/news-and-ratings-targeting.setup.ts
> +				const key = parts[0];
Wow, thanks for the suggestion. Now this complicated splitting and mapping became much more clear one liner

2023-02-01 11:51 UTC, mfarul approved these changes

2023-02-02 11:06 UTC, merged