ADEN-12854 - [PoC] of gathering and sending data to prometheus throug…
Wikia/ad-engine pull request #1798
Opened 2023-03-02 19:36 UTC by adi-wesolowski-fandom

…h pandora service, for monitoring purpose

2023-03-15 08:16 UTC, andrzejkupczyk commented on src/platforms/shared/tracking/monitoring.ts
> +	private clickHookOnIframe(prevTriggeredId: string): void {
It seems that the first call always passes an empty string. If so, I would suggest making `prevTriggeredId` optional or giving it a default value.

2023-03-15 08:16 UTC, andrzejkupczyk commented on src/platforms/shared/setup/monitoring.setup.ts
> +		return this.isLocal() ? 'http://localhost:8080' : utils.getServicesBaseURL();
I wonder if it is possible to avoid hard coding localhost? Maybe for example `InstantConfigService` could be used for that?

2023-03-15 09:20 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/monitoring.ts
> +		}
I dont understand, what you mean by "exacly same result". Yes, result should be the same and this is the case. But in `currentElement` we dont have the same element all the time - it skip up the ladder in node tree. 

The reason for it is, I want parent element, that match the pattern described as if statement. It is because, somethimes we got iframe or div of the Ad, put deeper by googletag, but we want to catch our id, not googletag id.

2023-03-15 09:22 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/monitoring.ts
> +	private clickHookOnIframe(prevTriggeredId: string): void {
Yes, it is empty. But can be null I guess. This is a leftover from early version of PoC, and I didnt enhance it :) The reason is to get a click event for new Ad, or else we would stuck on only one click-event

2023-03-15 09:24 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/monitoring.setup.ts
> +		return this.isLocal() ? 'http://localhost:8080' : utils.getServicesBaseURL();
It is used to get the prod behaviour. But still, many link in AdEngine are hardcoded. Here I put it to be able to send data to local instance of Pandora. But I can use other query param as well. As for ICBM - I dont see oportunity to do so, because I get config from prod on my dev-box, even with "local" param. Thats why I did it this way.

2023-03-15 11:44 UTC, andrzejkupczyk commented on src/platforms/shared/tracking/monitoring.ts
> +		}
Gotcha. `Element.closest()` accepts any CSS selector. It's pretty powerful so imho it might meet your needs 🙂 

```js
const closestAdElement = element.closest('[id]:not([id*="/"])');
```

☝🏻 finds closest ancestor element having non-empty id attribute, which does not contain "/" character (or `null` if there is no such element).

https://jsfiddle.net/w03c54xj/

2023-03-15 13:02 UTC, andrzejkupczyk commented on src/platforms/shared/tracking/monitoring.ts
> +		}
Thank u!

2023-03-28 09:52 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/monitoring.setup.ts
> +		return this.isLocal() ? 'http://localhost:8080' : utils.getServicesBaseURL();
Not, port should not change, at least as I am aware

2023-03-28 09:56 UTC, andrzejkupczyk approved these changes

2023-03-30 11:40 UTC, David-Iacovone requested changes
Looks good, just a few cosmetic suggestions

2023-03-30 11:40 UTC, David-Iacovone commented on src/core/utils/logger.ts
> +export function getTimeDeltaInSeconds(): string {
I would suggest to change the return type to number, since this function aims to return seconds.

2023-03-30 11:55 UTC, adi-wesolowski-fandom commented on src/core/utils/logger.ts
> +export function getTimeDeltaInSeconds(): string {
I think I wanted to keep string as it was there before, and to keep campatibility with what it was before. But in the end, it seems to be unnecessary. Ok, I will change it. thx

2023-03-30 13:49 UTC, adi-wesolowski-fandom commented on src/core/utils/logger.ts
> +export function getTimeDeltaInSeconds(): string {
Well... actually it return seconds, but not full seconds, there is comma. Also, function return the result of the "toFixed", which force to be "string" type.

2023-03-30 14:09 UTC, David-Iacovone requested changes

2023-03-30 14:19 UTC, David-Iacovone commented on src/core/utils/outbound-traffic-restrict.ts
> +	private static DEFAULT_THRESHOLD = 2;
It seems that they still can be modified. It looks kinda wired to me to use `private` and `static` on one property, since static suggest external usage of those properties

2023-03-30 14:31 UTC, David-Iacovone submitted a review, later dismissed

2023-03-31 07:23 UTC, andrzejkupczyk submitted a review, later dismissed

2023-04-17 11:22 UTC, jakubbanas approved these changes

2023-04-17 12:13 UTC, mfarul requested changes

2023-04-17 12:16 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/monitoring.ts
> +export class Monitoring {
ok

2023-04-17 12:17 UTC, andrzejkupczyk commented on src/core/utils/outbound-traffic-restrict.ts
> +		if (threshold !== this.ALWAYS_ALLOWED_THRESHOLD) {
The name of the constant and the condition parameter imply that the threshold value cannot be larger than 250, which might cause confusion for anyone working with the code in the future. Would it be possible to consider renaming the constant and parameter to something more generic that doesn't imply a specific threshold value? This would help avoid any confusion or potential bugs in the future. Thanks for considering this suggestion!

2023-04-17 12:19 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/monitoring.setup.ts
> +	private getServiceBaseURL(): string {
It was for 2 reasons: 
- not send metric data during tests or development using local version (as it may have some errors and not show ads, etc
- - to not send data to prod pandora and therefor, do not mess with data there if something went wrong during development
- to send data to local instance of Pandora during development, and have local copy of this data

2023-04-17 12:19 UTC, andrzejkupczyk commented on src/core/utils/outbound-traffic-restrict.ts
> +		if (threshold !== this.ALWAYS_ALLOWED_THRESHOLD) {
Okay, it looks like the code I reviewed has been already outdated 🤔

2023-04-17 12:23 UTC, adi-wesolowski-fandom commented on src/core/utils/outbound-traffic-restrict.ts
> +		if (threshold !== this.ALWAYS_ALLOWED_THRESHOLD) {
I used current "outbound-traffic-restricter" from "dev", that was created and deployed with task for DW-limitation

2023-04-17 12:28 UTC, andrzejkupczyk commented on src/platforms/shared/tracking/monitoring.ts
> +		fetch(`${endpointUrl}?app=${endpointInfo.appName}&slot=${slotName}&state=${state}`);
To ensure that the parameters are properly encoded, may I suggest using the `URLSearchParams` method to encode the parameters before passing them to the fetch function? This will help avoid any issues with special characters or spaces in the parameters. Same for the `sendTimeDataToMeteringSystem` method.

2023-04-17 12:29 UTC, andrzejkupczyk approved these changes

2023-04-17 13:55 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/monitoring.setup.ts
> +	private getServiceBaseURL(): string {
it can be

2023-04-17 15:15 UTC, mfarul submitted a review, later dismissed

2023-04-17 15:15 UTC, mfarul commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> +			MetricReporterSetup,
this can be added to ucp-mobile and to other platforms as sell

2023-04-18 05:56 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> +			MetricReporterSetup,
ok, done

2023-04-18 05:57 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/monitoring.ts
> +		fetch(`${endpointUrl}?app=${endpointInfo.appName}&slot=${slotName}&state=${state}`);
I added encoding, and change building url, into one place only

2023-04-18 05:58 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/monitoring.setup.ts
> +	private getServiceBaseURL(): string {
I removed all "isLocal" references

2023-04-18 05:58 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/monitoring.ts
> +	private clickHookOnIframe(prevTriggeredId: null | string = null): void {
extracted

2023-04-18 05:58 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/monitoring.ts
> +		fetch(`${endpointUrl}?app=${endpointInfo.appName}&action=${action}&duration=${duration}`);
done - I added fetch with support for timeout (default = 2 sec)

2023-04-18 09:15 UTC, mfarul approved these changes

2023-04-20 09:41 UTC, merged