ADEN-12771 - Add new API for BlockThrough
Wikia/ad-engine pull request #1816
Opened 2023-03-07 17:38 UTC by domjanik

2023-03-08 15:11 UTC, jbienkowski-fandom requested changes

2023-03-08 15:11 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +		window.fandomContext = {
I don't like this, it breaks `WindowFandomContext`'s interface and is a source of potential bugs... I would rather extend WindowFandomContext to allow empty objects by Partial<IXYZParameters>`. Otherwise I bet otherwise sooner or later someone will use `window.fandomContext.tracking.something.nested` and it will fail

2023-03-08 15:11 UTC, jbienkowski-fandom commented on @types/fandom/index.d.ts
>  	tracking?: ITrackingParameters;
I guess `tracking` and `partners` are not optional anymore but should me marked with `Partial` as `GlobalContextService` will initialize them to empty object

2023-03-08 15:11 UTC, jbienkowski-fandom commented on @types/fandom/index.d.ts
> +	page: IPageParameters;
```suggestion
	page: Partial<IPageParameters>;
```

2023-03-09 10:56 UTC, jbienkowski-fandom requested changes

2023-03-09 10:56 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +			tracking: {} as ITrackingParameters,
```suggestion
			tracking: {},
```
should work as tracking is `Partial`, same for `partners` (and could be same for site and page as they should be `Partial` too imho)

2023-03-09 10:56 UTC, jbienkowski-fandom commented on spec/ad-services/eyeota/eyeota.spec.ts
> +			site: null,
```suggestion
			site: {},
```
and same with others, then you will not have to use `as FandomContext`

2023-03-09 10:56 UTC, jbienkowski-fandom commented on src/ad-services/eyeota/index.ts
> +	constructor(props) {
this is unnecessary imho

2023-03-09 10:56 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +			window.fandomContext[category] = {} as any;
```suggestion
			window.fandomContext[category] = {};
```
should work without `as any` after changes to WindowFandomContext types (see previous comments)

2023-03-09 10:56 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +		window.fandomContext[category] = this.merge(window.fandomContext[category], value) as any;
```suggestion
		window.fandomContext[category] = this.merge(window.fandomContext[category], value);
```
same here

2023-03-09 10:56 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +	getValue(category: GlobalContextCategories, key?: string): unknown {
this method typings' could be improved too:
```suggestion
	getValue<K extends keyof WindowFandomContext, I extends keyof WindowFandomContext[K]>(
		category: K,
		key?: I,
	): WindowFandomContext[K][I] | undefined {
```

2023-03-09 11:41 UTC, domjanik commented on src/ad-services/eyeota/index.ts
> +	constructor(props) {
This change has been introduced, because Intellij sometimes has problems with our typings. I know it is unnecessary, but it looks better in our IDE :D If you insist on removing it - I can do it :)

2023-03-09 11:48 UTC, jbienkowski-fandom commented on src/ad-services/eyeota/index.ts
> +	constructor(props) {
okay, then it is fine by me ;)

2023-03-09 12:03 UTC, jbienkowski-fandom commented on spec/ad-services/eyeota/eyeota.spec.ts
> +			page: null,
```suggestion
			page: {},
```

2023-03-09 12:05 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +			site: {} as ISiteParameters,
```suggestion
			site: {},
```

2023-03-09 12:05 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +			page: {} as IPageParameters,
```suggestion
			page: {},
```

2023-03-09 12:05 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +			partners: {} as IPartnersParameters,
```suggestion
			partners: {},
```

2023-03-09 12:10 UTC, jbienkowski-fandom approved these changes

2023-03-13 08:27 UTC, merged