ADEN-12876 | Add AppnexusAst prebid video to N&R
Wikia/ad-engine pull request #1829
Opened 2023-03-13 13:03 UTC by rafalgiemza

affected sites: Gamefaqs, Gamespot, GiantBomb, Metacritic & TVguide

2023-03-13 16:28 UTC, dmnsobczak commented on src/platforms/news-and-ratings/gamefaqs/bidders/appnexusAst.ts
> +			incontent_player: {
N&R video slot is called `video`, not `incontent_player`

2023-03-13 16:28 UTC, dmnsobczak requested changes
Notes left

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/gamefaqs/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/gamefaqs/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/gamespot/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/gamespot/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/giantbomb/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/giantbomb/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/metacritic/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/metacritic/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-13 17:16 UTC, rafalgiemza commented on src/platforms/news-and-ratings/tvguide/bidders/appnexusAst.ts
> +			incontent_player: {
```suggestion
			video: {
```

2023-03-14 12:25 UTC, nandy-andy commented on src/platforms/news-and-ratings/gamefaqs/bidders/rubicon.ts
> +			featured: {
I don't think we've got `featured` and `incontent_player` slots on N&R. There is just `video` for now AFAIK, for example: https://github.com/Wikia/ad-engine/blob/dev/src/platforms/news-and-ratings/gamefaqs/setup/context/slots/gamefaqs-slots-context.setup.ts#L290-L292

2023-03-14 12:31 UTC, nandy-andy commented on src/platforms/news-and-ratings/gamefaqs/bidders/appnexusAst.ts
> +		accountId: 7450,
I think this is not necessary as it seems like a copy from Rubicon 🤔

2023-03-14 13:22 UTC, dmnsobczak commented on src/platforms/news-and-ratings/gamefaqs/bidders/appnexusAst.ts
> +export function getAppnexusAstContext(isDesktop: boolean): object {
File name is inconsistent - we name them `appnexus-ast.ts`

2023-03-14 13:23 UTC, dmnsobczak commented on src/platforms/news-and-ratings/gamefaqs/bidders/appnexusAst.ts
> +		accountId: 7450,
Agree

2023-03-14 13:23 UTC, dmnsobczak commented on src/platforms/news-and-ratings/gamefaqs/bidders/appnexusAst.ts
> +		debugPlacementId: '5768085',
This is not needed as well

2023-03-14 13:24 UTC, dmnsobczak commented on src/platforms/news-and-ratings/gamefaqs/bidders/appnexusAst.ts
> +		slots: isDesktop ? desktopSlots : mobileSlots,
This will create a structure like this: `{ slots: slots: video: placementId } ` which is incorrect

2023-03-14 13:31 UTC, dmnsobczak commented on src/platforms/news-and-ratings/gamefaqs/bidders/rubicon.ts
> +			incontent_player: {
There is no `featured` or `incontent_player` slot on N&R

2023-03-14 13:41 UTC, dmnsobczak commented on src/platforms/news-and-ratings/gamefaqs/bidders/rubicon.ts
> +				sizeId: '201',
This is Fandom's `sizeId` and probably cannot be used on N&R. It is an integer indicating the Rubicon Project video ad format ID. If not set, will be inferred from `mediaTypes.video.context`. Also, Rubicon docs say that it is an optional parameter, so I suggest removing it.

2023-03-14 14:00 UTC, dmnsobczak submitted a review, later dismissed

2023-03-14 14:10 UTC, nandy-andy commented on src/platforms/news-and-ratings/gamefaqs/bidders/rubicon.ts
> +		featured: {
It's `video` not `featured` on N&R 😊

2023-03-14 14:16 UTC, dmnsobczak commented on src/platforms/news-and-ratings/gamefaqs/bidders/rubicon.ts
> +		featured: {
Typo, done :D

2023-03-14 14:17 UTC, dmnsobczak submitted a review, later dismissed

2023-03-14 14:19 UTC, nandy-andy approved these changes

2023-03-14 15:20 UTC, dmnsobczak approved these changes

2023-03-14 16:11 UTC, rafalgiemza reviewed
+1 :)

2023-03-15 09:11 UTC, merged