ADEN-12905 - Added AgeGate handling
Wikia/ad-engine pull request #1853
Opened 2023-03-22 09:52 UTC by domjanik

In this PR I've refactored a bit our approach to detecting COPPA subjects. Currently, we were just reading wiki.targeting.directedAtChildren property from context. After introducing AgeGate ( and maybe over_18 in the future ) this approach is not enough, as it can't be easily extended. I've created a new method - isCoppaSubject, which checks LocalStorage for age_gate object, and if there is such object - it will parse it. If there is not - it will return wiki.targeting.directedAtChildren as it used to.

2023-03-22 10:36 UTC, szymon-nawrocki commented on src/core/utils/is-coppa-subject.ts
> +				? !parsedAgeGateResult.adult
If `adult` property is not available it means that someone clicked "I am a kid". In this case the code should return true (but currently it will throw an error)

2023-03-22 10:42 UTC, szymon-nawrocki commented on src/core/utils/is-coppa-subject.ts
> +				? !parsedAgeGateResult.adult
Okay it won't throw an error. It will return undefined, and `!undefined = true` 🙈

2023-03-22 10:48 UTC, szymon-nawrocki approved these changes

2023-03-30 09:54 UTC, jbienkowski-fandom requested changes

2023-03-30 09:54 UTC, jbienkowski-fandom commented on src/core/utils/is-coppa-subject.ts
> +		const ageGateResult = localStorage.getItem('age_gate');
In the meantime, we have changed the storage of AgeGate result from localStorage to cookie: https://github.com/Wikia/identity-engine/pull/50

Moreover, we could use the same feature flag as in the IdentityEngine which is `icAgeGate` in this util function (if the flag is set to false, just take the value from `wiki.targeting.directedAtChilden` context).

2023-03-30 12:06 UTC, jbienkowski-fandom commented on src/core/utils/is-coppa-subject.ts
> +	} else {
else is redundant

2023-03-30 12:08 UTC, jbienkowski-fandom commented on src/core/utils/is-coppa-subject.ts
> +				return dialogShown ? adult === '0' : context.get('wiki.targeting.directedAtChildren');
```suggestion
				return dialogShown === '1' ? adult === '0' : context.get('wiki.targeting.directedAtChildren');
```

2023-03-30 12:09 UTC, jbienkowski-fandom commented on src/core/utils/is-coppa-subject.ts
> +			}
if there is no cookie we should return something as well

2023-03-30 12:23 UTC, jbienkowski-fandom approved these changes

2023-04-13 09:24 UTC, merged