ADEN-12863 - add observer for galleries, to rotate ads together with …
Wikia/ad-engine pull request #1855
Opened 2023-03-22 14:21 UTC by adi-wesolowski-fandom

…gallery content + fix destroy-event name

2023-03-22 14:54 UTC, David-Iacovone approved these changes

2023-03-22 14:54 UTC, David-Iacovone commented on src/core/models/ad-slot.ts
> +	static DESTROY_EVENT = 'slotDestroy';
Is this meant to replace 'slotDestroyed' ?

2023-03-23 07:09 UTC, andrzejkupczyk commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		communicationService.onSlotEvent(AdSlot.DESTROYED_EVENT, ({ slot }) => {
```suggestion
		communicationService.onSlotEvent(AdSlot.DESTROY_EVENT, ({ slot }) => {
```

2023-03-23 07:09 UTC, andrzejkupczyk commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		if (!this.currentUrl) {
Out of pure curiosity, when will it be true? According to [ln#14](https://github.com/Wikia/ad-engine/pull/1855/files#diff-879ef870fd8aa9d7993c5f2948d46ccc520f0f7132d9ddb097a4dfbf2198a968R14) `currentUrl` should always be set, shouldn't it? 🤔

2023-03-23 07:19 UTC, andrzejkupczyk commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
Have you considered keeping consistent file naming with the `.setup` suffix?

2023-03-23 07:28 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		communicationService.onSlotEvent(AdSlot.DESTROYED_EVENT, ({ slot }) => {
No. I divided DESTROY and DESTROYED for a reason. Here, should be DESTROYED, because we want to create new slot _after_ destroying is complete, not before or there will be collision in GPT.

2023-03-23 07:32 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		if (!this.currentUrl) {
Should. I copyied the basic idea from SeamlessObserver, and they have it there also. And I think, its ok to be here. I believe, there could be (very rare) situation, where location.href could give as "null". But I cant tell and image, how it could happen in this case. So maybe you are right and this can be deleted.

2023-03-23 07:34 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
I can rename but I believe this is not a classic setup, dont affect on the AdEngine in the matter of lib behaviour. Its more like domain exception and observer itself. Just like TvGuidePageChangeAdsObserver is included in the TVguide domain.

2023-03-23 07:59 UTC, andrzejkupczyk commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		communicationService.onSlotEvent(AdSlot.DESTROYED_EVENT, ({ slot }) => {
Oh, my mistake - I thought this is the same event.

2023-03-23 08:28 UTC, andrzejkupczyk commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		if (!this.currentUrl) {
Well, if the `location.href` could be null (according to docs [it's always a string](https://developer.mozilla.org/en-US/docs/Web/API/Location/href#value)), then there are probably more problems with this code.

Imagine what would happen if:

this.currentUrl == null
location.href == null

In ☝🏻 case, the `this.currentUrl` will get a null value either way.

2023-03-23 08:45 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		if (!this.currentUrl) {
Yes indeed, there will be null. Maybe thats why we got if ;) 

But ok, sure, I will remove it then.

2023-03-23 08:46 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
This is a place where all observers are put in other platforms directories so I followed this pattern. 
I will add "setup" suffix for you ;)

2023-03-23 08:56 UTC, dmnsobczak commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
Filenames was unified in this ticket: https://github.com/Wikia/ad-engine/pull/1814
Please match this convention and avoid conflict while merging :D

2023-03-23 09:03 UTC, dmnsobczak commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		communicationService.onSlotEvent(AdSlot.DESTROYED_EVENT, ({ slot }) => {
I guess the problem here was with the events order. Communication service handles callbacks in the order they were registered - that's why this callback is executed before the one in the `gpt-provider` - second one waits for GPT load. You can solve this by postponing this callback register too, for example by wrapping it with this:
`communicationService.on(eventsRepository.AD_ENGINE_STACK_START, () => {
    communicationService.onSlotEvent(AdSlot.DESTROY_EVENT, ({ slot }) => {});
});`
Then you don't need to duplicate events and change their logic 🤔

2023-03-23 09:04 UTC, andrzejkupczyk submitted a review, later dismissed

2023-03-23 09:08 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		communicationService.onSlotEvent(AdSlot.DESTROYED_EVENT, ({ slot }) => {
I did not change logic for existing events, I just rename it to be more relevant to what's going on there (action to mark slot TO BE destroyed on the event (already) "Destroyed", seems weird to me. So I rename to, to future tense. 

And I used old name in Past tense, to message thing that happened: slots has been destroyed. And then I can create a new one - just like we discuss on slack :) 

Making this listener inside listener does not seems to be clear (I mean, it might not be in the future)

2023-03-23 09:23 UTC, andrzejkupczyk commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		communicationService.onSlotEvent(AdSlot.DESTROYED_EVENT, ({ slot }) => {
Introducing a new event can provide more flexibility and improve readability, so if it's not an invalid approach, I'll stick with it.

2023-03-27 11:40 UTC, David-Iacovone requested changes
Generally, it looks good. I would just consider these few minor tweaks before merging

2023-03-27 11:40 UTC, David-Iacovone commented on src/core/models/ad-slot.ts
>  	static DESTROYED_EVENT = 'slotDestroyed';
Is this event still in use?

2023-03-27 11:40 UTC, David-Iacovone commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.setup.ts
> +	private handleMutation() {
I would add a return type here just to keep it clear

2023-03-27 13:19 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.setup.ts
> +	private handleMutation() {
ok, done

2023-03-27 13:22 UTC, David-Iacovone approved these changes

2023-03-28 08:50 UTC, andrzejkupczyk approved these changes

2023-03-28 16:18 UTC, Jorewin submitted a review, later dismissed
One question, but other than that it looks good to me.

2023-03-28 16:18 UTC, Jorewin commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.setup.ts
> +		if (!this.slotsNamesToHandle.includes(slot.getSlotName())) {
Is this still necessary if the handler is subscribed to the `AdSlot.DESTROYED_EVENT` on `slotNameToHandle` slot? I don't see a possibility of it running with a slot outside of `slotNamesToHandle` list.

2023-03-29 06:10 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.setup.ts
> +		if (!this.slotsNamesToHandle.includes(slot.getSlotName())) {
It may not. It was done, because we didnt wanted to handle other on "destroyed" event. But calling it in onSlotEvent was simpler. I will check if we can remove it safely and do so

2023-03-29 06:55 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		const observer = new MutationObserver(() => this.handleMutation());
this change causing an error on "forEach" in "handleMutation". Propably on "this.slotNamesToHandle" could not see it. So I leave it as it is.

2023-03-29 06:55 UTC, adi-wesolowski-fandom commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.setup.ts
> +		if (!this.slotsNamesToHandle.includes(slot.getSlotName())) {
Ok, removed

2023-03-29 07:05 UTC, andrzejkupczyk commented on src/platforms/news-and-ratings/metacritic/setup/page-observers/metacritic-page-change-gallery-observer.ts
> +		const observer = new MutationObserver(() => this.handleMutation());
Oh, this is strange 🤔  I'm sorry for the trouble! 🙇🏻

2023-03-29 08:58 UTC, andrzejkupczyk approved these changes

2023-03-29 09:12 UTC, merged