ADEN-12988 Fix UAP glitch on mobile Safari
Wikia/ad-engine pull request #1869
Opened 2023-03-31 12:12 UTC by nandy-andy

2023-04-03 09:07 UTC, nandy-andy commented on src/platforms/ucp-mobile/templates/handlers/slot/mobile-slot-size-impact-to-resolved-handler.ts
> +export class MobileSlotSizeImpactToResolvedHandler implements TemplateStateHandler {
I thought of just extending `SlotSizeImpactToResolvedHandler` here instead of copy&pasting most of the code but after second thoughts I decided not to do it. Inheritance here could bring more pain if we'd have decided to change anything for desktop in `SlotSizeImpactToResolvedHandler` we'd need to make sure it behaves properly on mobile.

2023-04-03 10:24 UTC, dmnsobczak requested changes
Something doesn't seems right. I would try more brave changes with removing mobile impact image from the configuration if UAP is in mobile mode.
But, this can be done in the follow up if we won't split the handlers logic to a different files. RxJS allows many way to do this in the same, conditional pipe without losing a readability. We spent lot of time to unify UAP logic, make it really universal and get rid of branches, alternative handlers for this, additional steps for that or hacked logic there. If you want, I can prepare a commit with my proposition, but I need your help with testing it 🤔

2023-04-03 10:24 UTC, dmnsobczak commented on src/platforms/ucp-mobile/templates/handlers/slot/mobile-slot-size-impact-to-resolved-handler.ts
> +					this.manager.setImpactImage();
If I remember correctly this case is required only for UAP going back to impact, for example after clicking `Replay` on desktop. On mobile though there is no different image for impact, because impact is a video with 100% width and thumbnail below that handles the placeholder role when video still loads, so there is just resolved image added to the creative.
Creative template suggest it differently: https://github.com/Wikia/dfp-creative-templates/blob/master/uap-hivi.html
But actually Adops don't add mobile impact images: 
https://admanager.google.com/5441#creatives/creative/detail/line_item_id=4973088146&creative_id=138261896621
I would go a little bit further a get rid of impact image for mobile UAP. This could be the value required for conditional logic in UAP 🤔

2023-04-03 10:30 UTC, nandy-andy commented on src/platforms/ucp-mobile/templates/handlers/slot/mobile-slot-size-impact-to-resolved-handler.ts
> +export class MobileSlotSizeImpactToResolvedHandler implements TemplateStateHandler {
I couldn't reproduce it on f2.

2023-04-03 10:34 UTC, nandy-andy commented
> If you want, I can prepare a commit with my proposition, but I need your help with testing it 🤔
Be my guest and implement changes you're thinking about. You can test it on your local machine with Safari mobile emulation. The only downside is that `?adengine_version=local` does not work and once you have changes you think will work you need to push them to s3 and then use proper `?adengine_version`

2023-04-03 12:43 UTC, dmnsobczak submitted a review, later dismissed

2023-04-04 06:48 UTC, dmnsobczak approved these changes

2023-04-04 06:48 UTC, dmnsobczak commented on src/platforms/shared/templates/handlers/slot/slot-size-impact-with-placeholder-handler.ts
> +			this.domListener.scroll$
Done!

2023-04-04 06:56 UTC, merged