Aden 12962
Wikia/ad-engine pull request #1872
Opened 2023-04-03 12:03 UTC by adi-wesolowski-fandom

2023-04-04 12:49 UTC, jakinluk commented on src/core/utils/dw-traffic-aggregator.ts
> +	public push(track: string, url: string, element: DataWarehouseParams): void {
what about reducing parameter no to 
`(url: string, element: DataWarehouseParams)`
 since there must be exactly one queue per URL exposing a queue name through the interface may cause misuse.
In other words I think a queue name extraction from URL is a responsibility of this class

2023-04-04 13:10 UTC, jakinluk commented on src/core/utils/dw-traffic-aggregator.ts
> +export const dwTrafficAggregator = new DwTrafficAggregator();
for consistency, we can use dependency injection (@Injectable())

2023-04-04 13:14 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/tracking-urls.ts
> +			threshold: true,
yes, we can do that. I wasnt sure about this names, and tried to avoid camelcase names. Maybe change "config" to "allowed", and then change "threshold" to "sampling", leaving "aggregation" as is?

2023-04-04 13:15 UTC, adi-wesolowski-fandom commented on src/core/utils/dw-traffic-aggregator.ts
> +	public push(track: string, url: string, element: DataWarehouseParams): void {
We can try to reduce, but I dont agree that this responsibility should be put here, it break solid "s" rule - too much would be inserted here. And also, some other parts of library may also use it now, or in the near future (eg. monitoring task)

2023-04-04 13:16 UTC, adi-wesolowski-fandom commented on src/core/utils/dw-traffic-aggregator.ts
> +	public push(track: string, url: string, element: DataWarehouseParams): void {
I'll try to reduce no of params thou

2023-04-04 15:42 UTC, jakinluk commented on src/core/utils/dw-traffic-aggregator.ts
> +	public push(track: string, url: string, element: DataWarehouseParams): void {
I disagree that with my suggestion we break SRP. But we indeed break encapsulation by allowing the external consumers to affect the aggregation mechanism. Determining dictionary keys values internal implementation details of DwTrafficAggregator.

2023-04-04 15:49 UTC, jakinluk commented on src/core/utils/dw-traffic-aggregator.ts
> +export const dwTrafficAggregator = new DwTrafficAggregator();
You are right.
However, utils might not be the best place for that class. DwTrafficAggregator name and DataWarehouseParams type make this class specific to aggregate DW-related traffic. Can we keep it next to DataWarehouse where it is used?

2023-04-05 06:44 UTC, adi-wesolowski-fandom commented on src/core/utils/dw-traffic-aggregator.ts
> +	public push(track: string, url: string, element: DataWarehouseParams): void {
I stand by my opinion, this would affect of single responsibility of this class.... but!, I have solution that (i hope) will satisfy both of us. See now, after my last commits - now there is now two params and no messing with srp - now there is passing full TrackingUrl object, that include all data and nothing will go messy - and this also should force, to be less prone to errors

2023-04-05 06:44 UTC, adi-wesolowski-fandom commented on src/core/utils/dw-traffic-aggregator.ts
> +export const dwTrafficAggregator = new DwTrafficAggregator();
I moved aggregator class closer to data-warehouse

2023-04-05 07:48 UTC, jakinluk approved these changes

2023-04-06 13:44 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +				utils.logger(`DW - Track Aggregated Success`, { url, params });
i used the same call as it is in the "data-warehouse", with just some changes: use fetch instead of http-xml-thing and fixed param in logger to "aggregated", instead of event, which IMO is unnecessary. But sure, I will check it

2023-04-11 11:12 UTC, mfarul requested changes

2023-04-11 11:12 UTC, mfarul commented on src/platforms/shared/tracking/data-warehouse.ts
> +			dwTrafficAggregator.push(trackingURL, params);
shouldn't we return from here if the aggregator will be also responsible for sending the event

2023-04-11 11:12 UTC, mfarul commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +class DwTrafficAggregator {
Unit test is missing

2023-04-11 11:12 UTC, mfarul commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +		this.queue[track.name]?.params?.forEach((options) => paramsAggregated.push(options));
shouldn't we mark each parameters list per event so that backend will be able to deduce where the next event is starting?

2023-04-11 11:12 UTC, mfarul commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +		this.queue[track.name].params.push(element);
what about 2 events with the same name? for example impression for slot?

2023-04-11 11:15 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse.ts
> +			dwTrafficAggregator.push(trackingURL, params);
yes, we should. I want to place a `return` here, when DW separation will be ready. Until that moment, putting `return` here will cause losing data, as it will be pushed only to new endpoints, which is not parsing yet.

2023-04-11 11:16 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +class DwTrafficAggregator {
I will add

2023-04-11 11:19 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +		this.queue[track.name]?.params?.forEach((options) => paramsAggregated.push(options));
our (my) observation (mentioned in task) made me think that they are often single or only double, and quite distant from each other in time, and it was also hard for me to decide how best to combine them (combine by event-type, like `requested` or by slot name like `top-leaderboard`?). 

This approach seems to be way more efficient to achieve what we want: cost reduction.

2023-04-11 11:34 UTC, mfarul approved these changes

2023-04-11 11:34 UTC, mfarul commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +		this.queue[track.name]?.params?.forEach((options) => paramsAggregated.push(options));
ok, so the queue is actually not aggregating all events, but it is a map of tracks that will be aggregated. I would change the field name to make it more clear, f.e. trackQueue

2023-04-11 11:34 UTC, mfarul commented on src/platforms/shared/tracking/data-warehouse.ts
> +			dwTrafficAggregator.push(trackingURL, params);
pls add a comment to indicate the code is incomplete

2023-04-11 11:34 UTC, mfarul commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +		this.queue[track.name].params.push(element);
ok, so my thinking was from a misunderstanding of the queue field purpose
we might change its name to indicate that it only aggregates events of the same type (track)

2023-04-12 08:03 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +				utils.logger(`DW - Track Aggregated Success`, { url, params });
Of course, it can play the role of logGroup but from the source code, I see the convention is the log group is a string without whitespaces to be easily enabled via query params.

2023-04-12 08:07 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +	private readonly AGGREGATION_LIMIT_PER_TRACK = 5;
we could

2023-04-12 10:55 UTC, mfarul approved these changes

2023-04-17 12:45 UTC, jakinluk approved these changes

2023-04-20 12:26 UTC, merged