ADEN-13013 extend tracking data aggregation with gzip compression
Wikia/ad-engine pull request #1884
Opened 2023-04-13 10:25 UTC by jakinluk

2023-04-13 12:48 UTC, adi-wesolowski-fandom requested changes

2023-04-13 12:48 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +	private readonly SEND_DATA_INTERVAL = 10000;
pls, do not change this. 10 sec is very long. User can close page-tab sooner, and data will be lost. Ads load much quicker and we want to send all data, including requesting and success of receiving it. 

So IMO, here should be time which is half of the average time when ads being loaded to the browser, and it is around 1 second, as I measure it

2023-04-13 12:48 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +export interface DataCompressor {
I am not sure, this definition should be here, in aggregator. Looks like very different responsibility. Aggregation can be done without compression, and IMO should be treated like a module, not functional part of aggregator (even we want to use it only here - but only here for now - later on compression can be implemented somewhere else).

I suggest to create new file for interface and type above, aside of aggregator.ts and gzip-compressor.ts

2023-04-13 12:48 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +			utils.logger('adengine_debug', 'DwTrafficAggregator', 'Compression enabled', {
this key is to general. Make it more precise, like "aggregation-compression"

2023-04-13 13:02 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +	private readonly SEND_DATA_INTERVAL = 10000;
I planned to remove those changes. I increased them only for test purposes. However, you mentioned subscribing to _visibilitychange_ would prevent data loss.

2023-04-13 13:20 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +export interface DataCompressor {
Since DwTrafficAggregator is currently responsible for sending aggregated data (if these two things are separated we can talk about running compression outside of DwTrafficAggregator) compression must happen as well in the DwTrafficAggregator. Naturally, the compression module is injected as a dependency into DwTrafficAggregator. But since the compression module is only meant to fit DwTrafficAggregator needs, it's DwTrafficAggregator the owner of that interface. I followed here the Inversion of Control principle. And I would keep that interface here to underline the fact interface is owned by DwTrafficAggregator

2023-04-13 13:46 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/gzip-compressor.ts
> +				'Compression not supported, returning uncompressed data instead.',
I proposed something in the middle

2023-04-13 13:46 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +export interface DataCompressor {
No, I disagree. As you mentioned, Aggregator class is reponsible for aggregation and sending data, not to compress. Is different task. And as I mentioned, this compression can be in future used in other classes, eg monitoring. 
So it is natural, this should be separated, and moved to separate file, where all of things related to "compression" should be placed. 
Aggregator can own this, but its not its responsibility, to compress, only to aggregate. Even sending data is in fact a little to much for this class to do. Compression is definitely too much. 
I understand you followed to Inversion of Control, but still, "compression" placed here break single-reponsibility. 

Look at it that way: there more than one reason to change this class: change algorithm of how we aggregate data, and change comporession algorithm. Just like Uncle Bob said "Gather together the things that change for the same reasons. Separate those things that change for different reasons."
(https://blog.cleancoder.com/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html)

Other example: when we would like to use compression in monitoring mechanism, we will be forced to implement aggregator, to get to this interface. And this would be so much confusing. 

"Inversion of Control" principle would be still here present, even if you moved this "compression" interfaces and responsibility out of this class. They will still be imported and used here.

2023-04-13 13:48 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +				this.sendRequest(dwTrackingUrlV2 + result.contentEncoding || '', result.compressed);
I think (maybe I am wrong), every call, including query-params would be placed separately. No need to create new endpoint IMO. 

Did you asked them, we could use query-param to determine we send compressed data or not?

2023-04-13 13:59 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/gzip-compressor.ts
> +			if (done) {
Before I start changing can you please first try your idea to see if it really looks better? 
If you want me to avoid disabling eslint rule I can propose something like that:
```
let finished;
while (!finished) {
	const { done, value } = await reader.read();
	if (!done) {
		chunks.push(value);
	}
	finished = done;
}
```
is your request something more than a matter of taste?

2023-04-13 14:14 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/gzip-compressor.ts
> +			if (done) {
it was an idea. Yes, this chunk.push part could be problematic and this does not look good either in this way. First version was better; 

I just wonder, if we could push empty value or null? To be something like this: 
`chunks.push(done ? value : null);`

```suggestion
let done, value;
while (!done) {
        { done, value } = await reader.read();
	chunks.push(done ? value : null);
}
```

If it cannot be done, then leave as it was at the first place

2023-04-13 14:15 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +			utils.logger('adengine_debug', 'DwTrafficAggregator', 'Compression enabled', {
Do as you want. I'd like just to keep description part in browser console as short as possible, to be easily to read, like "AdSlot" logs etc

2023-04-13 14:16 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +				this.sendRequest(dwTrackingUrlV2 + result.contentEncoding || '', result.compressed);
Ok, if you insist, leave it as is.

2023-04-13 14:25 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +export interface DataCompressor {
I am not going to argue more about that and won't change my mind. Since as you said this class should not in the first place perform sending and should be only responsible for aggregation extracting interface outside does not change anything about the responsibility of DwTrafficAggregator, it would be just an irrelevant move.

2023-04-13 14:36 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/gzip-compressor.ts
> +			!!(window as unknown as any).CompressionStream && !!window.TextEncoder;
I don't like putting any logic into a constructor since then I would need to add try-catch there as well. But I will make it to be calculated only once.

2023-04-13 16:26 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/gzip-compressor.ts
> +			!!(window as unknown as any).CompressionStream && !!window.TextEncoder;
Your suggestions are valid and would prevent any unexpected errors but since every logic might be changed in the future and become more complicated I would prefer to keep it outside the constructor.

2023-04-13 16:40 UTC, jakinluk commented on src/platforms/shared/tracking/data-warehouse-utils/dw-traffic-aggregator.ts
> +export interface DataCompressor {
Let's move the discussion outside and come back here with conclusions

2023-05-08 10:06 UTC, andrzejkupczyk approved these changes

2023-05-08 11:06 UTC, jakinluk commented on src/core/utils/get-global.ts
> +	return undefined;
good point. I will do that

2023-05-08 13:01 UTC, adi-wesolowski-fandom approved these changes

2023-05-08 13:01 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse-utils/dw-aggregated-data-sender.ts
> +export type Compressed = {
👍

2023-05-11 09:07 UTC, andrzejkupczyk approved these changes

2023-05-15 12:47 UTC, merged