ADEN-13228 Publisher Server-Side Configuration on Prebid.js
Wikia/ad-engine pull request #1958
Opened 2023-05-30 08:27 UTC by preludek

2023-05-31 09:39 UTC, lnawrotek submitted a review, later dismissed

2023-07-04 09:21 UTC, dmnsobczak commented on src/platforms/ucp-desktop/setup/context/prebid/ucp-desktop-prebid-config.setup.ts
> +		context.set('bidders.prebid.mgnipbs', getMagniteContext());
Technically `mgnipbs` should be after `medianet` xD

2023-07-04 09:22 UTC, dmnsobczak approved these changes

2023-07-04 09:53 UTC, preludek commented on src/platforms/ucp-desktop/setup/context/prebid/ucp-desktop-prebid-config.setup.ts
> +		context.set('bidders.prebid.mgnipbs', getMagniteContext());
you win this time

2023-07-04 09:57 UTC, dmnsobczak approved these changes

2023-08-08 14:12 UTC, lnawrotek commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +				position: 'atf',
I'm not sure. @kwfandom could you help us?

2023-08-09 05:49 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +				position: 'atf',
Do we need it? :D

2023-08-09 05:50 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +			floor_adhesion: {
Floor Adhesion is not desktop slot

2023-08-09 05:51 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +			incontent_boxad: {
```suggestion
			incontent_boxad_1: {
```

2023-08-09 05:51 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +				sizes: [[300, 250]],
Im not in the topic, but why only that size?

2023-08-09 05:51 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +					loc: ['top'],
im not so sure

2023-08-09 05:52 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +				position: 'atf',
do we need it?

2023-08-09 05:52 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +				targeting: {
im not so sure

2023-08-09 05:52 UTC, kwfandom commented on src/platforms/ucp-mobile/bidders/prebid/magnite.ts
> +					loc: ['top'],
im not so sure

2023-08-09 05:52 UTC, kwfandom commented on src/platforms/ucp-mobile/bidders/prebid/magnite.ts
> +				position: 'atf',
do we need it?

2023-08-09 05:53 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +					loc: ['top'],
im not so sure

2023-08-09 05:54 UTC, kwfandom commented on src/platforms/ucp-desktop/bidders/prebid/magnite.ts
> +				position: 'atf',
do we need it?

2023-08-09 05:54 UTC, kwfandom commented
For me it's like, try those params in different configurations and check the network tab what is happening ;-;

2023-09-04 12:27 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/base-context.setup.ts
> +		context.set('bidders.s2s.bidders', this.instantConfig.get('icPrebidS2sBidders'));
Discussion/Idea:
This is equal to "using magnite s2s"? If so, maybe we should extend this and add this "magnite"? Right not, with only "s2s" in name, I would think of it, as a general mechanism, not only this strict variant "magnite s2s". What do you think?

2023-09-04 12:34 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/bidders/prebid/magniteS2s.ts
> +			top_leaderboard: {
in Jira task, in AC there is only top-boxad pointed, but here we can see configuration for more that top-boxad slot. I also do not see request to extend. Do we really want to bid for all of these slots?

2023-09-04 13:23 UTC, mfarul commented on src/platforms/shared/setup/base-context.setup.ts
> +		context.set('bidders.s2s.bidders', this.instantConfig.get('icPrebidS2sBidders'));
why not using instantConfig.get('icPrebidS2sBidders') directly instead of via context?

2023-09-04 13:29 UTC, adi-wesolowski-fandom requested changes

2023-09-04 15:36 UTC, lnawrotek commented on src/platforms/ucp-desktop/bidders/prebid/magniteS2s.ts
> +		accountId: 7450,
We use the same Account ID, because it's one company but different brands/tools. I suggest using a variable only in src/ad-bidders/prebid/index.ts What do you think?

2023-09-04 18:07 UTC, lnawrotek commented on src/platforms/ucp-desktop/bidders/prebid/magniteS2s.ts
> +			top_leaderboard: {
I think this is the result of not understanding this task. We can bid for all slots.

2023-09-04 18:15 UTC, lnawrotek commented on src/ad-bidders/prebid/index.ts
> +		if (context.get('bidders.s2s.enabled')) {
done

2023-09-05 06:34 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/base-context.setup.ts
> +		context.set('bidders.s2s.enabled', this.instantConfig.get('icPrebidS2s'));
Ok. But with one you can accomplish same thing, just do not put bidders in array where you want to disable it. Its gonna be same thing and we keep it lighter (less bytes to send through). 

But as I said, its ok. I dont want to enforce it.

2023-09-05 06:36 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/base-context.setup.ts
> +		context.set('bidders.s2s.bidders', this.instantConfig.get('icPrebidS2sBidders'));
👍

2023-09-05 06:37 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/bidders/prebid/magniteS2s.ts
> +			top_leaderboard: {
ok. Just asking :)

2023-09-05 06:37 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/bidders/prebid/magniteS2s.ts
> +		accountId: 7450,
ok

2023-09-05 06:37 UTC, adi-wesolowski-fandom commented on src/ad-bidders/prebid/index.ts
> +		if (context.get('bidders.s2s.enabled')) {
cool

2023-09-05 07:53 UTC, mfarul commented on src/platforms/shared/setup/base-context.setup.ts
> +		context.set('bidders.s2s.enabled', this.instantConfig.get('icPrebidS2s'));
i'm for 1 variable, let's save some network bandwidth !

2023-09-05 12:28 UTC, adi-wesolowski-fandom submitted a review, later dismissed

2023-09-08 12:05 UTC, adi-wesolowski-fandom approved these changes

2023-09-13 10:22 UTC, merged