ADEN-13247 - Moved directedAtChildren out of Blockthrough scope
Wikia/ad-engine pull request #1962
Opened 2023-05-30 15:16 UTC by domjanik

In this PR I've moved directedAtChildren flag out of Blockthrough scope. I did that, because we found out that it is being used by other partners as well and its better to keep such values out of single partners scope.

2023-05-31 09:32 UTC, jbienkowski-fandom commented on spec/ad-services/bt-rec/bt-rec.spec.ts
> -			expect(window.fandomContext.partners.blockthrough.directedAtChildren).to.equal(true);
are we not interested in backwards compatibility?

2023-05-31 10:21 UTC, szymon-nawrocki commented on src/ad-services/bt-rec/index.ts
>  		globalContextService.setValue(GlobalContextCategories.partners, {
This code sets up `partners.directedAtChildren` at `fandomContext` object and now is not only BTRec related.
I think it should be moved out of `/ad-services/bt-rec` catalogue

2023-05-31 10:22 UTC, domjanik commented on spec/ad-services/bt-rec/bt-rec.spec.ts
> -			expect(window.fandomContext.partners.blockthrough.directedAtChildren).to.equal(true);
We're going to inform our partners about that and sync it with them. I think we do not need such compatibility right now 🤔

2023-05-31 11:19 UTC, jbienkowski-fandom requested changes

2023-05-31 11:19 UTC, jbienkowski-fandom commented on src/core/utils/is-coppa-subject.ts
> +				blockthrough: {
backward compatible after all? :) let `@types/fandom/index.d.ts` reflect that change too please

2023-05-31 11:19 UTC, jbienkowski-fandom commented on src/core/utils/is-coppa-subject.ts
>  export function isCoppaSubject(): boolean {
we should check `globalContextService.getValue` and use it as "cache" as `utils.isCoppaSubject` is used quite a lot

2023-05-31 12:10 UTC, domjanik commented on src/core/utils/is-coppa-subject.ts
> +				blockthrough: {
Yeah... I thought about this and after all I'm kinda afraid of letting this only up to our partners xD

2023-05-31 12:47 UTC, szymon-nawrocki commented on src/core/utils/is-coppa-subject.ts
>  export function isCoppaSubject(): boolean {
Also this logic is duplicated in IdentityEngine, maybe this is a good moment to unify it between the repos?
https://github.com/Wikia/identity-engine/blob/main/src/modules/shared/CoppaSubject/index.ts

2023-06-01 07:16 UTC, szymon-nawrocki approved these changes

2023-06-01 07:19 UTC, jbienkowski-fandom submitted a review, later dismissed

2023-06-20 08:14 UTC, szymon-nawrocki submitted a review, later dismissed

2023-06-20 08:45 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
> +			return;
```suggestion
			return undefined;
```

2023-06-20 08:45 UTC, jbienkowski-fandom commented on src/core/services/global-context-service.ts
>  			return categoryObj[key];
(nit1) the `else` statement is unnecessary, so let's get rid of it
(nit2) `return undefined;` at the end (explicit is better than implicit)

2023-06-20 12:34 UTC, szymon-nawrocki approved these changes

2023-06-20 13:35 UTC, jbienkowski-fandom approved these changes
LGTM

2023-06-26 12:29 UTC, merged