ADEN-13301 - bidders fo gallery slot
Wikia/ad-engine pull request #2026
Opened 2023-06-29 11:45 UTC by adi-wesolowski-fandom

- upgrade context setup (bidder-alias)
- add bidders setup:
  - appnexus
  - index-exchange
  - pubmatic
  - rubicon
  - kargo (created new file + upgrade prebid congif setup)

2023-06-30 09:45 UTC, lnawrotek approved these changes

2023-06-30 10:10 UTC, dmnsobczak commented on src/platforms/ucp-desktop/setup/context/slots/ucp-desktop-slots-context.setup.ts
> +				bidderAlias: 'fandom_dt_galleries',
Move below the `adProduct`

2023-06-30 10:11 UTC, dmnsobczak commented on src/platforms/ucp-desktop/setup/context/prebid/ucp-desktop-prebid-config.setup.ts
> +		context.set('bidders.prebid.kargo', getKargoContext());
Alphabetical order

2023-06-30 10:12 UTC, dmnsobczak commented on src/platforms/ucp-desktop/bidders/prebid/kargo.ts
> +	const desktopSlots = {
This variable is redundant since we return it instantly

2023-06-30 10:12 UTC, dmnsobczak commented on src/platforms/ucp-desktop/bidders/prebid/appnexus.ts
> +			gallery: '30286507',
`gallery` logically should be before `other`

2023-06-30 10:17 UTC, dmnsobczak commented on src/platforms/ucp-desktop/bidders/prebid/kargo.ts
> +export function getKargoContext(): object {
Kargo is not enabled on Desktop - this will require rollout

2023-06-30 10:18 UTC, dmnsobczak requested changes
Few syntax suggestions left

2023-06-30 10:38 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/bidders/prebid/appnexus.ts
> +			gallery: '30286507',
ok

2023-06-30 10:39 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/bidders/prebid/kargo.ts
> +	const desktopSlots = {
ok

2023-06-30 10:39 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/bidders/prebid/kargo.ts
> +export function getKargoContext(): object {
ok

2023-06-30 10:55 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/setup/context/slots/ucp-desktop-slots-context.setup.ts
> +				bidderAlias: 'fandom_dt_galleries',
ok

2023-06-30 10:55 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/setup/context/prebid/ucp-desktop-prebid-config.setup.ts
> +		context.set('bidders.prebid.kargo', getKargoContext());
ok

2023-07-04 09:23 UTC, dmnsobczak approved these changes

2023-07-14 11:46 UTC, lnawrotek approved these changes

2023-07-18 10:29 UTC, merged