TACO-57 - Added handling Promise
Wikia/ad-engine pull request #2053
Opened 2023-07-17 09:34 UTC by domjanik

2023-07-21 09:32 UTC, szymon-nawrocki commented on src/communication/event-types.ts
>  		category: '[IdentityEngine]',
This event can be removed

2023-07-21 09:35 UTC, szymon-nawrocki commented on src/ad-services/identity-setup/index.ts
> -				targetingService.set('over_18', over18);
Don't we want to set up `over_18` no more?

2023-07-21 09:36 UTC, szymon-nawrocki commented on src/platforms/ucp-desktop/ucp-desktop-platform.ts
> -	IdentitySetup,
Should be also removed from `ucp-mobile-platform.ts`

2023-07-21 09:37 UTC, szymon-nawrocki commented on src/platforms/ucp-desktop/modes/ucp-desktop-ads.mode.ts
> +	IdentitySetup,
Same logic should be applied to `ucp-mobile-ads.mode.ts`

2023-07-21 09:39 UTC, szymon-nawrocki commented on src/platforms/shared/bootstrap.ts
> -import { trackingOptInWrapper } from './consent/tracking-opt-in-wrapper';
`TrackingOptInWrapper` class is not used anymore, so it looks like it should be removed

2023-07-21 09:43 UTC, szymon-nawrocki requested changes
Remove old not used code, and apply this changes to ucp-mobile platform

2023-07-24 07:03 UTC, domjanik commented on src/ad-services/identity-setup/index.ts
> -				targetingService.set('over_18', over18);
Unfortunately - no :( Whole Pipeline should be stopped long time ago

2023-07-24 09:52 UTC, szymon-nawrocki submitted a review, later dismissed

2024-05-14 12:29 UTC, closed without merging