Aden 13414
Wikia/ad-engine pull request #2080
Opened 2023-08-02 09:15 UTC by rafalgiemza

https://fandom.atlassian.net/browse/ADEN-13414

2023-08-03 09:10 UTC, lnawrotek commented on src/platforms/sports/styles.scss
> +			display: none;
Why did you remove "important"?

2023-08-03 09:10 UTC, lnawrotek commented on src/platforms/ucp-mobile/styles.scss
> +	&.hidden-ad {
Why did you remove "important"?

2023-08-03 09:10 UTC, lnawrotek commented on src/platforms/ucp-mobile/styles.scss
> +	display: none;
Why did you remove "important"?

2023-08-03 09:10 UTC, lnawrotek commented on src/platforms/shared/styles/common/hidden-ad-helper.scss
> +@mixin hidden-ad-helper() {
```suggestion
@mixin hidden-ad() {
```

or you can add this to _mixin.scss

2023-08-03 09:10 UTC, lnawrotek commented on src/platforms/shared/styles/common/hidden-ad-helper.scss
> +		display: none;
Your code doesn't have "important", is it ok? A lot of replaced CSS had "important".

2023-08-03 12:33 UTC, rafalgiemza commented on src/core/models/ad-slot.ts
> +export const HIDDEN_AD_CLASS = 'hidden-ad';
Good catch, I unified this code. Now everywhere simple HIDDEN_AD_CLASS is used.

2023-08-03 12:43 UTC, rafalgiemza commented on src/platforms/shared/styles/common/hidden-ad-helper.scss
> +@mixin hidden-ad-helper() {
moved :)

2023-08-03 12:49 UTC, rafalgiemza commented on src/platforms/sports/styles.scss
> +			display: none;
reverted

2023-08-03 12:50 UTC, rafalgiemza commented on src/platforms/ucp-mobile/styles.scss
> +	&.hidden-ad {
reverted

2023-08-03 12:50 UTC, rafalgiemza commented on src/platforms/ucp-mobile/styles.scss
> +	display: none;
reverted

2023-08-04 07:32 UTC, adi-wesolowski-fandom requested changes

2023-08-04 07:32 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/styles.scss
> +		&.hidead {
mixin-2 should catch it (even 1 should)

2023-08-04 07:32 UTC, adi-wesolowski-fandom commented on src/platforms/shared/styles/_mixin.scss
> +	.hiddn-a {
why `hiddn-a`? I dont see it anywhere

2023-08-04 07:32 UTC, adi-wesolowski-fandom commented on src/platforms/shared/styles/_mixin.scss
> +	.hiddn-a {
if here, shoud be "hidead" instead, mixin 1 and 2 are the same in the end. The only difference is by adding "important" or not. This can be parametrized. 

![Screenshot 2023-08-04 at 09 24 00](https://github.com/Wikia/ad-engine/assets/124166784/d8eb4c86-1ece-42f8-9640-c8a4c211c321)

2023-08-04 07:32 UTC, adi-wesolowski-fandom commented on src/platforms/shared/styles/_mixin.scss
> +	& .hidead {
`&` can be ommited. It doesnt give anything. 
![Screenshot 2023-08-04 at 09 24 00](https://github.com/Wikia/ad-engine/assets/124166784/3f3ad242-475a-4932-bdb5-3d83a49f5835)

2023-08-04 07:32 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/styles.scss
> +@include hidden-ad-helper-3();
it could be replaced with: 
```
.top-ads-container,
.bottom-ads-container,
.ad-slot-placeholder{
	@include hidden-ad-helper-1();
}
```

with other fixes, we could end up with only one hiding mixin, instead of 3 :)

2023-08-04 07:32 UTC, adi-wesolowski-fandom commented on README.md
> +				additionalClasses: 'hidead',
this field exist only in readme. Isnt it depreceted a long ago? Isnt it just "classList"?

2023-08-04 08:17 UTC, rafalgiemza commented on src/platforms/shared/styles/_mixin.scss
> +	.hiddn-a {
`hiddn-a` is a typo
refactored to `hidden-ad-helper($important: true)`

2023-08-04 08:21 UTC, rafalgiemza commented on src/platforms/ucp-desktop/styles.scss
> +@include hidden-ad-helper-3();
refactored :)

2023-08-04 08:33 UTC, rafalgiemza commented on README.md
> +				additionalClasses: 'hidead',
it looks for me more like RepeatConfig --> https://github.com/Wikia/ad-engine/blob/0ac15e4bf78fcbac1898172e522e81d4ff3ededb/src/core/models/ad-slot.ts#L17
so I can simple remove additionalClasses property

2023-08-04 08:33 UTC, rafalgiemza commented on src/platforms/shared/styles/_mixin.scss
> +	& .hidead {
removed :)

2023-08-04 08:35 UTC, rafalgiemza commented on src/platforms/ucp-desktop/styles.scss
> +		&.hidead {
refactored

2023-08-04 08:55 UTC, kwfandom commented on src/platforms/shared/utils/placeholder-service-helper.ts
> +	shouldHiddenAdLabel = (adLabel: HTMLElement): boolean => {
Why?

2023-08-04 09:03 UTC, rafalgiemza commented on src/platforms/shared/utils/placeholder-service-helper.ts
> +	shouldHiddenAdLabel = (adLabel: HTMLElement): boolean => {
My goal was to keep only 2 places with 'hidead': 
const in js
usage in mixin
But this time is too much, let's revert this one

2023-08-04 09:03 UTC, kwfandom commented on src/platforms/shared/utils/placeholder-service-helper.ts
> +	shouldHiddenAdLabel = (adLabel: HTMLElement): boolean => {
Im just asking about function name

2023-08-04 09:09 UTC, rafalgiemza commented on src/platforms/shared/utils/placeholder-service-helper.ts
> +	shouldHiddenAdLabel = (adLabel: HTMLElement): boolean => {
yeah, old was better

2023-08-04 10:10 UTC, adi-wesolowski-fandom submitted a review, later dismissed

2023-08-07 08:36 UTC, kwfandom commented on src/core/models/ad-slot.ts
> +export const HIDDEN_AD_CLASS = 'hidead';
I believe it's not the proper place for that.
```suggestion
```

2023-08-07 08:37 UTC, kwfandom commented on src/core/models/ad-slot.ts
>  	static AD_SLOT_PLACEHOLDER_CLASS = 'ad-slot-placeholder';
```suggestion
	static AD_SLOT_PLACEHOLDER_CLASS = 'ad-slot-placeholder';
	static HIDDEN_AD_CLASS = 'hidead';
```

2023-08-07 08:38 UTC, kwfandom commented on src/core/models/ad-slot.ts
> +export const HIDDEN_AD_CLASS = 'hidead';
It may be the root cause of mobile adhesion is not working.

2023-08-07 08:38 UTC, kwfandom commented on src/core/models/ad-slot.ts
> +		const added = this.addClass(HIDDEN_AD_CLASS);
I'm a newbie, but that was necessary?

2023-08-07 13:52 UTC, rafalgiemza commented on src/core/models/ad-slot.ts
> +export const HIDDEN_AD_CLASS = 'hidead';
The issue was related to omitted place with the 'hide' class in the unified-platform. More here: https://fandom.atlassian.net/browse/ADEN-13414?focusedCommentId=718605

2023-08-07 13:55 UTC, rafalgiemza commented on src/core/models/ad-slot.ts
>  	static AD_SLOT_PLACEHOLDER_CLASS = 'ad-slot-placeholder';
It's not good idea IMO

2023-08-07 14:53 UTC, lnawrotek submitted a review, later dismissed

2023-08-11 06:23 UTC, dmnsobczak commented on src/core/models/ad-slot.ts
> +export const HIDDEN_AD_CLASS = 'hidead';
I suggest keeping this constant inside AdSlot class. This is a static variable and can be accessed via `AdSlot::HIDDEN_CLASS ` and imho it is more logical.

2023-08-11 06:24 UTC, dmnsobczak commented on README.md
> -				additionalClasses: 'hide',
This hides the ad slot for rendering time and unhide once ad is ready. Why you removed it?

2023-08-11 06:25 UTC, dmnsobczak commented on src/ad-services/anyclip/index.ts
> +	HIDDEN_AD_CLASS,
You can import `AdSlot`, type the variable in L16 and import this constant from `AdSlot::HIDE`

2023-08-11 06:27 UTC, dmnsobczak commented on src/platforms/news-and-ratings/shared/templates/handlers/floor-adhesion/floor-adhesion-bootstrap-handler.ts
> +	HIDDEN_AD_CLASS,
In most places AdSlot is imported together with this constant.

2023-08-11 06:29 UTC, dmnsobczak requested changes
I can't access Jira to read full context of this change but for me it looks like a highly-regressive and unnecessary change. Can you give me a tl;dr explanation? 
But CSS cleanup is fine. I'm just worried about class rename. This is a so called "global constant" like `top_leaderboard` and this change might require checking CSS and JS on all platforms for custom overrides 🤔

2023-08-29 20:32 UTC, rafalgiemza commented on README.md
> -				additionalClasses: 'hide',
I thought, that this was outdated. Change reverted, value updated.

2023-08-29 20:32 UTC, rafalgiemza commented on src/ad-services/anyclip/index.ts
> +	HIDDEN_AD_CLASS,
Suggestion applied

2023-08-29 20:32 UTC, rafalgiemza commented on src/platforms/news-and-ratings/shared/templates/handlers/floor-adhesion/floor-adhesion-bootstrap-handler.ts
> +	HIDDEN_AD_CLASS,
Right, fixed

2023-08-30 11:55 UTC, lnawrotek commented on src/platforms/shared/styles/_mixin.scss
> +@mixin hidden-ad-helper($important: true) {
```suggestion
@mixin hidden-ad($important: true) {
```

2023-08-30 12:19 UTC, lnawrotek approved these changes

2023-09-12 11:17 UTC, merged