ADEN-13335 | Ads on Image Galleries (mweb)
Wikia/ad-engine pull request #2088
Opened 2023-08-08 21:19 UTC by rafalgiemza

- add event types on init, change image and close lightbox

2023-08-10 08:02 UTC, kwfandom commented on src/platforms/ucp-mobile/setup/context/slots/ucp-mobile-slots-context.setup.ts
> +				bidderAlias: 'fandom_dt_galleries',
dt?

2023-08-10 08:03 UTC, kwfandom commented on src/platforms/ucp-mobile/setup/dynamic-slots/specific-handler.ts/gallery-lightbox-handler.ts
> +export class MobileGalleryLightboxHandler {
is there any reason why we cannot reuse class created by @adi-wesolowski-fandom?

2023-08-10 09:05 UTC, rafalgiemza commented on src/platforms/ucp-mobile/setup/context/slots/ucp-mobile-slots-context.setup.ts
> +				bidderAlias: 'fandom_dt_galleries',
I made a mistake while copying from the desktop. It's not necessary, removed

2023-08-10 09:07 UTC, rafalgiemza commented on src/platforms/ucp-mobile/setup/dynamic-slots/specific-handler.ts/gallery-lightbox-handler.ts
> +export class MobileGalleryLightboxHandler {
I thought there must be different event names, but that's not true. The code is now refactored: mobile and desktop shared the same setup.

2023-08-11 06:38 UTC, dmnsobczak commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +import { UcpDesktopSlotsDefinitionRepository } from '../../ucp-desktop/setup/dynamic-slots/ucp-desktop-slots-definition-repository';
You importing from platform in file that is later used on that platform - this a MAJOR circular dependency error.

2023-08-11 06:39 UTC, dmnsobczak commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +import { UcpDesktopSlotsDefinitionRepository } from '../../ucp-desktop/setup/dynamic-slots/ucp-desktop-slots-definition-repository';
Even if linter don't report that.

2023-08-11 06:39 UTC, dmnsobczak commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +		private slotsDefinitionRepository:
Files in shared should be UNIVERSAL, no platform dependent

2023-08-11 06:40 UTC, dmnsobczak commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +	private hideFlorAdhesion() {
It's "FloorAdhesion", please check typos

2023-08-11 06:40 UTC, dmnsobczak commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +	private showFlorAdhesion() {
ditto

2023-08-11 06:42 UTC, dmnsobczak commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +export class GalleryLightboxSetup {
"Setup" classes should implement "DiProcess" and be a step of the pipeline. You introducing a mess in naming.

2023-08-11 06:43 UTC, dmnsobczak commented on src/platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +		new GalleryLightboxSetup(this.slotsDefinitionRepository).handle();
What about DI? We almost don't use "new Class" construction in AdEngine.

2023-08-11 06:44 UTC, dmnsobczak commented on src/platforms/ucp-mobile/ad-context.ts
> +				'gallery_leaderboard',
I don't know if that shouldn't be first discussed with IAS.

2023-08-11 06:44 UTC, dmnsobczak commented on src/platforms/ucp-mobile/ad-context.ts
> +				'gallery_leaderboard',
For the same reason `incontent_leaderboard` is not here

2023-08-11 06:47 UTC, dmnsobczak commented on src/platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +		new GalleryLightboxSetup(this.slotsDefinitionRepository).handle();
If you pass `this.slotsDefinitionRepository` into GallerySetup, then maybe `handleMobileGalleryLightboxSlots` should be a method inside that repository where you can just reference `this` 🤔

2023-08-11 06:48 UTC, dmnsobczak requested changes
Some comments left

2023-08-11 07:15 UTC, preludek commented
> Some comments left

You need to move on brother 😿

2023-08-16 07:32 UTC, rafalgiemza commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +	private hideFlorAdhesion() {
typo fixed

2023-08-16 07:34 UTC, rafalgiemza commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +	private showFlorAdhesion() {
typo fixed also here

2023-08-16 07:40 UTC, rafalgiemza commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +export class GalleryLightboxSetup {
agree, reverted to GalleryLightboxHandler

2023-08-21 05:13 UTC, rafalgiemza commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +import { UcpDesktopSlotsDefinitionRepository } from '../../ucp-desktop/setup/dynamic-slots/ucp-desktop-slots-definition-repository';
fixed

2023-08-21 05:13 UTC, rafalgiemza commented on src/platforms/shared/setup/gallery-lightbox.setup.ts
> +		private slotsDefinitionRepository:
fixed

2023-08-21 10:15 UTC, rafalgiemza commented on src/platforms/ucp-desktop/setup/dynamic-slots/ucp-desktop-dynamic-slots.setup.ts
> +		new GalleryLightboxSetup(this.slotsDefinitionRepository).handle();
fixed

2023-08-21 10:58 UTC, rafalgiemza commented on src/platforms/ucp-mobile/ad-context.ts
> +				'gallery_leaderboard',
removed

2023-08-22 10:28 UTC, kwfandom commented on src/platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +			console.log(
?

2023-08-22 10:28 UTC, kwfandom commented on src/platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +			'🚀 ~ file: ucp-mobile-dynamic-slots.setup.ts:294 ~ UcpMobileDynamicSlotsSetup ~ handleMobileGalleryLightboxAdsSlots ~ this.galleryLightbox:',
?

2023-08-22 12:57 UTC, rafalgiemza commented on src/platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +			console.log(
removed :)

2023-08-22 12:58 UTC, rafalgiemza commented on src/platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +			'🚀 ~ file: ucp-mobile-dynamic-slots.setup.ts:294 ~ UcpMobileDynamicSlotsSetup ~ handleMobileGalleryLightboxAdsSlots ~ this.galleryLightbox:',
removed :)

2023-08-22 15:43 UTC, mfarul approved these changes

2023-08-23 13:23 UTC, mfarul submitted a review, later dismissed

2023-08-24 04:38 UTC, kwfandom commented
Unit tests are failing http://prod.jenkins.service.sjc.consul:8080/job/adengine_pr_unit_tests/19339/console

2023-08-25 14:22 UTC, kwfandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +	private hideRegisterBox() {
nope. It's not the solution, mesage-box-service.ts -> add check for gallery leaderboard and put it to if.

2023-08-25 14:22 UTC, kwfandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +	private showRegisterBox() {
^

2023-08-28 06:52 UTC, kwfandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +		const floor = document?.getElementsByClassName('gallery-leaderboard')[0];
SlotService.get('xx')....
xx-slotname

2023-08-28 06:52 UTC, kwfandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +			const floor = document?.getElementById('floor_adhesion_anchor');
^

2023-08-28 06:53 UTC, kwfandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +		const floor = document?.getElementsByClassName('gallery-leaderboard')[0];
^

2023-08-28 06:53 UTC, kwfandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +			const floor = document?.getElementById('floor_adhesion_anchor');
Can't we just readjust the index of floor like on the desktop?

2023-08-28 08:29 UTC, adi-wesolowski-fandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +			const floor = document?.getElementById('floor_adhesion_anchor');
Karol, you mean z-index? Playing with z-indexes isnt good option IMO. It may lead to other problems in the future.

2023-08-28 08:35 UTC, adi-wesolowski-fandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +		const floor = document?.getElementsByClassName('gallery-leaderboard')[0];
hint: need to add "getElement()" at the end, to have HTML Element and be able to manipulate css classes, as using SlotsService.get return AdSlot instance.

2023-08-28 09:18 UTC, rafalgiemza commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +	private hideRegisterBox() {
good point! logic moved to right place

2023-08-28 09:20 UTC, adi-wesolowski-fandom commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +			const floor = document?.getElementById('floor_adhesion_anchor');
as for this, to replace by slot-service - I am not sure, as its not slots itself, but some other element. Jumping on the node-ladder to get right element after calling slotservice.get for floor, may cause problems as something change in the future in the structure. But I would consider changing string into some kind of static const variable. We use this same lines in few other places in ad-engine. 
![Screenshot 2023-08-28 at 11 20 09](https://github.com/Wikia/ad-engine/assets/124166784/9b70071f-73df-4f47-812e-4ab7042fa3ff)
Maybe some small refactor could be done to keep this name in one place. But not necessary here on this ticket?

2023-08-28 09:26 UTC, rafalgiemza commented on src/platforms/shared/handlers/gallery-lightbox-handler.ts
> +		const floor = document?.getElementsByClassName('gallery-leaderboard')[0];
fixed

2023-08-28 11:31 UTC, merged