ADEN-13527 Disable System1 on kid wikis
Wikia/ad-engine pull request #2118
Opened 2023-08-29 12:05 UTC by lnawrotek

2023-08-29 17:09 UTC, mfarul requested changes

2023-08-29 17:09 UTC, mfarul commented on src/ad-services/system1/index.ts
> +		if (!this.isEnabled('icSystem1', false) || this.isKidWiki()) {
```suggestion
		if (!this.isEnabled('icSystem1', false) || utils.isCoppaSubject()) {
```

2023-08-29 17:09 UTC, mfarul commented on src/ad-services/system1/index.ts
> +		if (!this.isEnabled('icSystem1', false) || this.isKidWiki()) {
and we can get rid of the kid wiki direct check - util is handling this plus Age gate, e.g. when adult is comming to kid wiki

2023-08-30 09:44 UTC, kwfandom approved these changes

2023-08-30 11:43 UTC, merged