ADEN-13571 | don't allow prebid.js and reorg pipeline for it
Wikia/ad-engine pull request #2136
Opened 2023-09-08 17:33 UTC by mfarul

2023-09-11 07:30 UTC, jakubbanas submitted a review, later dismissed

2023-09-22 08:14 UTC, preludek commented on src/platforms/shared/tracking/metric-reporter.ts
> +	initialise() {
```suggestion
	initialize() {
```

😈

2023-09-22 08:24 UTC, preludek commented on src/platforms/shared/utils/preloaded-libraries-setup.ts
> +	pu;
coś zostało 😅 
![image](https://github.com/Wikia/ad-engine/assets/43118980/779b8d10-d212-4d20-af8e-bfe2f0c578e5)

2023-09-22 08:40 UTC, preludek requested changes
Left one comment and there's also a random line to be removed.

2023-09-26 09:20 UTC, mfarul commented on src/platforms/shared/utils/preloaded-libraries-setup.ts
> +export class PreloadedLibrariesSetup implements DiProcess {
Yea, folder could be changed, it was just used as i've renamed existing file ;).

About the I've tried but then we need to change the pipeline logic as it's working on DIProcess that does not allow different instances :(.

2023-11-20 09:30 UTC, preludek submitted a review, later dismissed

2023-11-21 08:18 UTC, preludek approved these changes

2023-11-27 09:59 UTC, preludek approved these changes

2023-11-27 10:47 UTC, merged