ADEN-13541 - delay pipeline, waiting for onload event when set in icbm
Wikia/ad-engine pull request #2140
Opened 2023-09-12 14:29 UTC by adi-wesolowski-fandom

2023-09-15 09:43 UTC, mfarul requested changes

2023-09-15 09:43 UTC, mfarul commented on src/core/pipeline/imps/process-pipeline/compound-processes/when-page-loaded-process.ts
> +const WAIT_FOR_PAGE_LOAD_TIMEOUT = 2000;
ideally it should be ICBM variable, can also be used to start testing, e.g. no value - don't wait

2023-09-15 09:43 UTC, mfarul commented on src/core/pipeline/imps/process-pipeline/compound-processes/when-page-loaded-process.ts
> +			this.addExecutePipeline(pipeline, payload);
kill timeout here, even with fired variable let's free up some browser resources

2023-09-18 07:10 UTC, adi-wesolowski-fandom commented on src/core/pipeline/imps/process-pipeline/compound-processes/when-page-loaded-process.ts
> +const WAIT_FOR_PAGE_LOAD_TIMEOUT = 2000;
I think, its good to leave some kind of default value, in case someone miss any domain/page, or geo would be skipped? But it's certainly no problem, I will add reading icbm variable for timeout as well.

2023-09-18 07:28 UTC, adi-wesolowski-fandom commented on src/core/pipeline/imps/process-pipeline/compound-processes/when-page-loaded-process.ts
> +			this.addExecutePipeline(pipeline, payload);
to be honest, I think it will cost us more (more bytes to send as we need more code for clearing) than letting it run without action (timeout is lightweight for browsers IMO). But ok, I added this clearing.

2023-09-18 13:40 UTC, mfarul submitted a review, later dismissed
Let's move on, more changes required

2023-09-20 13:21 UTC, mfarul approved these changes

2023-09-25 07:05 UTC, adi-wesolowski-fandom commented on src/core/pipeline/imps/process-pipeline/compound-processes/phases/dom-content-loaded-phase-process.ts
> +			console.log('AEPERF fired');
```
console.log('[AEPERF] fired');
```

2023-10-16 07:46 UTC, adi-wesolowski-fandom commented
logic moved to "warp" branch

2023-10-16 07:46 UTC, closed without merging