ADEN-13549 delay events after document load completed
Wikia/ad-engine pull request #2152
Opened 2023-09-20 11:55 UTC by preludek

2023-09-20 13:10 UTC, mfarul commented on src/platforms/shared/tracking/load-times-tracker.ts
> +		if (document.readyState !== 'complete') {
can we extract a Promise here with a timeout as well ?

2023-09-22 09:48 UTC, preludek commented on src/platforms/shared/tracking/load-times-tracker.ts
> +		if (document.readyState !== 'complete') {
I've sculpted something. Is that something you were thinking of?

2023-09-29 17:37 UTC, mfarul requested changes

2023-09-29 17:37 UTC, mfarul commented on src/platforms/shared/tracking/batch-processor.ts
> +				batchToSend.forEach(({ url, params, type }) => sendRequest(url, params, type));
not clear where the task interface is, it should be rather generic with task, task processor (callback) and generic structure for tasks

2023-10-02 09:23 UTC, adi-wesolowski-fandom requested changes

2023-10-02 09:23 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/base-context.setup.ts
> +		context.set('options.delayEvents', this.instantConfig.get('icDelayEvents'));
why not set any default?

2023-10-02 09:23 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/batch-processor.ts
> +			if (this.batchedTasks.length > 0) {
quick exit should be more readable, hm?
```suggestion
			if (this.batchedTasks.length <= 0) { clear; return; }
```

2023-10-02 09:23 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse.ts
> +			document.addEventListener('readystatechange', () => {
this wont trigger if we would jump after event occur. 
My suggestion: extract code below into function like "dispatchWhenReady" and also check if document isnt complete already, before we set "addEventListener" - if not - set it, if it already done, just run "displathWhenReady" function

2023-10-02 09:23 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse.ts
> +	private handleDwEvent(url: string, params: DataWarehouseParams, type = 'Event'): void {
with suggestion above, this could be simplified

2023-10-02 09:23 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse.ts
> +		if (context.get('options.delayEvents.enabled')) {
quicker exit would be more appropriate

2023-10-02 09:23 UTC, adi-wesolowski-fandom commented on src/platforms/shared/tracking/data-warehouse.ts
> +					this.sendRequest(url, params, type);
4 level of nesting :(

2023-10-03 06:11 UTC, preludek commented on src/platforms/shared/setup/base-context.setup.ts
> +		context.set('options.delayEvents', this.instantConfig.get('icDelayEvents'));
I just didn't see the point to be honest. This is behind a icVar and has to be enabled anyway, why not just set it there? In case we need to change the numbers quickly we will have to do it through ICBM as well so 🤷

2023-10-03 06:14 UTC, preludek commented on src/platforms/shared/tracking/batch-processor.ts
> +			if (this.batchedTasks.length > 0) {
👍

2023-10-03 06:18 UTC, preludek commented on src/platforms/shared/tracking/data-warehouse.ts
> +			document.addEventListener('readystatechange', () => {
After this event occured we don't need this listener anyway and the events are being sent "the old way". Logic behind it is in `handleDwEvent` method

2023-10-03 06:21 UTC, preludek commented on src/platforms/shared/tracking/data-warehouse.ts
> +		if (context.get('options.delayEvents.enabled')) {
I mean I could change the order and check if `!context.get('options.delayEvents.enabled')` first and then sendRequest and return but I think this way it is is more readable and straightforward

2023-10-03 06:40 UTC, preludek commented on src/platforms/shared/tracking/batch-processor.ts
> +				batchToSend.forEach(({ url, params, type }) => sendRequest(url, params, type));
Done

2023-10-03 07:56 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/base-context.setup.ts
> +		context.set('options.delayEvents', this.instantConfig.get('icDelayEvents'));
because there is always a slight chance, that icVar wont be set in some countries, if we eg. forget to set XX as fallback :) 
But ok, if you dont see a point, no problem

2023-10-03 07:59 UTC, adi-wesolowski-fandom approved these changes

2023-10-05 12:35 UTC, mfarul approved these changes

2023-10-05 12:38 UTC, merged