Aden 13638 Enable Prebid localstorage for bidders
Wikia/ad-engine pull request #2179
Opened 2023-10-03 11:17 UTC by lnawrotek

2023-10-03 20:07 UTC, mfarul requested changes

2023-10-03 20:07 UTC, mfarul commented on src/ad-bidders/prebid/prebid-settings.ts
> +		if (typeof aliases === 'object') {
Can we extract this to method with a name describing what we are doing here? 
replaceFirstEmptyConfigurationForAlias ?

2023-10-04 09:47 UTC, preludek approved these changes

2023-10-04 09:50 UTC, mfarul approved these changes

2023-10-05 12:28 UTC, merged