ADEN-13006 - add new bidder: seedtag
Wikia/ad-engine pull request #2185
Opened 2023-10-09 07:49 UTC by adi-wesolowski-fandom

2023-10-10 07:50 UTC, preludek approved these changes
Looks good, some minor comments for consideration

2023-10-10 07:50 UTC, preludek commented on src/ad-bidders/prebid/adapters/seedtag.ts
> +						placement: placement ?? 'inBanner',
For consideration, this can be probably set as default 'inBanner' in line 17 and here just pass it as placement.

2023-10-10 07:50 UTC, preludek commented on src/ad-bidders/prebid/prebid-models.ts
> +	publisherId?: string;
Order 😈

2023-10-10 07:50 UTC, preludek commented on src/platforms/ucp-desktop/bidders/prebid/seedtag.ts
> +	return {
`publisherId` is the same for all slots, wonder if it can be passed besides the slots key like for example in `getPubmaticContext()`

2023-10-10 07:57 UTC, preludek commented on src/platforms/ucp-desktop/bidders/prebid/seedtag.ts
> +			floor_adhesion: {
Those sizes looks like from mobile, also I don't think we run floor_adhesion on desktop except some UAP variant. 🤔

2023-10-10 07:59 UTC, adi-wesolowski-fandom commented on src/ad-bidders/prebid/prebid-models.ts
> +	publisherId?: string;
66?

2023-10-10 07:59 UTC, preludek reviewed
There's also a video slot in the ss and we are missing it here.

2023-10-10 08:39 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/bidders/prebid/seedtag.ts
> +			floor_adhesion: {
agree, but in spreadsheet was connected as desktop, and we also have that slot in desktop context setup: src/platforms/ucp-desktop/setup/context/slots/ucp-desktop-slots-context.setup.ts (however with desktop/TLB size).

I will remove it from here, just for now.

2023-10-10 08:46 UTC, adi-wesolowski-fandom commented on src/platforms/ucp-desktop/bidders/prebid/seedtag.ts
> +	return {
yes, it is the same within one page. For now. 
It would be great, to give possibility to put in eg alongside "enabled" flag. But right here, right now, there is no support for it, as far as I can see. But it is good idea, to add such feature. There is another bidder, with same issue.
For now, I think its good to keep it here: to make it clear and readable. Putting everything in this global "context" variable isnt good way in my opinion, especially here, make another path to passing arguments. It may be confusing, making such exception here, for this particular bidder.

2023-10-10 11:29 UTC, preludek requested changes
Some minor potential improvements + a size change for one slot

2023-10-10 11:29 UTC, preludek commented on src/ad-bidders/prebid/adapters/seedtag.ts
> +				video: {
I'd leave only required parameters here

2023-10-10 11:29 UTC, preludek commented on src/platforms/ucp-desktop/bidders/prebid/seedtag.ts
> +				sizes: [[300, 50]],
```suggestion
				sizes: [[300, 250]],
```

2023-10-10 11:29 UTC, preludek commented on src/ad-bidders/prebid/adapters/seedtag.ts
> +						placement: placement,
```suggestion
						placement,
```

2023-10-10 11:38 UTC, adi-wesolowski-fandom commented on src/ad-bidders/prebid/adapters/seedtag.ts
> +				video: {
I used same as for pubmatic which was marked as supported in seedtag docs, to keep consistency, like eg. max time duration of the ad.

2023-10-10 12:29 UTC, preludek approved these changes

2023-10-11 12:51 UTC, adi-wesolowski-fandom commented on src/ad-bidders/prebid/adapters/seedtag.ts
> +					playerSize: [640, 480],
```suggestion
					playerSize: sizes[0] ?? [640, 480],
```

2023-10-11 13:56 UTC, merged