ADEN-13712 | Measure all pipeline steps and partners
Wikia/ad-engine pull request #2267
Opened 2023-12-05 09:33 UTC by jakubbanas

2023-12-06 09:43 UTC, preludek submitted a review, later dismissed
Overall looks good and like it's working 😄

During refinement I was thinking about emitting events directly from ScriptLoader or maybe a seperate class that would use script loader therefore we could just pass a string in all the partners instead of emiting events from those classes. What do you think about that solution?

2023-12-06 13:24 UTC, jakubbanas commented
> Overall looks good and like it's working 😄
> 
> During refinement I was thinking about emitting events directly from ScriptLoader or maybe a seperate class that would use script loader therefore we could just pass a string in all the partners instead of emiting events from those classes. What do you think about that solution?

Good idea, thanks!

2023-12-06 13:56 UTC, preludek approved these changes

2023-12-06 19:02 UTC, mfarul requested changes

2023-12-06 19:02 UTC, mfarul commented on src/platforms/shared/tracking/load-times-tracker.ts
> +		});
```suggestion
		}, false);
```

2023-12-14 13:22 UTC, mfarul approved these changes

2023-12-18 15:50 UTC, merged