TACO-427 Add cmp tracking key val
Wikia/ad-engine pull request #2345
Opened 2024-02-13 16:21 UTC by szymon-nawrocki

### Ticket
https://fandom.atlassian.net/browse/TACO-427

### Description
Add `cmp` targeting key value to allow GAM monitoring per CMP.
It will be needed for performance monitoring of OneTrust vs Tracking Opt In.

2024-02-19 11:23 UTC, domjanik commented on @types/window/index.d.ts
> +	OneTrust?: any;
Maybe we could type this object a bit? At least include the most important methods/values here?

2024-02-19 11:25 UTC, domjanik commented on src/ad-services/identity-setup/index.ts
> +	private getCmp(): '1t' | 'toi' {
Maybe we could extract '1t' | 'toi' to separate type / enum? Like:
type CmpTypes = '1t' | 'toi' 
or 
enum CmpTypes {
  OneTrust = '1t',
  TrackingOptIn = 'toi'
}

2024-02-19 12:37 UTC, szymon-nawrocki commented on src/ad-services/identity-setup/index.ts
> +	private getCmp(): '1t' | 'toi' {
Great idea, changed ✅

2024-02-22 11:19 UTC, domjanik requested changes

2024-02-22 11:19 UTC, domjanik commented on src/ad-tracking/compilers/slot-tracking-compiler.ts
> +function getCmp(): '1t' | 'toi' {
You can re-use CMP_TYPE from identity-setup in here to preserve consistency.

2024-02-22 12:30 UTC, domjanik submitted a review, later dismissed

2024-03-05 08:30 UTC, domjanik approved these changes

2024-03-05 08:43 UTC, merged