COTECH-1101 Add data privacy consents to VAST URL when in "tagless" mode
Wikia/ad-engine pull request #2373
Opened 2024-02-27 19:30 UTC by nandy-andy

In countries with video+display sync direct ad product we build VAST URL and send request to GAM as soon as possible. But it lacked `gdpr_consent` parameter. In this PR I'm adding the param as well as the `us_privacy` one. I'm also removing unused function and cleaning up the unit test.

2024-02-28 08:23 UTC, dzawada approved these changes

2024-02-28 08:31 UTC, domjanik requested changes

2024-02-28 08:31 UTC, domjanik commented on src/core/utils/tagless-request-url-builder.ts
> -		params.push(`ppid=${ppid}`);
Why PPIDs are being removed from here ? 🤔

2024-02-28 08:31 UTC, domjanik commented on src/core/utils/tagless-request-url-builder.ts
> -	params.push(`rdp=${trackingOptIn.isOptOutSale() ? 1 : 0}`);
AFAIK - rdp ( param telling us about user consent for data selling, CCPA ) and npa ( param telling us about user consent for gdpr ) params are later used. Maybe it would be good to leave them in those requests? Also - we're currently missing NPA param in these requests

2024-02-28 08:31 UTC, domjanik commented on src/core/utils/tagless-request-url-builder.ts
> -		params.push('tfcd=1');
Are you sure, that it is not used by @sseyda/Nef for reports?

2024-02-28 09:20 UTC, nandy-andy commented on src/core/utils/tagless-request-url-builder.ts
> -		params.push(`ppid=${ppid}`);
I removed whole `buildTaglessRequestUrl()` because the only place it's been used was a unit test and GitHub presents the change in a weird way. So it's all still there when building a VAST URL: https://github.com/Wikia/ad-engine/blob/2b2c673d9761508df3088bdb2798b197834e84de/src/core/utils/tagless-request-url-builder.ts#L104-L110

2024-02-28 09:20 UTC, nandy-andy commented on src/core/utils/tagless-request-url-builder.ts
> -		params.push('tfcd=1');
It's still there :)

2024-02-28 09:21 UTC, nandy-andy commented on src/core/utils/tagless-request-url-builder.ts
> -	params.push(`rdp=${trackingOptIn.isOptOutSale() ? 1 : 0}`);
I can add `npa` 👌 

Although, are we sure it's `npa` query-string param not `npa` key-val in `custom_param` query-string? 🤔

2024-03-01 14:48 UTC, nandy-andy commented on src/core/utils/tagless-request-url-builder.ts
> -	params.push(`rdp=${trackingOptIn.isOptOutSale() ? 1 : 0}`);
I've added `npa` query-string param.

2024-03-06 10:44 UTC, domjanik submitted a review, later dismissed

2024-03-06 11:26 UTC, latata approved these changes

2024-03-06 11:26 UTC, latata commented on src/ad-products/video/jwplayer/helpers/vast-tagless-request.ts
> +			isTagless: isTagless,
mnor: 
could be just 
```
isTagless,
```

instead of 
```
isTagless: isTagless,
```

2024-03-08 12:33 UTC, merged