Prevent exception when mw and fandomContext.tracking is not available
Wikia/ad-engine pull request #2374
Opened 2024-02-28 13:24 UTC by latata

2024-02-28 13:27 UTC, adi-wesolowski-fandom requested changes

2024-02-28 13:27 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/tracking-parameters.setup.ts
> +			window.fandomContext?.tracking?.pvUID; // N+R
lets add `|| 0`, temporary, as we may be able to find in DWH reports, how many of such cases are, where pvUID is missing.

2024-03-04 11:26 UTC, mklakus-fandom commented on src/platforms/shared/setup/tracking-parameters.setup.ts
> +			console.error('pvUID is not set');
Can we `console.error` more precise message?

E.g.
```ts
console.error('pvUID is not set correctly');
```
I think the error message is misleading,because when `pvUID` is equal to 0 we would get the error message and also we `return pvUID` which I suppose is intended for this case.

2024-03-04 11:26 UTC, mklakus-fandom approved these changes

2024-03-04 12:10 UTC, jbienkowski-fandom commented on src/platforms/shared/setup/tracking-parameters.setup.ts
>  	private getPvUniqueId() {
`getPvUniqueId` is only used by `getLegacyTrackingParameters`, on most of the platforms `icDisableLegacyTrackingParameters` is set to `true` and we are not relying on these values (we use `window.fandomContext`). I have set it consistently for all platforms and I believe the best solution would be to delete `getLegacyTrackingParameters` method all together.
Please see https://github.com/Wikia/ad-engine/pull/2381

2024-03-05 10:44 UTC, closed without merging