ADEN-13916 optimize noads
Wikia/ad-engine pull request #2388
Opened 2024-03-08 12:15 UTC by preludek

2024-03-13 10:18 UTC, preludek commented on src/platforms/ucp-no-ads/tracking/data-warehouse.ts
> +export class DataWarehouseTracker {
I've done some refactor on a different branch and there are no duplications. I'll merge it here shortly.

2024-03-14 08:45 UTC, jbienkowski-fandom approved these changes
My comments from previous PR https://github.com/Wikia/ad-engine/pull/2394#pullrequestreview-1935243263

2024-03-14 09:17 UTC, preludek commented
> My comments from previous PR [#2394 (review)](https://github.com/Wikia/ad-engine/pull/2394#pullrequestreview-1935243263)

I've moved the tracker and will create a followup for exporting objects 👍

2024-03-14 09:43 UTC, jbienkowski-fandom approved these changes

2024-03-22 14:08 UTC, jbienkowski-fandom approved these changes

2024-03-27 11:08 UTC, jbienkowski-fandom approved these changes

2024-03-27 11:09 UTC, jbienkowski-fandom submitted a review, later dismissed

2024-04-03 11:12 UTC, adi-wesolowski-fandom requested changes

2024-04-03 11:12 UTC, adi-wesolowski-fandom commented on src/ad-tracking/data-warehouse.ts
> -	private adEngineStageSetup: AdEngineStageSetup;
did you removed src/platforms/shared/setup/ad-engine-stage.setup.ts? I dont see it

2024-04-03 11:12 UTC, adi-wesolowski-fandom commented on src/ad-tracking/data-warehouse.ts
> +				reject();
We do not handle rejecting arent we?

2024-04-03 11:12 UTC, adi-wesolowski-fandom commented on src/ad-tracking/index.ts
> -export * from './bidder-tracker';
do we really need to export everything?

2024-04-03 11:12 UTC, adi-wesolowski-fandom commented on src/ad-tracking/tracking-urls.ts
> +interface Dictionary<T = any> {
we do have code duplicating right now. Please use import, but instead of importing all index of the core, use more precise path, so only interface will be imported, not entire core

2024-04-03 11:12 UTC, adi-wesolowski-fandom commented on src/platforms/shared/setup/tracking-parameters.setup.ts
> +  trackingUrls,
```suggestion
	trackingUrls,
```

2024-04-08 08:00 UTC, preludek commented on src/ad-tracking/data-warehouse.ts
> -	private adEngineStageSetup: AdEngineStageSetup;
Yeah it got removed in the process since. It wasn't reused anywhere really.

2024-04-08 08:01 UTC, preludek commented on src/ad-tracking/data-warehouse.ts
> +				reject();
There's a catch statement in handleDwEvent if afterDocumentCompleted rejects.

2024-04-08 13:54 UTC, jbienkowski-fandom approved these changes
LGTM, nice reduction in bundle size!

2024-04-23 12:13 UTC, merged