Aden 13917 uap split1
Wikia/ad-engine pull request #2399
Opened 2024-03-15 15:41 UTC by adi-wesolowski-fandom

2024-03-22 14:39 UTC, mfarul requested changes

2024-03-22 14:39 UTC, mfarul commented on src/ad-products/templates/interface/video/learn-more.ts
> +import { communicationService } from '@ad-engine/communication';
Inconsistency here - sometimes we use ../../../../communication but here `@ad-engine/communication`. 
If we can use the latter to select just one file it will be readable much better than ../../../

2024-03-22 15:31 UTC, adi-wesolowski-fandom commented on src/ad-products/templates/interface/video/learn-more.ts
> +import { communicationService } from '@ad-engine/communication';
thx for catching this, I must have missed that. But still it is in old part of the code I tried not to touch too much. Cutting off "eventRespository" was one of the exception. I left old "communicationService" in the core/ad-product space, thats why it is still with "@"

2024-03-22 15:31 UTC, adi-wesolowski-fandom commented on src/ad-products/templates/interface/video/learn-more.ts
>  import { utils } from '@ad-engine/core';
same as above :)

2024-03-27 11:02 UTC, preludek commented on src/communication/event-types.ts
💎

2024-03-27 11:26 UTC, preludek commented on src/platforms/bingebot/ad-context.ts
RIP

2024-03-27 11:36 UTC, preludek commented on src/platforms/platforms.json
> +		"uap"
That's an odd decision to place UAP here. UAP is not a platform but rather an ad-product, maybe this can be moved somewhere more suitable?

2024-03-27 12:19 UTC, preludek commented on src/platforms/uap/utils/communication-service-slim.ts
> +// export const communicationServiceSlim = new CommunicationServiceSlim();
There are some commented lines (exports, imports, usages) here and there in the PR 🙈

2024-03-27 13:11 UTC, adi-wesolowski-fandom commented on src/platforms/platforms.json
> +		"uap"
sure

2024-03-28 10:40 UTC, adi-wesolowski-fandom commented on src/platforms/uap/utils/communication-service-slim.ts
> +// export const communicationServiceSlim = new CommunicationServiceSlim();
fixed

2024-03-28 10:41 UTC, adi-wesolowski-fandom commented on src/ad-services/open-web/index.ts
> +import {AD_ENGINE_UAP_LOAD_STATUS} from "../../communication/events/events-ad-engine-uap";
fixed

2024-03-28 10:43 UTC, adi-wesolowski-fandom commented on src/communication/events/events-ad-engine-slot.ts
> +} as const;
You mean at the end of file? I see there is such.

2024-03-28 10:43 UTC, adi-wesolowski-fandom commented on package.json
> -		"*.ts": [
Because I was unable to push commit. It was temporary. I'll try to fix it

2024-03-28 10:44 UTC, Jorewin commented on src/communication/events/events-ad-engine-slot.ts
> +} as const;
Between the event definitions

2024-03-28 10:45 UTC, adi-wesolowski-fandom commented on src/core/utils/i18n.ts
> -export function translateLabels(): void {
It wasnt used anywhere. I removed unused code in many places :)

2024-03-28 10:45 UTC, adi-wesolowski-fandom commented on src/core/services/load-new-uap.ts
> +export function loadNewUap(): void {
what do you mean?

2024-03-28 10:46 UTC, adi-wesolowski-fandom commented on src/core/providers/gpt-provider-const.ts
Because icon.json file was big. And loading such a big file, just for one icon was bad. Like 20 kB file, just for 1 kB icon.

2024-03-28 10:46 UTC, adi-wesolowski-fandom commented on src/ad-products/templates/interface/icons/fullscreen-on.ts
Hmm, yeah, maybe we could. But it need to be done wisely, not like that it was before - concating all into one big file

2024-03-28 10:49 UTC, adi-wesolowski-fandom commented on src/communication/events/events-ad-engine-uap.ts
> +export const AD_ENGINE_UAP_UNLOCK = {
it must be misspeling. Fixing... 
And what do you mean by " it looks that the name got copied from other event."?

2024-03-28 10:55 UTC, adi-wesolowski-fandom commented on src/core/providers/gpt-provider-const.ts
I did some refactor

2024-03-28 11:05 UTC, Jorewin commented on src/communication/events/events-ad-engine-uap.ts
> +export const AD_ENGINE_UAP_UNLOCK = {
The `name` property for this event is `'Invalidate slot targeting'`. It is the same as the one for `AD_ENGINE_INVALIDATE_SLOT_TARGETING` event and it doesn't seem to describe what happens. But maybe I'm mistaken, I'm not fully familiar with when this event is triggered.

2024-03-28 11:20 UTC, Jorewin commented on src/core/providers/gpt-provider-const.ts
I'm taking here about the `Adx` and `GamOrigins` constants. What you are doing right now is importing them in `src/core/providers/gpt-provider.ts` and then reexporting them under a slightly different name. I don't see a reason for doing that.

2024-03-28 15:38 UTC, Jorewin commented on src/core/services/load-new-uap.ts
> +export function loadNewUap(): void {
New name is way better. Thank you!

2024-03-28 15:40 UTC, Jorewin commented on src/communication/events/events-ad-engine-uap.ts
> +export const AD_ENGINE_UAP_UNLOCK = {
Please adjust the `name` property too. It still has the verb `unlock`.

2024-03-28 15:50 UTC, adi-wesolowski-fandom commented on src/ad-products/templates/interface/icons/fullscreen-on.ts
suggestion? I thought fit well now

2024-03-28 15:52 UTC, adi-wesolowski-fandom commented on src/core/providers/gpt-provider-const.ts
I did same thing with css class names in AdSlot

2024-03-28 15:52 UTC, Jorewin commented on src/ad-products/templates/interface/icons/fullscreen-on.ts
Well, since the only exported function is `getFullscreenOffIcon`, then the file could be called `get-fullscreen-off-icon`.

2024-03-28 15:56 UTC, Jorewin commented on src/ad-products/templates/interface/icons/fullscreen-on.ts
The one I'm "concerned" the most about is the `icon.ts` file, because its name is not informative at all and could in my opinion be `get-icon-from-svg` to match the exported function.

2024-03-29 06:55 UTC, adi-wesolowski-fandom commented on src/communication/events/events-ad-engine-uap.ts
> +export const AD_ENGINE_UAP_UNLOCK = {
sure

2024-03-29 07:58 UTC, adi-wesolowski-fandom commented on package.json
> -		"*.ts": [
fixed

2024-03-29 12:29 UTC, Jorewin commented on src/core/providers/gpt-provider-const.ts
So are you saying that doing `import { ADX } from 'src/core/providers/gpt-provider.ts` also loads unnecessary stuff?

2024-04-02 08:04 UTC, adi-wesolowski-fandom commented on src/core/providers/gpt-provider-const.ts
thats what bundle-analyzer said/showed :)

2024-04-03 11:19 UTC, Jorewin submitted a review, later dismissed

2024-04-03 15:23 UTC, WikiaJenkins commented
E2E test results: ucp-mobile, http://prod.jenkins.service.sjc.consul:8080/job/ads-wdio-docker-fandom-QE-217/100/

2024-04-03 15:35 UTC, WikiaJenkins commented
E2E test results: ucp-desktop, http://prod.jenkins.service.sjc.consul:8080/job/ads-wdio-docker-fandom-QE-217/99/

2024-04-04 15:29 UTC, WikiaJenkins commented
E2E test results: ucp-desktop, http://prod.jenkins.service.sjc.consul:8080/job/ads-wdio-docker-fandom-QE-217/134/

2024-04-18 16:53 UTC, Jorewin approved these changes

2024-05-21 11:46 UTC, closed without merging