Platform 9311 move jobs to jenkinsfiles
Wikia/ad-engine pull request #2498
Opened 2024-05-17 11:30 UTC by abador

2024-05-21 09:52 UTC, abador commented on jenkins/functions.groovy
> +  def slackChannel = '#abador'
If initial tests are fine we should change this to
```suggestion
  def slackChannel = '#adeng-release'
```

2024-05-21 14:31 UTC, slayful approved these changes

2024-05-23 09:22 UTC, szymon-nawrocki commented on jenkins/functions.groovy
> +      S3_PATH="s3://fandom-ae-assets/platforms"
```suggestion
      S3_PATH="s3://fandom-ae-assets/platforms/dev"
```

2024-05-23 09:27 UTC, szymon-nawrocki commented on jenkins/Jenkinsfile_deploy.groovy
> +def dryRun = params.dry_run
Comment for not forgetting to remove before merge :)

2024-05-23 09:36 UTC, szymon-nawrocki requested changes
Please change the s3 path for branch deployment

2024-05-24 10:14 UTC, psmagiel requested changes
Could we include running e2e tests after deploy to s3 dev succeeds, when the $commit is provided? https://github.com/Wikia/jenkins-jobs/blob/master/jobs/ads/ad-engine-platforms-deploy-branch.yaml

2024-05-27 14:47 UTC, harnash approved these changes

2024-05-28 10:37 UTC, adpaste approved these changes

2024-05-28 13:02 UTC, adpaste submitted a review, later dismissed

2024-05-29 11:19 UTC, adpaste commented on jenkins/Jenkinsfile_deploy.groovy
> +def dryRun = params.dry_run
Done.

2024-05-29 12:37 UTC, psmagiel approved these changes

2024-05-29 13:15 UTC, szymon-nawrocki commented on jenkins/Jenkinsfile_deploy_branch.groovy
> +
```suggestion
```

2024-05-29 13:20 UTC, szymon-nawrocki commented on jenkins/Jenkinsfile_deploy_branch.groovy
> +        if (commit != "") {
Okay, now I see that the commit is needed as a test parameter 🤔
Anyway it is not very intuitive that when I want to run the tests I need to provide a commit

2024-05-29 13:29 UTC, abador commented on jenkins/Jenkinsfile_deploy_branch.groovy
> +        if (commit != "") {
It's the same in the original pipeline https://github.com/Wikia/jenkins-jobs/pull/1382/files#diff-495b402a5f8bece9acb97aa4f906a7acda37a739b6b6fbeb62a3dceb530141ff

2024-05-29 13:42 UTC, szymon-nawrocki approved these changes

2024-06-03 06:49 UTC, merged