[ADEN-10468] BingeBot: sponsored logo ad slot
Wikia/ad-engine pull request #874
Opened 2020-08-12 12:43 UTC by Loczi94

2020-08-12 12:55 UTC, Bielik20 commented on platforms/bingebot/ad-context.ts
> +			fallbackConfigKey: 'fallbackInstantConfig',
We don't do that anymore. We have fallback inside context.

2020-08-19 07:56 UTC, Bielik20 requested changes

2020-08-19 07:56 UTC, Bielik20 commented on platforms/bingebot/setup/dynamic-slots/bingebot-dynamic-slots.setup.ts
> +);
Do we need to export that?

2020-08-19 07:56 UTC, Bielik20 commented on platforms/bingebot/setup/dynamic-slots/bingebot-dynamic-slots.setup.ts
> +			const adSlot = slotService.slots[action.slotId];
What about `slotService.get`?

2020-08-19 07:56 UTC, Bielik20 commented on platforms/bingebot/styles.scss
> +}
How about moving it to AdEngine?

2020-08-19 07:56 UTC, Bielik20 commented on platforms/bingebot/index.ts
> +import './styles.scss';
ditto

2020-08-19 08:16 UTC, Loczi94 commented on platforms/bingebot/styles.scss
> +}
It is in AdEngine. 🙃  You mean moving it to `src/ad-products/styles/styles.scss`? My point of view is that this style applies to element which exists only in BingeBot app so imo there is no point in moving it from here.

2020-08-19 09:38 UTC, Bielik20 approved these changes

2020-08-19 11:34 UTC, merged