ADEN-10505 Introduce Startup 2.0 to all platforms
Wikia/ad-engine pull request #882
Opened 2020-08-21 13:53 UTC by Bielik20

2020-08-26 07:05 UTC, fraszczakszymon commented on platforms/futhead/futhead-platform.ts
> +			parallel(InstantConfigSetup, () => ensureGeoCookie().then(() => bootstrapAndGetConsent())),
I believe ensureGeoCookie should happen before `InstantConfigSetup`, am I wrong?

2020-08-26 07:08 UTC, fraszczakszymon commented on platforms/futhead/futhead-platform.ts
> +			parallel(InstantConfigSetup, () => ensureGeoCookie().then(() => bootstrapAndGetConsent())),
```suggestion
			() => ensureGeoCookie(),
			parallel(InstantConfigSetup, () => bootstrapAndGetConsent()),
```

2020-08-26 07:09 UTC, fraszczakszymon commented on platforms/gamepedia/gamepedia-platform.ts
> +			parallel(InstantConfigSetup, () => ensureGeoCookie().then(() => bootstrapAndGetConsent())),
Ditto
```suggestion
			() => ensureGeoCookie(),
			parallel(InstantConfigSetup, () => bootstrapAndGetConsent()),
```

2020-08-26 07:16 UTC, fraszczakszymon commented on platforms/muthead/muthead-platform.ts
> +			parallel(InstantConfigSetup, () => ensureGeoCookie().then(() => bootstrapAndGetConsent())),
Ditto
```suggestion
			() => ensureGeoCookie(),
			parallel(InstantConfigSetup, () => bootstrapAndGetConsent()),
```

2020-08-26 07:21 UTC, fraszczakszymon commented on platforms/ucp-hydra/ucp-hydra-platform.ts
> +			GamepediaA9ConfigSetup,
Why do we name these two in a different way?

2020-08-26 07:26 UTC, fraszczakszymon commented on platforms/ucp-minerva/ucp-minerva-platform.ts
> +			GamepediaA9ConfigSetup,
Ditto

2020-08-26 07:30 UTC, fraszczakszymon requested changes
Well done 💎 . I can see one issue only: we need to fetch geo data on FUT/MUT/GP before ICBM is configured.

2020-08-31 06:41 UTC, Bielik20 commented on platforms/futhead/futhead-platform.ts
> +			parallel(InstantConfigSetup, () => ensureGeoCookie().then(() => bootstrapAndGetConsent())),
Great catch

2020-08-31 06:45 UTC, Bielik20 commented on platforms/ucp-hydra/ucp-hydra-platform.ts
> +			GamepediaA9ConfigSetup,
I don't know... my guess is someone changed one and forgot about the other 🤷 
I changed it though.

2020-08-31 07:18 UTC, fraszczakszymon approved these changes

2020-09-09 12:29 UTC, merged