ADEN-10640 Adding Top1k wikis targeting setting
Wikia/ad-engine pull request #910
Opened 2020-10-13 15:04 UTC by dmnsobczak

2020-10-13 15:15 UTC, Loczi94 requested changes

2020-10-13 15:15 UTC, Loczi94 commented on platforms/shared/context/targeting/ucp-targeting.setup.ts
> +
Key val on oasis is named `top_1k` and imo it could be set in the same way:
`top_1k: context.get('wiki.targeting.wikiIsTop1000') ? 1 : 0`

See: https://github.com/Wikia/app/blob/dev/extensions/wikia/AdEngine3/src/ml/configuration.js#L48

2020-10-14 08:08 UTC, dmnsobczak commented on platforms/shared/context/targeting/ucp-targeting.setup.ts
> +
You linked Queen of Hearts targeting. I copied this keyval name and value from general, page targeting:
https://github.com/Wikia/app/blob/dev/extensions/wikia/AdEngine3/src/targeting.js#L232

2020-10-14 08:09 UTC, Loczi94 approved these changes

2020-10-14 13:28 UTC, merged