ADEN-10628 Add Permutive to BingeBot
Wikia/ad-engine pull request #911
Opened 2020-10-13 16:53 UTC by nandy-andy

2020-10-14 10:35 UTC, Loczi94 requested changes

2020-10-14 10:35 UTC, Loczi94 commented on platforms/bingebot/modes/bingebot-ads.mode.ts
>  	}
```suggestion
		this.callExternals();
		startAdEngine();
	}

	private callExternals(): void {
		permutive.call();
	}
```

There is no need to create `inhibitors` array since we do not push anything to it.

2020-10-14 12:13 UTC, Loczi94 commented on platforms/shared/setup/base-context.setup.ts
>  		);
We have a method `isEnabled()` in `Permutive` class where we check all conditions. What do you think about including this condition in this method? Also I don't think we need to force boolean since we get `undefined` from context and it's a falsy value in JS. 🤔

2020-10-14 12:31 UTC, nandy-andy commented on platforms/shared/setup/base-context.setup.ts
>  		);
Yep, I think we could move checking `context.get('wiki.targeting.directedAtChildren')` to `isEnabled` in `Permutive` 👌

The issue with `undefined` in this case is that its falsy nature makes Permutive enabled by default if `this.instantConfig.get('icPermutive')` is `true`. That's why I think we need to force the boolean :P

2020-10-14 13:09 UTC, Loczi94 commented on platforms/bingebot/ad-context.ts
> +			directedAtChildren: false,
IMHO we don't need it because `wiki.targeting.directedAdChildren` will have falsy value (`undefined`) anyway and we should be aware that it's set to `false` in ad-contex. It's up to you if you want to leave it as is.

2020-10-14 13:10 UTC, Loczi94 approved these changes

2020-10-15 11:23 UTC, nandy-andy commented on platforms/bingebot/ad-context.ts
> +			directedAtChildren: false,
👌  discussed offline

2020-10-16 15:01 UTC, merged