ADEN-8879 add adContext and debug properties to window.ads
Wikia/ad-engine pull request #928
Opened 2020-11-06 11:21 UTC by KonradLinkowski

2020-11-09 11:21 UTC, dmnsobczak commented on src/ad-engine/services/context-service.ts
> +window.ads.adContext = context;
I don't know if this is a very elegant place for that. Maybe we can set this variable in the `Context` class constructor, like:
```
Context() {
    window.ads.adContext = this;
}
```
?

2020-11-09 11:22 UTC, dmnsobczak commented on src/ad-engine/services/context-service.ts
> +window.ads.adContext = context;
Also: we don't need to make the whole class Context public with all the set and get methods. We can just return the result of `content.get('')`, a simple object of values.

2020-11-09 11:24 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		window.ads.debug = (groups: string) => this.cookieStorage.setItem('adengine_debug', groups);
I didn't even know that we were already checking if `adengine_debug` cookie exists :o Nice.

But one suggestion: we can easily enable debug mode: can we also add a method to disable it? It's simpler than looking for and removing cookie manually.

2020-11-09 11:27 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		window.ads.debug = (groups: string) => this.cookieStorage.setItem('adengine_debug', groups);
https://github.com/Wikia/ad-engine/blob/dev/src/ad-engine/utils/logger.ts#L7
This chunk of code happens only at the beginning, during AdEngine start. Is is any way to enable/disable debug mode during AdEngine work without reloading the page? 
If not, maybe it's a good ideal to add automatic page refresh after enabling debug mode?

2020-11-09 11:28 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		window.ads.debug = (groups: string) => this.cookieStorage.setItem('adengine_debug', groups);
Another bonus: Any message in console like: `AdEngine Debug Mode enabled`?

2020-11-09 11:30 UTC, dmnsobczak commented on src/ad-engine/services/context-service.ts
> +window.ads.adContext = context;
Linter is failing:
`TypeError: Cannot set property 'adContext' of undefined`
Maybe this will fix the issue?
```
window.ads = window.ads || {};
window.ads.adContext = window.ads.adContext || context;
```

2020-11-09 11:31 UTC, dmnsobczak requested changes
Linter + few suggestions after code review.

2020-11-09 11:50 UTC, KonradLinkowski commented on src/ad-engine/ad-engine.ts
> +		window.ads.debug = (groups: string) => this.cookieStorage.setItem('adengine_debug', groups);
> But one suggestion: we can easily enable debug mode: can we also add a method to disable it? It's simpler than looking for and removing cookie manually.

I'm pretty sure that using `window.ads.debug('0')` disables debug mode.

> Is is any way to enable/disable debug mode during AdEngine work without reloading the page?

I could make an interval checking if debug mode changed, but it probably isn't a good practice. I believe that there is other way of doing this, but I don't know ad-engine very well right now.

>  Any message in console

Sure

2020-11-09 11:56 UTC, KonradLinkowski commented on src/ad-engine/services/context-service.ts
> +window.ads.adContext = context;
> Also: we don't need to make the whole class Context public with all the set and get methods. We can just return the result of content.get(''), a simple object of values.

I thought that the task is about adding access to the whole context object, but it makes sense to expose only the `get` method as you pointed out. Maybe it would be even better if this method would return whole context data as json or js object, but I'm not sure about the usage though.

> Linter is failing

Husky hooks fired when I created the commit, but the linter didn't detect anything then so that's weird.

2020-11-12 12:01 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +		window.ads.debug = (groups: string | null) =>
What will happen if I will run `window.ads.debug()`? I think that this part of code won't run correctly:
https://github.com/Wikia/ad-engine/blob/dev/src/ad-engine/utils/logger.ts#L16
Can we make default value of `groups` parameter as `1`? Then `debug()` will enable debug mode and `debug(null)` will disable it.

2020-11-12 12:02 UTC, dmnsobczak commented on src/ad-engine/services/context-service.ts
> +		window.ads.adContext = contextObject;
Make sure to add to QA notes memo to check whether `adContext` object is always up-to-date, no matter when we'll try to read it.

2020-11-12 12:04 UTC, dmnsobczak requested changes
Linter is still failing. Try running `npm run lint` locally before pushing new commits.

Also, what about those two?
> If not, maybe it's a good ideal to add automatic page refresh after enabling debug mode?
> Another bonus: Any message in console like: AdEngine Debug Mode enabled?

2020-11-13 09:41 UTC, dmnsobczak commented on src/ad-engine/ad-engine.ts
> +			logger('ad-engine', 'AdEngine Debug Mode enabled');
`logger('ad-engine', 'AdEngine Debug Mode' + groups !== null ? 'enabled' : 'disabled');`
?

2020-11-13 11:00 UTC, dmnsobczak approved these changes

2020-11-17 09:33 UTC, merged