ADEN-10686 rotator interval change
Wikia/ad-engine pull request #934
Opened 2020-11-20 11:49 UTC by KonradLinkowski

2020-11-20 14:21 UTC, dmnsobczak commented on src/ad-products/utils/fmr-rotator.ts
> +							}, customDelays[slot.lineItemId] || this.refreshInfo.refreshDelay);
If somebody disable the icVariable completely then `customDelays` will be undefined, and `undefined[slot.lineItemId]` will result in error. What about:
`const customDelays = context.get('options.rotatorDelay') || {};`
or
`this.instantConfig.get('icRotatorDelay', {})`
?

2020-11-20 14:23 UTC, dmnsobczak commented on platforms/shared/setup/base-context.setup.ts
> +		context.set('options.rotatorDelay', this.instantConfig.get('icRotatorDelay'));
This is setup file for new MediaWiki+AdEngine integration (aka UCP), but we are still using old AdEngine integration - without platforms in `app` repository. We need second pull request with the same change here:
https://github.com/Wikia/app/blob/dev/extensions/wikia/AdEngine3/src/setup.js#L121

2020-11-20 14:24 UTC, dmnsobczak requested changes
Possible error and second PR for app repository

2020-11-22 12:08 UTC, KonradLinkowski commented on platforms/shared/setup/base-context.setup.ts
> +		context.set('options.rotatorDelay', this.instantConfig.get('icRotatorDelay'));
https://github.com/Wikia/app/pull/18246

2020-11-23 09:02 UTC, dmnsobczak approved these changes

2020-11-25 09:50 UTC, merged