ADEN-10495 | Pass Permutive keys to Appnexus and Rubicon
Wikia/ad-engine pull request #943
Opened 2020-12-03 13:20 UTC by Loczi94

2020-12-04 13:10 UTC, dmnsobczak commented on src/ad-bidders/prebid/adapters/appnexus-ast.ts
> +import { permutive } from '@ad-engine/services';
Well, there is a reason why we don't want to import modules between packages. Are you sure it won't broke anything?

2020-12-04 13:13 UTC, dmnsobczak commented on src/ad-bidders/prebid/adapters/appnexus-ast.ts
> +				p_standard: permutive.getPermutiveKeys(),
Why don't you put it here?
https://github.com/Wikia/ad-engine/blob/dev/src/ad-bidders/prebid/prebid-adapter.ts#L44

2020-12-04 13:15 UTC, dmnsobczak commented on src/ad-bidders/prebid/adapters/rubicon-display.ts
> +				...this.getTargeting(code, this.customTargeting),
We are forgetting about data from `targeting` parameter:
`this.getTargeting(code, { ...(targeting || {}), ...this.customTargeting })`

2020-12-04 13:17 UTC, dmnsobczak requested changes
Unit tests are failing

2020-12-04 13:49 UTC, Loczi94 commented on src/ad-bidders/prebid/adapters/rubicon-display.ts
> +				...this.getTargeting(code, this.customTargeting),
Yep, you're right. 🙈

2020-12-09 14:41 UTC, dmnsobczak approved these changes

2020-12-09 14:48 UTC, dmnsobczak commented
Unit tests are failing. @Loczi94 please fix :)

2020-12-10 13:28 UTC, dmnsobczak approved these changes

2020-12-16 12:39 UTC, merged