WIP
Wikia/ad-engine pull request #951
Opened 2020-12-23 11:17 UTC by KonradLinkowski

2020-12-28 10:50 UTC, dmnsobczak commented on platforms/ucp/ad-context.ts
> +			enabled: true,
Remember to set this to `false` and use icVariable instead during testing, because this will enable RealVu everywhere.

2020-12-29 11:31 UTC, nandy-andy commented on platforms/shared/setup/base-context.setup.ts
> +			this.instantConfig.get('icRealVu') && context.get('wiki.opts.enableRealVu'),
Do we need to check `'wiki.opts.enableRealVu'` from context? It's inconsistent with the rest of our integrations but maybe we decided at some point we want this feature to be enabled by a community 🤔

2020-12-29 11:33 UTC, nandy-andy commented on src/ad-services/real-vu/index.ts
> +			utils.logger(logGroup, 'disabled');
I do like the way you used logging. Using our query-string param will inform us about each state of the RealVu loading process 👍

2020-12-29 11:35 UTC, nandy-andy commented on platforms/shared/setup/base-context.setup.ts
> +			this.instantConfig.get('icRealVu') && context.get('wiki.opts.enableRealVu'),
OK, I can see https://github.com/Wikia/unified-platform/pull/4393/files#diff-7d714ea1f52e468d81ef41f5d41b61c71ad9b962b6eeefd55eed0b9da1050969R172 so it means you decided to make it flexible (per platform/geo/community) 👌

2020-12-29 11:35 UTC, nandy-andy approved these changes

2020-12-29 11:40 UTC, dmnsobczak commented on platforms/shared/setup/base-context.setup.ts
> +			this.instantConfig.get('icRealVu') && context.get('wiki.opts.enableRealVu'),
`AC: 1. Add the following RealVu tag on the pages of specific communities (communities TBD)`

2020-12-29 11:42 UTC, dmnsobczak commented on platforms/ucp/ad-context.ts
> +		realVu: {
This config value needs to be copied into `ucp-hydra`, `ucp-minerva` and `ucp-mobile` ad-contexts as well.

2020-12-29 11:43 UTC, dmnsobczak requested changes
Add config to 3 remaining platforms

2020-12-29 12:32 UTC, nandy-andy commented on platforms/shared/setup/base-context.setup.ts
> +			this.instantConfig.get('icRealVu') && context.get('wiki.opts.enableRealVu'),
I missed it 🙈 All clear, thanks! :)

2020-12-29 18:17 UTC, nandy-andy approved these changes

2020-12-30 06:55 UTC, dmnsobczak approved these changes

2020-12-30 09:48 UTC, nandy-andy commented on platforms/shared/setup/base-context.setup.ts
> +			this.instantConfig.get('icRealVu') && context.get('wiki.opts.enableRealVu'),
But then... we don't need `icRealVu`, do we?

2020-12-30 09:50 UTC, dmnsobczak commented on platforms/shared/setup/base-context.setup.ts
> +			this.instantConfig.get('icRealVu') && context.get('wiki.opts.enableRealVu'),
In case of any issues icVariable is faster than wgVariable. Also I think that in the future we'll drop the wgVariables and RealVu will be managed only using ICBM :)

2020-12-30 13:37 UTC, merged