ADEN-10808 remove LiveRamp integration
Wikia/ad-engine pull request #967
Opened 2021-02-08 13:56 UTC by Tomasz-at-Fandom

2021-02-16 13:55 UTC, Loczi94 requested changes
There is still ATS-related code in ad-engine. Also, I think we can update prebid.js here: https://github.com/Wikia/ad-engine/blob/dev/src/ad-engine/services/pbjs-factory.ts#L5 :)

2021-02-16 13:55 UTC, Loczi94 commented on platforms/shared/tracking/tracking.setup.ts
>  	private atsTracker(): void {
This is also LiveRamp-connected code thus it should be deleted.

2021-02-16 15:52 UTC, Tomasz-at-Fandom commented on platforms/shared/tracking/tracking.setup.ts
>  	private atsTracker(): void {
Thanks! Done.

2021-02-18 12:37 UTC, dmnsobczak commented on src/ad-engine/services/pbjs-factory.ts
> +	'//static.wikia.nocookie.net/fandom-ae-assets/prebid.js/v4.17.0/20210217.min.js';
This line is a third fallback, we don't need to worry about that and actually we can clean this up, but thanks for remembering about that :)

2021-02-18 12:38 UTC, dmnsobczak commented on src/ad-bidders/index.ts
>  export * from './prebid/ats';
I think we can remove that too.

2021-02-18 12:39 UTC, dmnsobczak requested changes
I think we can remove `/src/ad-bidders/prebid/ats` module too.

2021-02-19 09:31 UTC, Tomasz-at-Fandom commented on src/ad-bidders/index.ts
>  export * from './prebid/ats';
As per our Zoom discussion, since this point to more ATS Analytics code, I will talk to Paulina to make sure we are not removing too much. To be continued...

2021-02-19 12:43 UTC, Tomasz-at-Fandom commented on src/ad-bidders/index.ts
>  export * from './prebid/ats';
The Ats class was removed

2021-02-19 12:43 UTC, Tomasz-at-Fandom commented on src/ad-engine/services/pbjs-factory.ts
> +	'//static.wikia.nocookie.net/fandom-ae-assets/prebid.js/v4.17.0/20210217.min.js';
Done

2021-02-22 12:26 UTC, Loczi94 commented on src/ad-engine/services/pbjs-factory.ts
> -			scriptLoader.loadScript(libraryUrl || prebidLibraryUrl, 'text/javascript', true, 'first');
I think we have Prebid.js url in code to prevent situation when Instant Config service does not respond. 🤔  But still, we have fallback-config.json where we store Prebid.js url. What do you think @dmnsobczak?

2021-02-22 12:30 UTC, dmnsobczak commented on src/ad-engine/services/pbjs-factory.ts
> -			scriptLoader.loadScript(libraryUrl || prebidLibraryUrl, 'text/javascript', true, 'first');
1. Response from ICBM
2. fallback-config
3. This line
It can happen only for new platform which don't have fallback-config saved yet or variable was not enabled for this service in the past 24 hours. It's quite impossible to achieve and sounds like a small impact. I'm fine with removing it :D

2021-02-22 12:35 UTC, Loczi94 commented on src/ad-engine/services/pbjs-factory.ts
> -			scriptLoader.loadScript(libraryUrl || prebidLibraryUrl, 'text/javascript', true, 'first');
Okay, thanks @dmnsobczak! I'm ok with it, too. It's one place less where we need to update the url.

2021-02-22 12:36 UTC, Loczi94 approved these changes

2021-02-22 13:11 UTC, dmnsobczak approved these changes

2021-02-22 13:51 UTC, Tomasz-at-Fandom commented on src/ad-engine/services/pbjs-factory.ts
> -			scriptLoader.loadScript(libraryUrl || prebidLibraryUrl, 'text/javascript', true, 'first');
Ideally, from developers perspective, all configuration variables with fallback values should be managed / loaded in one place. If we have something like that then let's stick to it, to avoid duplication and for nice encapsulation of concerns :)

2021-02-24 15:57 UTC, merged