ADEN-10866 | ucp-mobile: Lazy requesting for ICBs
Wikia/ad-engine pull request #988
Opened 2021-04-02 12:51 UTC by Loczi94

2021-04-09 14:56 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +					slotElement.parentElement.classList.remove('loading');
This will be needed to be changed to `slotElement.parentElement.classList.remove('is-loading');` after the `top_boxad` changes with cleanup kicks in. Let's keep it in mind and coordinate accordingly depending on which changes get merged first 👌

2021-04-09 15:01 UTC, Loczi94 commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +					slotElement.parentElement.classList.remove('loading');
Ok, good point!

2021-04-09 15:07 UTC, nandy-andy commented on src/ad-engine/services/slot-placeholder-injector.ts
> +	repeat?: number;
This may be confusing that in the `SlotCreatorConfig` is [an object](https://github.com/Wikia/ad-engine/pull/988/files#diff-e1e9d500924692b52cba6ee6b57650e6b0798027970960c7ee2bca5e2e93e1ebR152-R162) and in `SlotPlaceholderConfig` it's a number. I don't know what to do with it. Just sharing my thoughts ;)

2021-04-09 15:09 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +		const slotName = 'incontent ad';
The value assigned to `slotName` looks odd.

2021-04-09 15:10 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +		} else if (context.get('wiki.opts.enableICBPlaceholder')) {
Don't we need here one more `else if` for `'wiki.opts.enableICPPlaceholder'` case?

2021-04-09 15:13 UTC, nandy-andy commented on src/ad-engine/services/slot-placeholder-injector.ts
> +		let repeat = 2;
Where does the magical `2` come from?

2021-04-09 15:14 UTC, Loczi94 commented on src/ad-engine/services/slot-placeholder-injector.ts
> +	repeat?: number;
I agree. I renamed it to `repeatLimit`.

2021-04-09 15:16 UTC, Loczi94 commented on src/ad-engine/services/slot-placeholder-injector.ts
> +		let repeat = 2;
If we repeat a placeholder it means that it is a second placeholder in the row. Do you have any ideas how to refactor this part?

2021-04-09 15:17 UTC, Loczi94 commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +		} else if (context.get('wiki.opts.enableICBPlaceholder')) {
We have this part in separate method - `configureICPPlaceholderHandler`.

2021-04-09 15:17 UTC, nandy-andy commented on src/ad-engine/services/slot-placeholder-injector.ts
> +}
These methods are similar but much simpler than https://github.com/Wikia/ad-engine/pull/988/files#diff-23599229e919b398dd805ce5482ab0504f06c3e54ea1eb97d2bb00928e552839L60-L93 I wonder if we can make a reusable abstraction for it in the future. Nothing to address now, just to keep in mind when thinking about potential future dev improvements :)

2021-04-09 15:23 UTC, nandy-andy commented on src/ad-engine/services/slot-placeholder-injector.ts
> +		let repeat = 2;
Not right now. My brain does not work anymore ;) It starts thinking about getting the start number from somewhere else where it's already there (for example the index from the slot name `incontent_boxad_2`) but it's overcomplicating, isn't it? Right now just a comment why it's 2 will do, I guess 🤷‍♂️

2021-04-09 15:25 UTC, nandy-andy commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +				context.set('slots.incontent_boxad_1.insertBeforeSelector', '');
What do you think of moving this logic to the `SlotPlaceholderInjector`? I assume it'll make `injectIncontentAdsPlaceholders()` more readable.

2021-04-09 15:40 UTC, Loczi94 commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-slots-definition-repository.ts
> +				context.set('slots.incontent_boxad_1.insertBeforeSelector', '');
This part is strictly connected with ICBs logic. I'd rather keep these two things separate:

- SlotPlaceholderInjector class with code which injects placeholders (in the future it can be used for injecting not only incontent ads placeholders)
- UcpMobileSlotsDefinitionRepository class with all 'configuration' code like setting context.

Both - injecting placeholders and injecting ICB1 wait for the same UAP action thus moving this part to SlotPlaceholderInjector won't change an order in which the code is run.

2021-04-12 11:28 UTC, Tomasz-at-Fandom commented
Was there any change done to the content of all the modified .json files or were they just reformatted?

2021-04-12 13:22 UTC, Loczi94 commented
@Tomasz-at-Fandom there wasn't any change. Please, just ignore them.

2021-04-12 14:22 UTC, Tomasz-at-Fandom requested changes

2021-04-12 17:23 UTC, Tomasz-at-Fandom requested changes

2021-04-13 08:26 UTC, Loczi94 commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +				)
I can see your point but my point was not to listen to and pipe actions if it is not necessary. 🤔  That is why I placed this code within 'if' blocks.

2021-04-13 08:30 UTC, Tomasz-at-Fandom requested changes

2021-04-13 08:30 UTC, Tomasz-at-Fandom commented on platforms/ucp-mobile/setup/dynamic-slots/ucp-mobile-dynamic-slots.setup.ts
> +				)
A yes I see, well we could just make another `if` block checking if the subscription function was defined and if so then make the subscription :)

2021-04-13 11:49 UTC, Tomasz-at-Fandom approved these changes

2021-04-14 15:39 UTC, merged